### PR TITLE
Bump XAT for new LibZipSharp

### PR DESCRIPTION
**Pull request by grendello**

### CODE REVIEW

**Comment by jonpryor** [comment]
squash-and-merge:

```markdown
Bump to mono/mono.posix@d8994ca, xamarin/LibZipSharp@98e9173

Changes: https://github.com/mono/mono.posix/compare/e1269a564a022b143769785714968a52091c10a4...d8994caaf29f0a95022ee4d1d51ae0a55150ce92

  * mono/mono.posix@d8994ca: Remove Windows support completely for now

    Fixes an issue in which Mono.Unix would try to resolve `libc`
    P/Invokes by looking for the `msvcrt` library on Unix machines.

  * mono/mono.posix@74d504f: Fix yaml template path
  * mono/mono.posix@127cf9e: [build] Don't rebuild managed code on packaging time on Windows

Changes: https://github.com/xamarin/LibZipSharp/compare/2.0.4...2.0.7

  * xamarin/LibZipSharp@98e9173: Bump version to 2.0.7
  * xamarin/LibZipSharp@6e1e1b3: Localized file check-in by OneLocBuild Task: Build definition ID 11678: Build ID 6581869 (#119)
  * xamarin/LibZipSharp@1c05430: LEGO: Merge pull request 118
  * xamarin/LibZipSharp@06d44d8: Localized file check-in by OneLocBuild Task: Build definition ID 11678: Build ID 6570668 (#117)
  * xamarin/LibZipSharp@37f3894: LEGO: Merge pull request 116
  * xamarin/LibZipSharp@6c0edc5: Update libzip and zlib submodules (#115)
  * xamarin/LibZipSharp@acd9a54: [Localization] Switch from xlf to resx files  (#112)
  * xamarin/LibZipSharp@3cece80: LEGO: Merge pull request 114
  * xamarin/LibZipSharp@fe336b4: LEGO: Merge pull request 113
  * xamarin/LibZipSharp@9aee99a: [Localization] Add OneLocBuild job (#111)
  * xamarin/LibZipSharp@bdfa9f8: Bump Mono.Unix to 7.1.0-final.1.21458.1 (#110)

Changes: https://github.com/xamarin/xamarin-android-tools/compare/9c641b3e08e56db37467a64a2c5de2c7f7ddb3ef...29f11f2a304376bfa96de999a78083fe5a8174c6

  * xamarin/xamarin-android-tools@29f11f2 Bump to mono/mono.posix@d8994ca, xamarin/LibZipSharp@98e9173 (#193)
  * xamarin/xamarin-android-tools@7cfe683 [ci] Use Microsoft.SourceLink.GitHub (#192)
  * xamarin/xamarin-android-tools@01a0dde [Localization] Import translated resx files (#189)
  * xamarin/xamarin-android-tools@cc715d9 [Xamarin.Android.Tools.AndroidSdk] Permit NDK r25 (#190)
  * xamarin/xamarin-android-tools@3c55e9a Avoid `Environment.SpecialFolder.ApplicationData` (#188)
  * xamarin/xamarin-android-tools@0d55472 LEGO: Merge pull request 187
  * xamarin/xamarin-android-tools@6946512 Juno: check in to juno/hb_befb220e-87ce-47e9-a9e6-10ea592b2337_20220729154833425. (#186)
  * xamarin/xamarin-android-tools@6e3433a Juno: check in to juno/hb_befb220e-87ce-47e9-a9e6-10ea592b2337_20220729025332507. (#185)
  * xamarin/xamarin-android-tools@73c4388 [Xamarin.Android.Tools.AndroidSdk] Update SDK component for API-33 (#184)
  * xamarin/xamarin-android-tools@da3653e [Xamarin.Android.Tools.AndroidSdk] Add API-33 to KnownVersions
  * xamarin/xamarin-android-tools@327d433 [ci] Run OneLocBuild on a schedule (#180)
  * xamarin/xamarin-android-tools@8ab60e4 [ci] Use latest macOS and Windows images (#181)
  * xamarin/xamarin-android-tools@4dd3292 LEGO: Merge pull request 182
  * xamarin/xamarin-android-tools@56b61f1 [Localization] Add OneLocBuild job (#175)
  * xamarin/xamarin-android-tools@14076a6 [Xamarin.Android.Tools.AndroidSdk] Add API-32 to KnownVersions
```

**Comment by jonpryor** [comment]
Waiting on the Windows build to complete successfully.

**Comment by dellis1972** [comment]
Looks like we need to bump Mono.Unix in the `android-sdk-installer` which is pulled in via `monodroid`.

`Could not load file or assembly 'Mono.Unix, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. `

**Comment by dellis1972** [comment]
Depends on https://github.com/xamarin/android-sdk-installer/pull/692

**Pull request merged**
