### PR TITLE
Fixed the issue #1931

### PR DESCRIPTION
**Pull request by rubo**
HTTP headers `Server` and `User-Agent` must use space symbol as a separator instead of comma as defined in [RFC 7231](https://tools.ietf.org/html/rfc7231). Implemented this requirement similar to what have been done for NSUrlSessionHandler.cs in Xamarin.iOS.

See the issue #1931

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
@grendello can you review when you have a chance?

I would see if we can add some kind of test checking this case. We have some on-device tests calling a HTTP server already, right?

**Comment by dellis1972** [comment]
I agree with @jonathanpeppers a unit test would be nice for this. @grendello do we have anything like that?

**Comment by rubo** [comment]
@jonathanpeppers @dellis1972 Found the unit test and updated it.

Also revised the fix by removing special handling for the `Server` header. The reason is `HttpRequestHeaders` doesn't process the `Server` header as a collection like `User-Agent` (although they have similar spec in RFC) so there's no problem with it. Thus, the special handling for the `Server` header is redundant in NSUrlSessionHandler.cs too for Xamarin.iOS.

**Comment by jonpryor** [comment]
build

**Pull request merged**
