### PR TITLE
[Xamarin.Android.Build.Tasks] remove <Dx/> task

### PR DESCRIPTION
**Pull request by jonathanpeppers**
There was only one place in monodroid where the `<Dx/>` task was still
used, which I was able to recently remove.

We should remove `<Dx/>` to avoid confusion between the other related
tasks that are in use:
* `<CompileToDalvik/>`
* `<D8/>` and `<R8/>`

This will simplify places in monodroid where I need to add d8 support.

There is a scenario where "Enhanced Fast Deployment" compiles dex
files using these tasks.

### CODE REVIEW

**Comment by jonpryor** [comment]
The [**macOS PR Release Build**](https://jenkins.mono-project.com/job/xamarin-android-pr-builder-release/912/) failed because AOT failed:

```
error : One or more errors occurred. (ApplicationName='…/cross-arm', ... Native error= Cannot find the specified file
error : at System.Threading.Tasks.TaskReplicator.Run[TState] ...
...
```

The AOT build failed because the AOT cross-compiler doesn't exist, because the mono bundle didn't exist:

```
warning : Unable to download URL `https://****.azureedge.net/mono-jenkins/xamarin-android/xamarin-android/bin/Release/bundle-v21-h1b15cd2e-Release-Darwin-libzip=b95cf3f,llvm=349752c,mono=b041669.zip` to ...
warning : 404 (Not Found)
```

@mjbond-msft [mentioned](https://xamarinhq.slack.com/archives/C03CEGRUW/p1551110487536800) why this would be happening:

> regarding the issue involving a change to the expected drop location with the `xamarin-android` (release) build. i think i see the problem. when moving to the jenkinsfile solution, i in inadvertently changed the point-of-reference for the package publish operation to start from within the `xamarin-android` source directory; whereas in the original configuration (as currently used by the debug build) publish happens one directory level up.

We'll need a PR against `build-tools/automation/build.groovy` to fix this, which will allow PR builds to be green.

@dellis1972 : Alternative, we need to re-investigate our unit tests so that AOT-related tests only fail if the `cross-*` compilers actually exist, and ignore the tests if they don't exist.  I had thought we had done this previously...

**Comment by dellis1972** [comment]
@jonpryor we do have this method which checks for the cross compilers https://github.com/xamarin/xamarin-android/blob/23c30056a8a11b1bf80a2b7bb7d64b44b4351545/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.ProjectTools/Common/Builder.cs#L165

**Comment by dellis1972** [comment]
These are called in various tests https://github.com/xamarin/xamarin-android/blob/b08240ee50e941cb326688cc0dcf5969ebfe5473/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs#L664

**Comment by dellis1972** [comment]
Also this line https://github.com/xamarin/xamarin-android/blob/b08240ee50e941cb326688cc0dcf5969ebfe5473/build-tools/scripts/RunTests.targets#L122 assumes that if we build in Release mode get have the AOT compilers.

**Pull request merged**
