### PR TITLE
[ci] Parallelize MSBuild Test Suites

### PR DESCRIPTION
**Pull request by jpobst**
This parallelizes our MSBuild test suite (`Xamarin.Android.Build.Tests.dll`) to run on 3 machines concurrently instead of 1.  This is accomplished by applying `[Category]` attributes to the NUnit TestFixtures to specify which "node" they should run on:

```
[Category ("Node-3")]
public class BuildAssetsTest : BaseTest
```

I've done some initial load balancing between the 3 nodes, but `Node-1` only runs `class BuildTest` and it needs to be broken down into multiple classes so we can move some to `Node-2`.  This will be a future request for @dellis1972 or @jonathanpeppers so we can get a better distribution.

## Results
```
Today:
- MSBuild - MacOS: 1h 43m 48s
- MSBuild - Windows: 1h 34m 45s

PR:
- MSBuild - Mac-1: 1h 5m 45s
- MSBuild - Mac-2: 26m 0s
- MSBuild - Mac-3: 44m 50s
- MSBuild - Windows-1: 52m 41s
- MSBuild - Windows-2: 16m 18s
- MSBuild - Windows-3: 39m 55s
```

If a new TestFixture is created and it does not specify a `Node-X` category it will be run on `Node-2` in the `run Xamarin.Android.Build.Tests - Mac/Windows - No Node` step.  This is a backup mechanism, it is expected that every TestFixture specifies a Node.

### CODE REVIEW

**Comment by pjcollins** [comment]
We may need t revisit how much work we're trying to do in parallel in general, especially on Windows. It looks like some of the latest Windows runs here are taking almost as long as a full run? At least we don't seem to be seeing timeouts with these changes which is definitely a plus, but it looks like we're still [seeing a test slowdown][0] for certain tests running in parallel:

```
=> Xamarin.Android.Build.Tests.BuildTest.CheckSequencePointGeneration(True,False,False,True,"PdbOnly",False,"release")
[TESTLOG] Test CheckSequencePointGenerationTrueFalseFalseTruePdbOnlyFalserelease Starting
Using C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
Using msbuild
Found Time Elapsed 00:05:09.6500000
Found Time Elapsed 00:00:02.2100000
[TESTLOG] Test CheckSequencePointGenerationTrueFalseFalseTruePdbOnlyFalserelease Complete
[TESTLOG] Test CheckSequencePointGenerationTrueFalseFalseTruePdbOnlyFalserelease Outcome=Passed
=> Xamarin.Android.Build.Tests.BuildTest.CheckSequencePointGeneration(True,True,True,True,"PdbOnly",False,"release")
[TESTLOG] Test CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease Starting
Using C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
Using msbuild
Found Time Elapsed 00:07:01.9200000
Found Time Elapsed 00:00:24.1100000
[TESTLOG] Test CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease Complete
[TESTLOG] Test CheckSequencePointGenerationTrueTrueTrueTruePdbOnlyFalserelease Outcome=Passed
=> Xamarin.Android.Build.Tests.BuildTest.CheckSequencePointGeneration(True,False,True,False,"",False,"release")
[TESTLOG] Test CheckSequencePointGenerationTrueFalseTrueFalseFalserelease Starting
Using C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
Using msbuild
Found Time Elapsed 00:08:19.2300000
Found Time Elapsed 00:00:02.3400000
```

I don't think these should be taking minutes to run, even on low performance hardware?

[0]: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3576462&view=logs&jobId=a0ad45fc-ebd0-5737-7a5a-bb0648ae4277&j=a0ad45fc-ebd0-5737-7a5a-bb0648ae4277&t=37a55d53-c63e-55b3-dc83-effd398fca81

**Comment by jpobst** [comment]
I was waiting for more data, but I think these new Windows agents are dramatically slower than the ones we had last week.  Here's my previous run where all the suites completed in well under an hour: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3575766&view=results.

**Comment by pjcollins** [comment]
I think we just bring the machines to a crawl sometimes, I had seen this on the previous scaling set pool, and the static VM pool before that.

**Comment by jpobst** [comment]
👍  I rebased on `master` which contains test fixes, and now the relevant suites on this PR are green.

**Pull request merged**
