### PR TITLE
[d17-5] [tests] verify we can build/run on API 34

### PR DESCRIPTION
**Pull request by jonathanpeppers**
For classic Xamarin.Android projects.

This will be in draft to be sure the test works (expected to fail). Then I will cherry-pick the required fixes here.

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
Awesome, the tests fail:

image

So now I'll cherry-pick something to fix it. 🤞

**Comment by jonathanpeppers** [comment]
Looks good now:

image

**Comment by jonpryor** [comment]
```markdown
[build] Bump `$(XABuildToolsVersion)`=34 (#8314)

Context: https://developer.android.com/tools/releases/build-tools
Context: https://developer.android.com/google/play/requirements/target-sdk

Starting 2023-08-31, new apps must target API-33.

We assume that starting in 2024-08-31, new apps must in turn target
API-34.

This provides a bit of a conundrum for existing Classic Xamarin.Android
customers who may have concerns about the pending 2024-08-31 deadline,
and may not be comfortable migrating to .NET 8 in that timeframe.

What do we want?  We'd like Classic Xamarin.Android to be able to
target Android 14 (API-34) with as minimum an effort as possible.
(By which we mean "NO API-34 BINDINGS!")  This would allow existing
Classic Xamarin.Android customers to set `targetSdkVersion`=34.

As far as we can tell, *no* API-34 APIs are required in order to
set [`//uses-sdk/@android:targetSdkVersion`][0]=34 within
`AndroidManifest.xml`.

What *is* required in order to set `targetSdkVersion` to 34 is to use
a newer `aapt2`.  Using the `aapt2` that is included with
Xamarin.Android 13.2.1.2 while setting `targetSdkVersion`=34 will
result in a build error such as:

	[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Write fault on path …/Scratch.TryTargetApi34/[Unknown]
	  at System.IO.FileStream.WriteInternal (System.Byte[] src, System.Int32 offset, System.Int32 count)
	  at System.IO.FileStream.Write (System.Byte[] array, System.Int32 offset, System.Int32 count)
	  at System.IO.StreamWriter.Flush (System.Boolean flushStream, System.Boolean flushEncoder)
	  at System.IO.StreamWriter.WriteSpan (System.ReadOnlySpan`1[T] buffer, System.Boolean appendNewLine)
	  at System.IO.StreamWriter.WriteLine (System.String value)
	  at Xamarin.Android.Tasks.Aapt2Daemon.Aapt2DaemonStart ()
	  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state)
	  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
	  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx)
	  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state)
	  at System.Threading.ThreadHelper.ThreadStart ()

If you download a newer `aapt2`, you can override the
`$(Aapt2ToolPath)` and `$(Aapt2ToolExe)` MSBuild properties to use a
more recent `aapt2`, which will allow the build to complete.

Update the `$(XABuildToolsVersion)` and related MSBuild properties
within `Configuration.props` so that we redistribute the `aapt2` from
the Android SDK Build Tools 34.0.0 package.  This will allow Classic
Xamarin.Android apps to update the `targetSdkVersion` value within
`AndroidManifest.xml` to API-34.

*Note*: this *may* result in a build warning such as:

	…/Xamarin.Android.Legacy.targets(348,5): warning XA1008: The TargetFrameworkVersion (Android API level 33) is lower than the targetSdkVersion (34). Please increase the `$(TargetFrameworkVersion)` or decrease the `android:targetSdkVersion` in the `AndroidManifest.xml` so that the API levels match.

This warning may be ignored.

[0]: https://developer.android.com/guide/topics/manifest/uses-sdk-element#target
```

**Comment by jonpryor** [comment]
@jonathanpeppers: please review the draft commit message, above.

**Comment by jonathanpeppers** [comment]
LGTM! We could do a merge commit or rebase & merge for the two commits, but it's up to you.

**Pull request merged**
