### PR TITLE
[One .NET] remove NuGet workarounds

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://github.com/xamarin/xamarin-android/issues/5896

Since early in .NET 5 development, we had workarounds (hacks?) for
enabling the legacy Xamarin.Forms NuGet package to work correctly. We
used `$(PackageTargetFallback)` so that `monoandroid` assemblies would
be used in NuGet packages. We also had to fix up item groups manually
so `monoandroid` could be chosen over `netstandard`.

We should be able to remove these workarounds, since we now have a
dotnet/installer with this change:

https://github.com/NuGet/NuGet.Client/commit/10274281c37e9dd3626938757f7e947d649b821b

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
I don't think this will actually work yet, I get errors building `HelloAndroid`:

```
HelloAndroid.csproj : error NU1202: Package Xamarin.AndroidX.Migration 1.0.8 is not compatible with net6.0-android30.0 (.NETCoreApp,Version=v6.0). Package Xamarin.AndroidX.Migration 1.0.8 supports: monoandroid90 (MonoAndroid,Version=v9.0)
```

**Comment by jonathanpeppers** [comment]
This is mostly green, but new `.so` files are showing up:
```
349,816 lib/arm64-v8a/libmono-component-diagnostics_tracing.so *2
167,608 lib/arm64-v8a/libmono-component-hot_reload.so *2
```
Are we supposed to do something that excludes these? Question for next week.

**Comment by jonathanpeppers** [comment]
I'm going to wait on: https://github.com/xamarin/xamarin-android/pull/5977

Then come back to this.

**Comment by jonathanpeppers** [comment]
Only error I'm seeing in the latest run:
```
[BT : 1.4.0] error : Error retrieving device SDK version. Please try again. [/Users/runner/work/1/s/bin/TestRelease/temp/TestAndroidStoreKeyTrueTrueaabTrueandroid_ks test.keystoreTrue/UnnamedProject.csproj]
                     /Users/runner/Library/Android/dotnet/packs/Microsoft.Android.Sdk.Darwin/30.0.100-ci.pr.gh5973.27/tools/Xamarin.Android.Common.targets(2526,3): error : java.lang.IllegalStateException :  Error retrieving device SDK version. Please try again.
```

I think it is unrelated.

**Review by dellis1972 — APPROVED** [review]

**Pull request merged**
