### PR TITLE
[Xamarin.Android.Build.Tasks] Add Run target

### PR DESCRIPTION
**Pull request by radekdoulik**
Add new `Run` target to start the app activity on the device/emulator

Add new `GetAndroidActivityName` task to retrieve the activity name
from the manifest file

Add new `Xamarin.Android.Application.targets` file for application
specific targets and import it conditionaly into the
`Xamarin.Android.Common.targets`.

### CODE REVIEW

**Comment by radekdoulik** [comment]
Didn't add test for it yet. I plan to use it in the https://github.com/xamarin/xamarin-android/issues/3740 implementation, which will run on CI and should serve as a good test for that.

**Comment by jonathanpeppers** [comment]
Is this the same as: https://github.com/xamarin/xamarin-android/pull/3801

You both happened to implement the same thing?

**Comment by dellis1972** [comment]
🤣

**Comment by radekdoulik** [comment]
the only failing build has the upload error => ready to go

(##[error]Artifact Test Results - MSBuild - macOS already exists for build 3235725.)

**Pull request merged**
