### PR TITLE
Bump binutils to 17.0.6-7.2.2

### PR DESCRIPTION
**Pull request by grendello**
Context: https://github.com/xamarin/xamarin-android-binutils/releases/tag/L_17.0.6-7.1.1
Context: https://github.com/xamarin/xamarin-android-binutils/releases/tag/L_17.0.6-7.1.2
Context: https://github.com/xamarin/xamarin-android-binutils/releases/tag/L_17.0.6-7.2.1
Context: https://github.com/xamarin/xamarin-android-binutils/releases/tag/L_17.0.6-7.2.2
Changes: https://github.com/xamarin/xamarin-android-binutils/compare/L_17.0.6-7.1.0...L_17.0.6-7.1.1
Changes: https://github.com/xamarin/xamarin-android-binutils/compare/L_17.0.6-7.1.1...L_17.0.6-7.1.2
Changes: https://github.com/xamarin/xamarin-android-binutils/compare/L_17.0.6-7.1.2...L_17.0.6-7.2.0
Changes: https://github.com/xamarin/xamarin-android-binutils/compare/L_17.0.6-7.2.0...L_17.0.6-7.2.1
Changes: https://github.com/xamarin/xamarin-android-binutils/compare/L_17.0.6-7.2.1...L_17.0.6-7.2.2

This release makes changes to how we build and run the `as.exe` wrapper, so that it can be verified by API Scan without any issues.  Otherwise it is identical to the previous release, using the same version of LLVM.

* [ci] Build and sign in a DevDiv pipeline by @pjcollins in https://github.com/xamarin/xamarin-android-binutils/pull/7
* [ci] Migrate to the 1ES template by @pjcollins in https://github.com/xamarin/xamarin-android-binutils/pull/8
* [ci] Improve binskim scan performance by @pjcollins in https://github.com/xamarin/xamarin-android-binutils/pull/11
* [ci] Improve triggers and support test signing by @pjcollins in https://github.com/xamarin/xamarin-android-binutils/pull/12
* [ci] Fix unsigned artifact uploading by @pjcollins in https://github.com/xamarin/xamarin-android-binutils/pull/13
* [ci] Disable automatic GitHub action trigger by @pjcollins in https://github.com/xamarin/xamarin-android-binutils/pull/16
* [ci] Build on performance build pools by @pjcollins in https://github.com/xamarin/xamarin-android-binutils/pull/15
* Build `as.exe` on windows by @grendello in https://github.com/xamarin/xamarin-android-binutils/pull/10
* [ci] Add API Scan job by @pjcollins in https://github.com/xamarin/xamarin-android-binutils/pull/9
*  Fix `as.exe` crash on Windows by @grendello in https://github.com/xamarin/xamarin-android-binutils/pull/20
* [ci] Use managed identity for API Scan by @pjcollins in https://github.com/xamarin/xamarin-android-binutils/pull/21
* Back to wide strings on Windows + magic encantations by @grendello in https://github.com/xamarin/xamarin-android-binutils/pull/22

### CODE REVIEW

**Comment by jonpryor** [comment]
The Linux unit tests are failing:

```
/mnt/vss/_work/2/s/bin/Release/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.101/tools/Xamarin.Android.Common.targets(2063,3): error XA3006: stderr | /mnt/vss/_work/2/s/bin/Release/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.101/tools/Linux/binutils/bin/llc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /mnt/vss/_work/2/s/bin/Release/dotnet/packs/Microsoft.Android.Sdk.Linux/34.0.101/tools/Linux/binutils/bin/../lib/../lib/libLLVMObject.so.17)
```

which is rather odd, as the #8806 PR didn't experience this, nor did the build for 0db28d3ff2f9852005eddbfc6ff8c9227f1a5474 in https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9347762&view=results (which had some failures, but non in **Linux Tests**).

Restarting the entire build, for sanity (?).

**Comment by jonpryor** [comment]
Rebuild at: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9402886&view=results

**Comment by grendello** [comment]
This is likely because we build on Ubuntu 22.04 (https://github.com/xamarin/xamarin-android-binutils/blob/main/build-tools/automation/azure-pipelines.yml#L60)
which has glibc 2.35, while Ubuntu 20.04 (the current LTS, till 2025 I think) has 2.31 - perhaps the tests ran on a bot with the older Ubuntu?

We probably should switch the binutils build bot to 20.04

**Review by jonathanpeppers — APPROVED** [review]

**Pull request merged**
