### PR TITLE
[xaprepare] Bump MDK version

### PR DESCRIPTION
**Pull request by radekdoulik**
Context: https://github.com/xamarin/xamarin-android/pull/4099
Roslyn bug: https://github.com/dotnet/roslyn/issues/38183
Corresponding Mono bug: https://github.com/mono/mono/issues/16541

To get Roslyn fix, for a bug we experience on ji-nrt branch, where
cil-strip is crashing.

    Moving F:\A\xamarin-v000004-1\_work\2\s\bin\TestRelease\temp\BuildAotApplication_arm64-v8a_Hybrid_True_True\obj\Release\android\assets\Java.Interop.dll to obj\Release\android\assets\non-stripped\Java.Interop.dll (TaskId:190)
      [cil-strip] obj\Release\android\assets\non-stripped\Java.Interop.dll (TaskId:190)
      [cil-strip stdout] Mono CIL Stripper (TaskId:190)
      [cil-strip stdout]  (TaskId:190)
      [cil-strip stdout] Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (TaskId:190)
      [cil-strip stdout] Parameter name: index (TaskId:190)
      [cil-strip stdout]    at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index) (TaskId:190)
      [cil-strip stdout]    at Mono.Cecil.GenericParameterCollection.get_Item(Int32 index) (TaskId:190)
      [cil-strip stdout]    at Mono.Cecil.ReflectionReader.GetTypeRefFromSig(SigType t, GenericContext context) (TaskId:190)
      [cil-strip stdout]    at Mono.Cecil.ReflectionReader.CreateTypeSpecFromSig(TypeSpec ts, Int32 index, GenericContext context) (TaskId:190)
      [cil-strip stdout]    at Mono.Cecil.Cil.CodeReader.ReadCilBody(MethodBody body, BinaryReader br) (TaskId:190)
      [cil-strip stdout]    at Mono.Cecil.Cil.CodeReader.VisitMethodBody(MethodBody body) (TaskId:190)
      [cil-strip stdout]    at Mono.Cecil.MethodDefinition.LoadBody() (TaskId:190)
      [cil-strip stdout]    at Mono.Cecil.ModuleDefinition.FullLoad() (TaskId:190)
      [cil-strip stdout]    at Mono.CilStripper.AssemblyStripper.Strip() (TaskId:190)
      [cil-strip stdout]    at Mono.CilStripper.AssemblyStripper.StripAssembly(AssemblyDefinition assembly, String file) (TaskId:190)
      [cil-strip stdout]    at Mono.CilStripper.Program.Main(String[] arguments) (TaskId:190)
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2732,4): error XA3001: Could not strip IL of assembly: obj\Release\android\assets\Java.Interop.dll [F:\A\xamarin-v000004-1\_work\2\s\bin\TestRelease\temp\BuildAotApplication_arm64-v8a_Hybrid_True_True\UnnamedProject.csproj]

### CODE REVIEW

**Comment by radekdoulik** [comment]
@akoeplinger Do you have more information about the Roslyn bug? If so, could you please add it to the PR description?

**Comment by jonpryor** [comment]
@akoeplinger, @radekdoulik: Apparently Roslyn doesn't like us? The [**Mac** > **Build** step is failing](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3375602&view=logs&jobId=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&t=b1c5529c-cb32-57d3-a3b4-ef8eebaa5024):

```
Project "/Users/builder/azdo/_work/3/s/xamarin-android/build-tools/xaprepare/xaprepare.sln" (1) is building "/Users/builder/azdo/_work/3/s/xamarin-android/build-tools/xaprepare/xaprepare/xaprepare.csproj" (2) on node 1 (default targets).
GenerateBindingRedirects:
  No suggested binding redirects from ResolveAssemblyReferences.
CoreCompile:
  /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Roslyn/csc.exe /noconfig /unsafe+ /nowarn:1701,1702 /nostdlib+ /platform:x86 /errorreport:prompt /warn:4 /doc:bin/Release/xaprepare.xml /highentropyva+ /reference:/Users/builder/.nuget/packages/kajabity.tools.java/0.2.6862.30334/lib/net40/Kajabity.Tools.Java.dll /reference:/Users/builder/.nuget/packages/xamarin.libzipsharp/1.0.6/lib/net45/libZipSharp.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.7.2-api/Microsoft.CSharp.dll /reference:/Users/builder/.nuget/packages/mono.options/5.3.0.1/lib/net4-client/Mono.Options.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.7.2-api/Mono.Posix.dll /reference:/Users/builder/.nuget/packages/mono.posix.netstandard/1.0.0/ref/net40/Mono.Posix.NETStandard.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.7.2-api/mscorlib.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.7.2-api/System.Core.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.7.2-api/System.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.7.2-api/System.IO.Compression.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.7.2-api/System.Net.Http.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.7.2-api/System.Xml.dll /reference:/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/4.7.2-api/System.Xml.Linq.dll /debug:portable /optimize+ /out:obj/x86/Release/xaprepare.exe /subsystemversion:6.00 /target:exe /utf8output /win32manifest:app.manifest /deterministic+ /langversion:7.1 /analyzerconfig:/Users/builder/azdo/_work/3/s/xamarin-android/.editorconfig obj/x86/Release//BuildInfo.Generated.cs obj/x86/Release//Properties.Defaults.cs Main.cs Application/Abi.cs Application/Abi.Bitness.cs Application/Abi.OS.cs Application/AbiType.cs Application/AndroidPlatform.cs Application/AndroidToolchainComponent.cs Application/AppObject.cs Application/BclFile.cs Application/BclFileTarget.cs Application/BclFileType.cs Application/BuildInfo.cs Application/Characters.cs Application/CompressionFormat.cs Application/Context.cs Application/DownloadStatus.cs Application/EssentialTools.cs Application/ExecutionMode.cs Application/Extensions.DictionaryOfProgramVersionParser.cs Application/Extensions.Runtime.cs Application/ExternalGitDependency.cs Application/GeneratedFile.cs Application/GeneratedMakeRulesFile.cs Application/GeneratedMonoAndroidProjitemsFile.cs Application/GeneratedProfileAssembliesProjitemsFile.cs Application/GeneratedPlaceholdersFile.cs Application/KnownConditions.cs Application/KnownProperties.cs Application/LlvmRuntime.cs Application/Log.cs Application/LoggingVerbosity.cs Application/MonoCrossRuntime.cs Application/MonoHostRuntime.cs Application/MonoJitRuntime.cs Application/MonoRuntime.cs Application/MonoRuntimesHelpers.cs Application/MonoUtilityFile.cs Application/ProcessRunner.cs Application/ProcessStandardStreamWrapper.cs Application/Program.cs Application/ProgramVersionParser.cs Application/Properties.cs Application/PropertiesChangedEventArgs.cs Application/RegexProgramVersionParser.cs Application/RuleGeneratorDelegate.cs Application/Runtime.cs Application/RuntimeFile.cs Application/RuntimeFileType.cs Application/Scenario.cs Application/ScenarioNoStandardEndSteps.cs Application/ScenarioAttribute.cs Application/SimpleActionStep.cs Application/SizeFormatter.cs Application/Step.cs Application/StepWithDownloadProgress.cs Application/TestAssembly.cs Application/TestAssemblyType.cs Application/ThirdPartyLicenseType.cs Application/ThirdPartyNotice.cs Application/ThirdPartyNoticeGroup.cs Application/ThumbTwiddler.cs Application/TPNAttribute.cs Application/Utilities.cs Application/VersionFetchers.cs ConfigAndData/AbiNames.cs ConfigAndData/BuildAndroidPlatforms.cs ConfigAndData/CommonLicenses.cs ConfigAndData/Configurables.cs ConfigAndData/Dependencies/AndroidToolchain.cs ConfigAndData/Runtimes.cs ConfigAndData/Runtimes.Code.cs OperatingSystems/OS.cs Properties/AssemblyInfo.cs Scenarios/Scenario_AndroidToolchain.cs Scenarios/Scenario_PrepareExternal.cs Scenarios/Scenario_PrepareExternalGitDependencies.cs Scenarios/Scenario_PrepareImageDependencies.cs Scenarios/Scenario_Required.cs Scenarios/Scenario_Standard.cs Scenarios/Scenario_ThirdPartyNotices.cs Steps/Step_Android_SDK_NDK.cs Steps/Step_BuildMingwDependencies.cs Steps/Step_DownloadMonoArchive.cs Steps/Step_DownloadNuGet.cs Steps/Step_GenerateFiles.cs Steps/Step_Get_Windows_Binutils.cs Steps/Step_InstallCorrettoOpenJDK.cs Steps/Step_InstallMonoRuntimes.cs Steps/Step_PrepareExternal.cs Steps/Step_PrepareExternalGitDependencies.cs Steps/Step_PrepareExternalJavaInterop.cs Steps/Step_PrepareImageDependencies.cs Steps/Step_PrepareLocal.cs Steps/Step_PrepareMSBuild.cs Steps/Step_PrepareProps.cs Steps/Step_ShowEnabledRuntimes.cs Steps/Step_ThirdPartyNotices.cs ThirdPartyNotices/aapt2.cs ThirdPartyNotices/bundletool.cs ThirdPartyNotices/Java.Interop.cs ThirdPartyNotices/mono.cs ThirdPartyNotices/opentk.cs ThirdPartyNotices/proguard.cs ThirdPartyNotices/r8.cs ThirdPartyNotices/sqlite.cs ThirdPartyNotices/Xamarin.Android.Build.Tasks.cs ThirdPartyNotices/Xamarin.Android.NunitLite.cs ThirdPartyNotices/Xamarin.Android.Tools.Aidl.cs ThirdPartyNotices/Xamarin.Android.Tools.JavadocImporter.cs ThirdPartyNotices/xaprepare.cs ToolRunners/CMakeRunner.cs ToolRunners/CMakeRunner.OutputSink.cs ToolRunners/GitRunner.cs ToolRunners/GitRunner.BlamePorcelainEntry.cs ToolRunners/GitRunner.OutputSink.cs ToolRunners/MSBuildRunner.cs ToolRunners/MSBuildRunner.OutputSink.cs ToolRunners/NinjaRunner.cs ToolRunners/NinjaRunner.OutputSink.cs ToolRunners/NuGetRunner.cs ToolRunners/NuGetRunner.OutputSink.cs ToolRunners/SevenZipRunner.cs ToolRunners/SevenZipRunner.OutputSink.cs ToolRunners/SnRunner.cs ToolRunners/SnRunner.OutputSink.cs ToolRunners/TarRunner.cs ToolRunners/TarRunner.OutputSink.cs ToolRunners/ToolRunner.cs ToolRunners/ToolRunner.OutputSink.cs Application/RefreshableComponent.cs ThirdPartyNotices/LibZipSharp.cs ThirdPartyNotices/libzip.cs Application/EssentialTools.Unix.cs Application/Log.Unix.cs Application/Utilities.Unix.cs ConfigAndData/Configurables.Unix.cs ConfigAndData/Runtimes.Unix.cs OperatingSystems/Unix.cs Scenarios/Scenario_Standard.Unix.cs Scenarios/Scenario_UpdateMono.Unix.cs Steps/Step_BuildMonoRuntimes.Unix.cs Steps/Step_GenerateFiles.Unix.cs Steps/Step_PrepareExternal.Unix.cs Steps/Step_PrepareExternalJavaInterop.Unix.cs Steps/Step_PrepareImageDependencies.Unix.cs ToolRunners/MakeRunner.Unix.cs ToolRunners/MakeRunner.OutputSink.Unix.cs Application/Context.MacOS.cs Application/EssentialTools.MacOS.cs Application/HomebrewProgram.MacOS.cs Application/LlvmRuntime.MacOS.cs Application/MonoPkgProgram.MacOS.cs Application/PkgProgram.MacOS.cs Application/GeneratedMakeRulesFile.MacOS.cs ConfigAndData/Configurables.MacOS.cs ConfigAndData/Dependencies/AndroidToolchain.MacOS.cs ConfigAndData/Dependencies/MacOS.cs OperatingSystems/MacOS.cs Scenarios/Scenario_Standard.MacOS.cs Steps/Step_ChangeLibMonoSgenDylibID.MacOS.cs Steps/Step_InstallCorrettoOpenJDK.MacOS.cs Steps/Step_PrepareImageDependencies.MacOS.cs ToolRunners/BrewRunner.MacOS.cs ToolRunners/MakeRunner.MacOS.cs ToolRunners/PkgutilRunner.MacOS.cs "/var/folders/44/mpr_nlrs6bl2ggyzmx892rlw0000gn/T/.NETFramework,Version=v4.7.2.AssemblyAttributes.cs"
  Using shared compilation with compiler from directory: /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Roslyn
/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Roslyn/Microsoft.CSharp.Core.targets(59,5): error : Roslyn compiler server reports different hash version than build task. [/Users/builder/azdo/_work/3/s/xamarin-android/build-tools/xaprepare/xaprepare/xaprepare.csproj]
```

Key part:

```
error : Roslyn compiler server reports different hash version than build task.
```

Eep?

**Comment by jonpryor** [comment]
Context: https://github.com/xamarin/xamarin-android/pull/4099

**Comment by akoeplinger** [comment]
@radekdoulik the roslyn bug is https://github.com/dotnet/roslyn/issues/38183 (corresponding mono issue: https://github.com/mono/mono/issues/16541)

The different hash version for roslyn in the msbuild task is quite interesting. @radical any ideas?

**Comment by radical** [comment]
I was able to reproduce this locally with msbuild and a non-xa project. I think it should be the same issue here.

- The shared compiler is started from a particular mono (like 6.8.0.43 here) - `/Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Roslyn/VBCSCompiler.exe`
- then a newer version of mono is installed (6.8.0.95 here), which has a *different* version of roslyn
- A subsequent invocation of msbuild tries to connect to the same compiler server (the path hasn't changed), and that fails because these two have different versions of roslyn

Maybe during installation, we need to kill all such compiler server processes from the same path as what we are installing to.

**Comment by akoeplinger** [comment]
Hm ok. That sounds like something that's not new and would've happened in the past too so it's probably not something we need to fix immediately in 6.8.x.

@jonpryor Where's 6.8.0.43 coming from? I guess one way to fix this is to pass `/p:UseSharedCompilation=false /nodeReuse:false` to the msbuild call that builds xaprepare so we don't get any of the servers.

**Comment by radical** [comment]
@akoeplinger true. I will poke around this more and try to confirm it.

**Comment by radekdoulik** [comment]
Is there a way to stop the Roslyn server (shared compiler)? Maybe we can do that before staring of xaprepare compilation? Then we might not need to disable the shared compilation?

**Comment by radical** [comment]
This seems to work:
`$ mono /Library/Frameworks/Mono.framework/Versions/6.8.0/lib/mono/msbuild/Current/bin/Roslyn/VBCSCompiler.exe -shutdown`

**Comment by akoeplinger** [comment]
@radekdoulik you can do what Ankit mentioned but I'd recommend just disabling the shared compilation for xaprepare. It's a single project so you won't get any benefit from it anyway.

**Comment by jonpryor** [comment]
@radical suggested:

> Maybe during mono's installation, we need to kill all such compiler server processes from the same path as what we are installing to.

@akoeplinger: is there a way to do that, to kill the compiler server processes before/after updating mono?  `killall mono mono-sgen`?

It seems somewhat "looney" that we'd potentially have to use `/p:UseSharedCompilation=false /nodeReuse:false` *everywhere* in order to safely use `msbuild`, which may not be easy to do, e.g. on unit test machines on which we may also update mono.

**Comment by jonpryor** [comment]
Commit 05aad5865eb1228e3255fb80cc9a07d5cafe0008 likely won't work reliably, as we're using on-prem hardware, so one of the key assumptions -- that there won't be a Roslyn build server running before the build -- *may* be wrong, if two builds hit the same box within ~10 minutes (the timeout interval of the Roslyn build server).

Other ideas raised:

 1. Export `MSBUILDNODEHANDSHAKESALT=$(mono --version=number)`.  The Roslyn build server (sanely) uses the path to the Roslyn `.exe` as a path to check for validity.  The problem is that the Mono.framework directory install uses a "3-tuple" version scheme, not a 4-tuple, so when we update Mono while staying on the same major.minor.build --  as is done in this PR -- then the validity check is incomplete.  Setting `MSBUILDNODEHANDSHAKESALT` may "fix" the check, allowing the full 4-tuple version to be used.

 2. Add a `killall mono` & `killall mono-sgen` after `xaprepare` runs, to ensure that no mono processes are running after mono is updated.

(2) may be reasonably sane, but might be slightly more difficult to implement.

**Comment by jonpryor** [comment]
...and in fact, 05aad5865eb1228e3255fb80cc9a07d5cafe0008 *did* fail to build, with the same error...

**Comment by radical** [comment]
> ...and in fact, [05aad58](https://github.com/xamarin/xamarin-android/commit/05aad5865eb1228e3255fb80cc9a07d5cafe0008) _did_ fail to build, with the same error...

Can we confirm if the property `$(UseSharedCompilation)==false` was indeed set for that build?

> Export MSBUILDNODEHANDSHAKESALT=$(mono --version=number). 

I don't think this will work. This seems to be a specifically for msbuild nodes, thus parallel builds. Roslyn doesn't seem to have a similar env var (https://github.com/dotnet/roslyn/blob/master/src/Compilers/Shared/BuildServerConnection.cs#L519). If we can add that to roslyn, then this should work.

**Comment by rainersigwald** [comment]
We recently discovered that `MSBUILDNODEHANDSHAKESALT` doesn't actually work as designed: microsoft/msbuild#4961, so I think the "kill mono" approach might be most reliable here, unfortunately.

**Comment by jonpryor** [comment]
@grendello, @radekdoulik: could one of you please update this PR to "kill all `mono` processes" after mono is updated (IFF mono is updated)?  As is, mono updates are potentially unstable, as any `mono` processes from *before* the mono reinstall/update is "suspect" and won't work properly afterward.

**Comment by radical** [comment]
fyi, opened PR for bockbuild - https://github.com/mono/mono/pull/18488

**Comment by jonpryor** [comment]
@radical: It's nice that *mono* will kill VBCSCompiler...on *master*.  The fix isn't on mono/2019-10, and thus won't help with *this* PR.

I think we'll need to *abandon* this PR, as it's not really viable at the moment, and hope that the mono/2019-12 bump PR #3981 will similarly get us an updated Roslyn toolchain, while avoiding the VBCSCompiler breakage we're currently experiencing (as the minor version changes in #3981).

Alternatively, we "duplicate" the `VBCSCompiler.exe -shutdown` logic in mono/mono@cc6e927d10173ba7d90805348e8350e6dd80e142 into `xaprepare`...

**Comment by radekdoulik** [comment]
This will be soon not needed, when we integrate the next mono branch.

**Pull request closed without merging**
