### PR TITLE
[Xamarin.Android.Build.Tasks] DesignTimeBuild should use live build cache's if they exist.

### LINKED ISSUE #1501: [Designer] Broken MSBuild logic
The following two commits:
 - https://github.com/xamarin/xamarin-android/commit/e55d6557f6a273a21be3cf72893f12a86f1ec359
 - https://github.com/xamarin/xamarin-android/commit/e824170632e0b9115ee65d9dc07c41fa3b8907b6

Broke the designer target `GetExtraLibraryLocationsForDesigner` because the first redefines the path of the cache file `_AndroidResourcePathsCache` and the second prevents that path from ever being created.

> VS bug [#594873](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/594873)

### PR DESCRIPTION
**Pull request by dellis1972**
Fixes #1501 

If we have valid live cache files for the additional resources, the design time build should make use of them. However it should not create them since it would cause build problems for the live builds.

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
Trying a few more times, and I think that 594126 is only happening randomly.

Having trouble repro-ing with the fix removed, so hard to know if this fixes 594126 or not.

**Comment by dellis1972** [comment]
I think this is good to go.

**Comment by jonathanpeppers** [comment]
👍

**Comment by garuma** [comment]
Tested on my end by using an older monodroid build and only changing the lines this PR changed (i.e. not accounting for the most recent MSBuild changes done to xamarin-android in between) and it does fix the issue.

**Pull request merged**
