### PR TITLE
Default InvariantGlobalization in Xamarin Android

### PR DESCRIPTION
**Pull request by eerhardt**
This allows for unnecessary code to be trimmed by default in an app. See https://github.com/dotnet/runtime/pull/47999.

### CODE REVIEW

**Review by jonathanpeppers — APPROVED** [review]

**Comment by jonpryor** [comment]
@eerhardt : why isn't `$(InvariantGlobalization)`=False the default in the first place?  What are the ramifications of this change?

**Comment by eerhardt** [comment]
> why isn't $(InvariantGlobalization)=False the default in the first place? 

The behavior of `$(InvariantGlobalization)=False` is the default behavior of the runtime when `$(InvariantGlobalization)` isn't explicitly set. But we don't explicitly set this in the core SDK because this would not allow an end user set the environment variable to control this behavior, since the `runtimeconfig.json` value overrides the environment variable. In the core SDK, we only want the `runtimeconfig.json` setting set when the developer explicitly sets it.

> What are the ramifications of this change?

For app models that are trimmed (Blazor WASM, Xamarin), this setting allows the code that is only used when `$(InvariantGlobalization)=true` to be trimmed from the app when it isn't being used. This isn't a substantial amount of code, but for Blazor WASM, it was 10 KB uncompressed and 3 KB .br compressed.

**Review by radekdoulik — APPROVED** [review]

**Comment by radekdoulik** [comment]
Added `do-not-merge` to postpone until I measure the difference for the description message.

**Comment by radekdoulik** [comment]
Ah, but there will be no difference yet. We should bump net6 version too.

**Comment by radekdoulik** [comment]
I tried to measure it with `6.0.0-preview.1.21109.8`, but that didn't contain the runtime change yet. So let's merge it without that information.

**Pull request merged**
