### PR TITLE
[Tasks] Add aot to the list of valid profilers

### PR DESCRIPTION
**Pull request by radekdoulik**
With this change it is possible to build an apk containing `aot`
profiler module (libmono-profiler-aot.so shared library) and profile
the app with it. It can enabled by setting `mono.debug.profile`
property to `aot` on the device or emulator.

Note that the `aot` profiler saves the data during the mono
runtime shutdown. So one way (only way?) to get the data is to call
`System.Environment.Exit` to end the XA app. Currently  there is
an issue with Java.Interop, where during the shutdown we get
an unhandled exception and thus the shutdown process doesn't
finish, which means the profile output is not written to the file.
Hopefully I can fix that soon.

### CODE REVIEW

**Comment by jonpryor** [comment]
Should this be part of PR #1254, as they both deal with AOT logging?

**Comment by jonpryor** [comment]
> Note that there is an issue with Java.Interop, where the app shutdown is broken right now.

This seems a bit odd, in that... how are you doing "app shutdown" in the first place? Normally apps are killed (`SIGTERM`?) by Android; there is no "clean app exit" process that I'm aware of.

I don't understand what Java.Interop has to do with this.

**Comment by radekdoulik** [comment]
This PR makes it possible to use `aot` profiler. The other one is for convenience, to have right extension when `aot` profiler is used. So I kept them separate.

**Comment by radekdoulik** [comment]
The shutdown I noted is not the usual Android shutdown. I should have describe it better I guess.

The aot profiler outputs the data to the file during the runtime shutdown, so currently the way to get that data is to call `System.Environment.Exit`. Current Java.Interop doesn't handle that nicely and fails with unhandled exception, see below. I am now able to get the data with "hacked" Java.Interop and I would like to try fix Java.Interop to handle that case better.

Regarding the aot profiler usage in XA by our users, I think we should add possibility to ask the profiler to stop at request. I need to consult that with mono team. And then we introduce another [XS command](https://github.com/xamarin/xamarin-android/blob/master/src/monodroid/jni/monodroid-glue.c#L3490-L3561) `stop profile` to stop the profiler. Plus maybe a way to do it from command line too, I am not sure whether the XS commands could be used outside of IDE?

The unhandled exception I see during the shutdown:
```
[ERROR] FATAL UNHANDLED EXCEPTION: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'The ThreadLocal object has been disposed.'.
  at System.Threading.ThreadLocal`1[T].GetValueSlow () [0x00014] in <ad0ee2441a95493896dd541312e44f97>:0 
  at System.Threading.ThreadLocal`1[T].get_Value () [0x0003e] in <ad0ee2441a95493896dd541312e44f97>:0 
  at Java.Interop.JniEnvironment.get_CurrentInfo () [0x00001] in <28d24e54f60b4e39b474e934d28d5937>:0 
  at Java.Interop.JniEnvironment.get_Runtime () [0x00001] in <28d24e54f60b4e39b474e934d28d5937>:0 
  at Java.Interop.JniObjectReference.Dispose (Java.Interop.JniObjectReference& reference) [0x00030] in <28d24e54f60b4e39b474e934d28d5937>:0 
  at Java.Interop.JniRuntime.Dispose (System.Boolean disposing) [0x0003a] in <28d24e54f60b4e39b474e934d28d5937>:0 
  at Java.Interop.JniRuntime.Finalize () [0x00002] in <28d24e54f60b4e39b474e934d28d5937>:0 
```

**Comment by radekdoulik** [comment]
Updated the PR description with better description of how the aot profiler writes data and about the runtime shutdown.

**Pull request merged**
