### PR TITLE
[Xamarin.Android.Tools.Aidl] fix classloader retrieval for List and Map (#1597)

### PR DESCRIPTION
**Pull request by ssimek**
Fixes incorrect code generation from AIDL for cases which require the class loader (ReadArrayList/ReadHashMap)

The current code could not possibly work, as the required parameters were simply not provided to the called methods causing build failures. The one case which provided null instead of class loader would likely cause runtime failures under some circumstances.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/xamarin/xamarin-android?pullRequest=4963) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/xamarin-android?pullRequest=4963) before we can accept your contribution.<br/><br/>:x: ssimek [sign now](https://cla.dotnetfoundation.org/xamarin/xamarin-android?pullRequest=4963)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/xamarin-android?pullRequest=4963) it.</sub>

**Comment by jonpryor** [comment]
I believe this would fix: https://github.com/xamarin/xamarin-android/issues/1597

**Comment by jonpryor** [comment]
@ssimek wrote:

> The one case which provided null instead of class loader would likely cause runtime failures under some circumstances.

Can you please elaborate?  The Android documentation certainly states that `null` is a valid value for the parameter, e.g. both [`Parcel.readArrayList(ClassLoader)`](https://developer.android.com/reference/android/os/Parcel#readArrayList(java.lang.ClassLoader)) and [`Parcel.readHashMap(ClassLoader)`](https://developer.android.com/reference/android/os/Parcel#readHashMap(java.lang.ClassLoader)) state:

> `loader`: `ClassLoader`: This value may be `null`.

**Comment by jonpryor** [comment]
@ssimek: please also see/try: PR #5003.

**Comment by ssimek** [comment]
Hi @jonpryor,

my fix is based the fix on [original AIDL tool code](https://android.googlesource.com/platform/system/tools/aidl/+/refs/heads/master/aidl_to_java.cpp) and I honestly did not investigate much into why the value is required/should be provided. However, at a glance, I'd say that the call with a `null` classloader would somehow fail if there were another `Parcelable` inside the List/Map, since

> The given class loader will be used to load any enclosed Parcelables.

It is not clear what happens when no class loader is provided. I assume it is safer to do the same as the original AIDL tool instead of hoping that providing `null`will work correctly.

**Comment by jonpryor** [comment]
Superseded by PR#5003.

The `ClassLoader` parameter support isn't part of PR #5003, and is being tracked at: https://github.com/xamarin/xamarin-android/issues/5012

**Pull request closed without merging**
