### PR TITLE
[ci] Stop building monodroid in builds from forks

### PR DESCRIPTION
**Pull request by pjcollins**
Removes all usage of provisionator and monodroid build and test steps
when building a PR from a fork.

### CODE REVIEW

**Comment by pjcollins** [comment]
Tagging everyone for review for awareness, once this lands any xamarin/monodroid related changes will need to come from xamarin-android branches.

**Review by jpobst — APPROVED** [review]
The changes look good.

One concern is: are we worried about accidentally merging a PR that was from a fork and thus has not had the full battery of checks run?

If we are, we could write a step that fails if running from a fork, so we would at least always see an error that we could choose to ignore if we want.

I will leave this decision up to others, as I do not use forks.  😁

**Review by grendello — APPROVED** [review]

**Review by moljac — APPROVED** [review]
LGTM

**Comment by dellis1972** [comment]
This looks good. 

What is the process for dealing with Third party contributions? they won't have the permissions to push to the main repo, so I guess we will need to merge PR's and then fix issues with the full build if they appear?

**Review by dellis1972 — APPROVED** [review]

**Review by jonathanpeppers — APPROVED** [review]

**Comment by pjcollins** [comment]
> This looks good.
> 
> What is the process for dealing with Third party contributions? they won't have the permissions to push to the main repo, so I guess we will need to merge PR's and then fix issues with the full build if they appear?

Yeah this sounds about right, we will need to monitor our regular CI results a bit more closely to make sure it stays healthy after this.

**Comment by grendello** [comment]
> > This looks good.
> > What is the process for dealing with Third party contributions? they won't have the permissions to push to the main repo, so I guess we will need to merge PR's and then fix issues with the full build if they appear?
> 
> Yeah this sounds about right, we will need to monitor our regular CI results a bit more closely to make sure it stays healthy after this.

Should we perhaps change the default branch to `dev` and make `main` "ready for release"? 3rd party PRs would be merged against `dev` and, if they don't break the branch, cherry-picked to `main`.  It's more work, but at least `main` wouldn't be potentially broken for anyone pulling changes in the morning should a PR break something.

**Comment by pjcollins** [comment]
The idea of adding an intermediate branch such as `dev` seems interesting, though I'm not sure the overhead of keeping the two branches in sync and merging back and forth is doing to be worth it? I think in the vast vast majority of cases we only ship from release branches (such as [release/8.0.1xx-rc2](https://github.com/xamarin/xamarin-android/tree/release/8.0.1xx-rc2)), so we have a bit of a "buffer" in place already.

**Comment by grendello** [comment]
@pjcollins I'm more worried about timezones here - if someone in the US or Europe or anywhere else merges a broken 3rd party PR, then people waking up in the morning, while the committer isn't available, will be faced with a broken branch after they pull changes at the start of their day.  We have (unfortunately) so few 3rd party PRs that the overhead shouldn't be too much.

**Comment by pjcollins** [comment]
This PR still ran `6,676` tests compared to the `6,754` tests in a recent build from main, I am hoping that the scenario where a forked build causes a real breakage is going to be extremely small. We can look at workflow changes in the future if we do start running into issues.

**Pull request merged**
