### PR TITLE
bintray/jcenter/jfrog removal/replacements

### PR DESCRIPTION
**Pull request by moljac**
## bintray/jcenter/jfrog removal/replacements

Context: https://blog.gradle.org/jcenter-shutdown

Context: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

JCenter is shutting down.  It is no longer browsable as of May 1, and artifacts hosted on JCenter repository *will be read-only accessible* indefinitely.

Stop using JCenter, and instead use [Maven Central][0].

[0]: https://search.maven.org/

NOTE: unable to find url replacements:

* jetbrains runtime `jbrsdk`
* `twitter-core`
* 
```
./build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs:35:			// https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbrsdk-8u202-linux-x64-b1483.37.tar.gz
./build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs:36:			// https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbrsdk-8u202-osx-x64-b1483.37.tar.gz
./build-tools/xaprepare/xaprepare/ConfigAndData/Configurables.cs:37:			// https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbrsdk-8u202-windows-x64-b1483.37.tar.gz


./src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/BuildTest.cs:3277:				WebContent = "https://dl.bintray.com/twitteross/twitterkit/com/twitter/sdk/android/twitter-core/3.3.0/twitter-core-3.3.0.aar",
```

Related:

https://github.com/xamarin/java.interop/commit/9444570be4c272a11ee7855d6440c8f033faabac

### CODE REVIEW

**Review by jonathanpeppers — APPROVED** [review]
Tested a couple of these URLs and they seem to work.

This looks good if the build ends up green. 👍

**Comment by moljac** [comment]
thanks

What about `jbrsdk`? Just wait and see when and where it will be moved? 

https://blog.gradle.org/jcenter-shutdown

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

JCenter repo will be read-only forever. Seems that downloads will be possible and even after 2022-02-01

**Comment by jonathanpeppers** [comment]
Honestly, I think it would be fine to wait and only fix URLs that break. Most of these are just unit tests.

**Comment by jonpryor** [comment]
For commit message purposes, this could be repurposed: https://github.com/xamarin/java.interop/commit/9444570be4c272a11ee7855d6440c8f033faabac

**Review by grendello — APPROVED** [review]

**Pull request closed without merging**
