### PR TITLE
Bump to xamarin/monodroid@d23d086

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Changes: https://github.com/xamarin/monodroid/compare/7f40abfa...d23d0864

* Fixes for netstandard projects

* Improvement to deploy times when no device attached

### CODE REVIEW

**Comment by dellis1972** [comment]
Only one test failure , it doesn't look related.

**Comment by jonpryor** [comment]
Windows had a "test failure":

```
  1) Failed : Xamarin.Android.Build.Tests.ResolveSdksTaskTests.ResolveSdkTiming
    Task should not take more than 2 seconds to run.
    Expected: less than or equal to 00:00:02
    But was:  00:00:02.6554166
     at Xamarin.Android.Build.Tests.ResolveSdksTaskTests.ResolveSdkTiming() in E:\A\_work\5\s\src\Xamarin.Android.Build.Tasks\Tests\Xamarin.Android.Build.Tests\Tasks\ResolveSdksTaskTests.cs:line 250

```

**Comment by jonpryor** [comment]
Fast Deploy Assemblies also failed weirdly: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3223642&view=ms.vss-test-web.build-test-results-tab&runId=9647116&resultId=100001&paneView=attachments

**Comment by dellis1972** [comment]
This FastDev failures look very weird 
```
  D:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3639,5): error MSB3086: Task could not find "al.exe" using the SdkToolsPath ""
```

**Comment by jonathanpeppers** [comment]
When I was looking at the QA tests last week, this one pops up occasionally:
```
error MSB3086: Task could not find "al.exe" using the SdkToolsPath ""
```
There is a UWP project in one of the test SLNs, and some of the build machines seems to be missing part of the UWP VS workload.

I'm going to restart these and see what happens.

**Comment by jonathanpeppers** [comment]
There is another failure:
```
System.IO.DirectoryNotFoundException : Could not find a part of the path "/Users/xamarinqa/azdo/_work/1/s/xamarin-forms-samples/UsingResxLocalization/Android/UsingResxLocalization.Android.csproj".
```
This is unrelated/happening on master, and should hopefully be fixed by: https://github.com/xamarin/QualityAssurance/pull/3440

**Pull request merged**
