### PR TITLE
[android-tools] Bump android-O to use r02 (beta)

### PR DESCRIPTION
**Pull request by dellis1972**

### CODE REVIEW

**Comment by dellis1972** [comment]
ok, the build failure is down to the ConsoleLogger negative index issue that we get on xbuild sometimes

**Comment by dellis1972** [comment]
build

**Comment by atsushieno** [comment]
I don't see the point of bumping ONLY reference to the preview API package. Our API metadata fixup, while it MAY not break "builds", can bring inconsistency with the API, and upgrading the API packaeg *without reviewing* the actual API changes is rather harmful because it makes API review more or less harder, for nothing.

**Comment by jonpryor** [comment]
This is superseded by PR #625.

**Pull request closed without merging**
