### PR TITLE
Update mono to 2017-02 "monthly master" branch

### PR DESCRIPTION
**Pull request by xmcclure**
To be merged after Wrench testing is complete and after the next xamarin-android branch.

This is an adjustment of PR #430 . Some discussion is archived there.

### CODE REVIEW

**Comment by akoeplinger** [comment]
build

**Comment by xmcclure** [comment]
build

**Comment by xmcclure** [comment]
build

**Comment by xmcclure** [comment]
build

**Comment by xmcclure** [comment]
Rebased on top of c76fc6439e9

**Comment by xmcclure** [comment]
build

**Comment by xmcclure** [comment]
build

**Comment by xmcclure** [comment]
build

**Comment by xmcclure** [comment]
build

**Comment by xmcclure** [comment]
Rebased to pick up what is hopefully a fix for the failing `Xamarin.Android.Build.Tests.PackagingTest.CheckBuildIdIsUnique` test. Also removed the ManifestDocumentElement.cs fix (it is now in base xamarin.android) and the -v on monosymbolicate (it didn't help).

**Comment by borgdylan** [comment]
Is this PR supposed to bring in support for ppdb debugging, or is that still on the waiting list?

**Comment by xmcclure** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by directhex** [comment]
build

**Comment by xmcclure** [comment]
After discussion with @jonpryor and all checks passing, merging

**Pull request merged**
