### PR TITLE
[build] enable the dotnet7 feed

### PR DESCRIPTION
**Pull request by jonathanpeppers**
We should now have access to use the `dnceng-dotnet7` connection in DevDiv's AzDO instance.

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
Manually started a build on this branch here:

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6140153&view=results

**Comment by jonathanpeppers** [comment]
Newer build: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6144693&view=results

**Comment by jonathanpeppers** [comment]
It appears we don't need the `NuGetAuthenticate` task, this build worked:

https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6140153&view=logs&j=0bb7211e-5977-566f-6fc8-aeeb1a69a540&t=fee18160-fa48-517c-6ad3-54f1db51f1ca&l=24

**Review by pjcollins — APPROVED** [review]
Do we want to make any package version changes before we start pushing? I assume we are going to mostly keep the same preview schema, but should we change [this](https://github.com/xamarin/xamarin-android/blob/main/Directory.Build.props#L35) to 33.0.0? I think we had discussed that we no longer need the .NET SDK band in the version?

**Comment by jonathanpeppers** [comment]
Yeah, let me change that before I merge.

**Review by pjcollins — APPROVED** [review]

**Pull request merged**
