### PR TITLE
Bump to xamarin/monodroid/main@f4240bc3

### PR DESCRIPTION
**Pull request by jonpryor**
Changes: http://github.com/xamarin/monodroid/compare/e451ea986b27cdfb965df07c1f2ea74fa14f33c2...f4240bc3c3d331db47c9ee944b4388e0e9af4076

  * xamarin/monodroid@f4240bc3c: Bump to xamarin/android-sdk-installer@68939f22 (#1247)
  * xamarin/monodroid@f84615dae: Bump to xamarin/android-sdk-installer/main@69fa0dca (#1245)
  * xamarin/monodroid@8589f37fa: [ci] Import variables.yaml from xamarin-android (#1246)

### CODE REVIEW

**Review by jonathanpeppers — APPROVED** [review]

**Comment by jonpryor** [comment]
`InstallAndroidDependenciesTest` is still failing. 🙃

[Current reason](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6073613&view=ms.vss-test-web.build-test-results-tab&runId=39018808&resultId=100035&paneView=attachments):

```
…/Xamarin.Android.Legacy.targets(266,5): error XA5300: "No Android platforms installed at '{0}'. Please install an SDK Platform with the `{1}{2}tools{2}{3}` program."
…/Xamarin.Android.Legacy.targets(266,5): error XA5300: System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
…/Xamarin.Android.Legacy.targets(266,5): error XA5300:   at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args)
…/Xamarin.Android.Legacy.targets(266,5): error XA5300:   at System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args)
…/Xamarin.Android.Legacy.targets(266,5): error XA5300:   at System.String.Format (System.IFormatProvider provider, System.String format, System.Object[] args)
…/Xamarin.Android.Legacy.targets(266,5): error XA5300:   at Microsoft.Build.Framework.LazyFormattedBuildEventArgs.FormatString (System.Globalization.CultureInfo culture, System.String unformatted, System.Object[] args)
```

**Comment by jonpryor** [comment]
Aside: my "favorite corner case" in C#: `(string format, params object[] args)` methods.  Consider:

```csharp
using System;
using System.Collections.Generic;

class App {
    public static void Write(string format, params object[] args) =>
        System.Console.WriteLine (format, args);

    static void Main ()
    {
        var d = new Dictionary<string, string> () {
            ["a"] = "1",
            ["b"] = "{bee}",
        };
        foreach (var e in d) {
            Write ($" {{ \"{e.Key}\" = \"{e.Value}\" }}");
        }
    }
}
```

Does It Die™? 😅

**Comment by jonpryor** [comment]
[Does It Die™](https://github.com/xamarin/xamarin-android/pull/6963#issuecomment-1110295938)?  Of course it dies:

```
System.FormatException: Input string was not in a correct format.
  at System.Text.StringBuilder.AppendFormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args)
  at System.String.FormatHelper (System.IFormatProvider provider, System.String format, System.ParamsArray args)
  at System.String.Format (System.IFormatProvider provider, System.String format, System.Object[] args) 
  at System.IO.TextWriter.WriteLine (System.String format, System.Object[] arg) 
```

*Why* does it die?  Because after string interpolation, we have:

```csharp
string message = " { \"b\" = \"{bee}\" }";
Console.WriteLine(format: message, args: new object[0]);
```

`message` is *not* a format string.  It's a "complete" string (for lack of a better term), the *result* of calling `string.Format()`, *not the input **to*** `string.Format()`.

This is likewise bad, for the same reason:

```csharp
string.Format(string.Format("{0}={1}", "a", "{bee}"));
```

You shouldn't use the result of `string.Format()` (or C# `$"format strings"`) as the format parameter *to* `string.Format()`.

**Comment by jonpryor** [comment]
Back to [the error](https://github.com/xamarin/xamarin-android/pull/6963#issuecomment-1110292409), the "offending" code is:

https://github.com/xamarin/xamarin-android/blob/6dc426f1788260a7fbc330f5b708d0fac0526f06/src/Xamarin.Android.Build.Tasks/Tasks/Legacy/ResolveAndroidTooling.cs#L157-L158

Necessary context: the value of `Properties.Resources.XA5300_Android_Platforms`:
https://github.com/xamarin/xamarin-android/blob/6dc426f1788260a7fbc330f5b708d0fac0526f06/src/Xamarin.Android.Build.Tasks/Properties/Resources.resx#L839-L846

`XA5300_Android_Platforms` is a format string for `string.Format()`, and expects 4 parameters.  It only gets 3.  Thus, the exception.

The only reason we haven't seen this before is *normally* `ResolveAndroidTooling.GetMaxInstalledApiLevel()` finds an installed API level.  In this unit test run, it didn't; `maxApiLevel` is < 0.

I can only assume this is the case because *no* API levels were installed?

**Comment by jonpryor** [comment]
For more context, the unit test itself: https://github.com/xamarin/xamarin-android/blob/6dc426f1788260a7fbc330f5b708d0fac0526f06/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs#L19-L47

**Comment by jonpryor** [comment]
…and we have a plausible explanation:

"For Sanity", https://github.com/xamarin/android-sdk-installer/commit/69fa0dcabaa85364385eae515f8c4737fd1dfcd4 changed the default repository from "GoogleV2" to "Xamarin" in the `<InstallAndroidDependencies/>` task.

The unit test, by way of the `AndroidSdkResolver.GetMaxInstalledPlatform()` invocation, is specifying that the app should build against API-32.

The "Xamarin" repository *does not have* API-32 available.  It only has up to API-31.  (We need to update the "Supported" repository.)

The test also involves two `msbuild` invocations:

  * `msbuild -t:InstallAndroidDependencies …`: this works
  * `msbuild -t:Build,SignAndroidPackage …`: this *fails*, because *no* Android SDK is installed.

Because no Android SDK is installed, we get an error saying that, but because of the `string.Format()` mismatch, the error message is "not obvious".

**Pull request merged**
