### PR TITLE
API O enumification

### PR DESCRIPTION
**Pull request by atsushieno**

### CODE REVIEW

**Comment by atsushieno** [comment]
It actually depends on https://github.com/xamarin/java.interop/pull/164 i.e. I don't care about [Interface] in methodmap.csv anymore.

**Comment by atsushieno** [comment]
It is ready to be merged (with the required java.interop changes).

**Comment by jonpryor** [comment]
> (with the required java.interop changes)

What are the required Java.Interop changes? Is it [support for static properties on interfaces](https://github.com/xamarin/java.interop/pull/159)?

**Comment by jonpryor** [comment]
Please rebase atop commit db668ba0 or later, as that has some attempted fixes (or just checks!) around `adb` use. The [failing macOS+xbuild PR Build](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/1093/) failed because the entire build timed out, waiting for `adb` to connect:

    Build timed out (after 600 minutes). Marking the build as aborted.

**Comment by jonpryor** [comment]
Additionally, we need to investigate [the ABI breakage](https://trello.com/c/ZxLagFhk/186-api-26-monoandroiddll-abi-breakage).

**Comment by jonpryor** [comment]
Trying to build this PR locally, and (oddly) it doesn't build:

```
obj/Debug/android-26/mcw/Android.Views.ViewGroup.cs(10,92): error CS0535: 'ViewGroup' does not implement interface member 'IViewParent.KeyboardNavigationClusterSearch(View, int)'
```

That aside, the previously mentioned ABI breakage is still in effect: `xamarin-android/src/Mono.Android/obj/Debug/android-26/mcw/Android.App.Activity.cs` contains:

```csharp
		public virtual unsafe Java.Lang.Object FindViewById (int id)
```

while API-25 contains:

```csharp
		public virtual unsafe Android.Views.View FindViewById (int id)
```

**Comment by jonpryor** [comment]
> It actually depends on xamarin/java.interop#164

The referenced PR has been merged.

**Comment by atsushieno** [comment]
You are supposed to fix your api-merge issue first.

**Comment by atsushieno** [comment]
Marking as do-not-merge as api-merge needs to be fixed first.

**Comment by atsushieno** [comment]
Now there is nothing that blocks merging this. No fixes in api-merge or anything else, it is not worth. Just two lines in metadata does the required work.

**Comment by jonpryor** [comment]
Please append `26` to `$(STABLE_API_LEVELS)` in [`build-tools/scripts/BuildEverything.mk`](https://github.com/xamarin/xamarin-android/blob/cffc699/build-tools/scripts/BuildEverything.mk#L26) so that we ensure that the new API-26 binding doesn't break API.

**Comment by atsushieno** [comment]
Since the commit messages can be gone after force updates, I'm copypasting the original text here.

Here is the list of the reported breaking changes:

   Perceptible = <span class='removed removed-inline removed-breaking-inline'>130</span> <span class='added '>230</span>

Google changed the value!

    public RemoteInput.Builder SetAllowFreeFormInput (bool <span class='removed removed-inline removed-breaking-inline'>allowFreeFormInput</span> <span class='added '>allowFreeFormTextInput</span>)

The bare parameter name changes that we already resolved as "renaming to the new name is the way what we do". api-diff most likely needs fix to not report this kind of changes.

	<span class='removed removed-method breaking' data-is-breaking>public virtual void OnServiceAdded (ProfileState status, BluetoothGattService service);</span>

It is actually a bugfix: https://bugzilla.xamarin.com/show_bug.cgi?id=55473

	public <span class='removed removed-inline removed-breaking-inline'>AdvertiseTx</span> <span class='added '>int</span> TxPowerLevel { get; }

It is also a bugfix for https://bugzilla.xamarin.com/show_bug.cgi?id=51293

	public virtual Android.Database.ICursor Query (Android.Net.Uri <span class='removed removed-inline removed-breaking-inline'>url</span> <span class='added '>uri</span>, string[] projection, string selection, string[] selectionArgs, string sortOrder, Android.OS.CancellationSignal cancellationSignal)
	public virtual void OnError (string <span class='removed removed-inline removed-breaking-inline'>itemId</span> <span class='added '>mediaId</span>)
	public virtual bool EnableNetwork (int netId, bool <span class='removed removed-inline removed-breaking-inline'>disableOthers</span> <span class='added '>attemptConnect</span>)
	public virtual SubscriptionInfo GetActiveSubscriptionInfoForSimSlotIndex (int <span class='removed removed-inline removed-breaking-inline'>slotIdx</span> <span class='added '>slotIndex</span>)
	public virtual string GetDeviceId (int <span class='removed removed-inline removed-breaking-inline'>slotId</span> <span class='added '>slotIndex</span>)
	public virtual void SetMaxEms (int <span class='removed removed-inline removed-breaking-inline'>maxems</span> <span class='added '>maxEms</span>)
	public virtual void SetMaxHeight (int <span class='removed removed-inline removed-breaking-inline'>maxHeight</span> <span class='added '>maxPixels</span>)
	(... and all those relevant methods on Android.Widget.TextView)
	public bool IsAnnotationPresent (Class <span class='removed removed-inline removed-breaking-inline'>annotationType</span> <span class='added '>annotationClass</span>)
	public bool IsAssignableFrom (Class <span class='removed removed-inline removed-breaking-inline'>c</span> <span class='added '>cls</span>)
	public bool IsInstance (Object <span class='removed removed-inline removed-breaking-inline'>object</span> <span class='added '>obj</span>)
	public virtual bool IsAnnotationPresent (Class <span class='removed removed-inline removed-breaking-inline'>annotationType</span> <span class='added '>annotationClass</span>)
	public virtual void TraceInstructions (bool <span class='removed removed-inline removed-breaking-inline'>enable</span> <span class='added '>on</span>)
	public virtual void TraceMethodCalls (bool <span class='removed removed-inline removed-breaking-inline'>enable</span> <span class='added '>on</span>)
	public virtual bool IsAnnotationPresent (Java.Lang.Class <span class='removed removed-inline removed-breaking-inline'>annotationType</span> <span class='added '>annotationClass</span>)
	public Java.Lang.Object NewInstance (Java.Lang.Object[] <span class='removed removed-inline removed-breaking-inline'>args</span> <span class='added '>initargs</span>)
	public string GetDisplayScript (Locale <span class='removed removed-inline removed-breaking-inline'>locale</span> <span class='added '>inLocale</span>)
	public string GetDisplayVariant (Locale <span class='removed removed-inline removed-breaking-inline'>locale</span> <span class='added '>inLocale</span>)
	public virtual int NextInt (int <span class='removed removed-inline removed-breaking-inline'>n</span> <span class='added '>bound</span>)
	public CopyOnWriteArrayList (Java.Lang.Object[] <span class='removed removed-inline removed-breaking-inline'>array</span> <span class='added '>toCopyIn</span>)
	(... and all those lines in Java.Util.Concurrent.CopyOnWriteArrayList)

They are all parameter name fixes in Android API.

	MaskFlags = <span class='removed removed-inline removed-breaking-inline'>4080</span> <span class='added '>65520</span>

Google changed the constant value here too. Well, it should.

	<span class='added added-interface breaking' data-is-breaking>Java.Lang.IAutoCloseable</span>

This is a bogus report. It sure adds another interface but it does not bring in any breaking change because the derived interface XmlResourceParser also contains the only member in AutoCloseable i.e. close() !

api-check must not report this as a breaking change. This applies to all other interfaces that report the same error too.

	<span class='added added-method breaking' data-is-breaking>public virtual View KeyboardNavigationClusterSearch (View p0, FocusSearchDirection p1);</span>

Why is this happening? Because they are static methods that should not be part of the interface member.

Why does this happen? Because this fix is not merged! https://github.com/xamarin/java.interop/pull/159

That fix really needs to be merged otherwise we keep generating these API incomatibility forever. The issue on java.time.chrono API mentioned there is actually due to totally different issue from the static <-> instance changes, so there is no excuse to not fix the static issue.

	<span class='removed removed-method breaking' data-is-breaking>public IAppendable Append (string s, int start, int end);</span>

Fixed: see src/Mono.Android/Java.Lang/StringBuffer.cs and src/Mono.Android/Java.Lang/StringBuilder.cs for details.

	<h3>Removed Type <span class='breaking' data-is-breaking>Java.Lang.Reflect.Constructor.InterfaceConsts</span></h3>
	<h3>Removed Type <span class='breaking' data-is-breaking>Java.Lang.Reflect.Method.InterfaceConsts</span></h3>

They must be brought be intrusive Google API changes due to the step-by-step migration from Harmony to OpenJDK. There are no members that used those consts and should be simply killed even without changes. We can take bugs IF ANYONE EVER used it. I don't waste my time on "fixing" this.

	<span class='removed removed-method breaking' data-is-breaking>public virtual bool IsAnnotationPresent (Java.Lang.Class annotationClass);</span>
	<span class='removed removed-method breaking' data-is-breaking>public virtual void AddPropertyChangeListener (Java.Beans.IPropertyChangeListener listener);</span>
	<span class='removed removed-method breaking' data-is-breaking>public virtual void RemovePropertyChangeListener (Java.Beans.IPropertyChangeListener listener);</span>
	(in both Pack200.IPacker and Pack200.IUnpacker)
	<span class='removed removed-property breaking' data-is-breaking>public virtual bool IsDestroyed { get; }</span>
	<span class='removed removed-method breaking' data-is-breaking>public virtual void Destroy ();</span>

They are all api-merge bug: why does api-merge preserve this method as a default interface method?? It had been non-default in earlier API Levels, therefore api-merge must generate this method as non-default.

	<span class='added added-interface breaking' data-is-breaking>IAnnotatedElement</span>

This is new in java.lang.reflect.GenericDeclaration interface and should also be part of huge Harmony - OpenJDK migration. And unlike other new additional interfaces, those methods in AnnotatedElement are not default, so they are indeed breaking changes.

At this state, I don't think there is anything we can help the situation. We cannot remove this base interface type because that will generate JCW  that doesn't compile.

The only idea I can think of is to completely kill this type. It's just like we give up EntityIterator.

	<span class='removed removed-method breaking' data-is-breaking>public virtual FileChannel Position (long newPosition);</span>
	<span class='removed removed-method breaking' data-is-breaking>public virtual FileChannel Truncate (long size);</span>
	<span class='removed removed-method breaking' data-is-breaking>public System.Threading.Tasks.Task&lt;FileChannel&gt; TruncateAsync (long size);</span>

This was actually newly introduced breakage for OpenJDK migration too. FileChannel now implements SeekableByteChannel, which never existed, and they require those methods to return ISeekableByteChannel in C#, not FileChannel whereas FileChannel **is** ISeekableByteChannel.

So they are changed in the metadata fixup, but then this breakage. Now Position() and Truncate() are added as explicit interface implementation.

However, what can we do for TruncateAsync() ? NOTHING! It is (semi-)automatically generated by `generateAsyncWrapper='true'` which is NOT defined in the interface and therefore it cannot be explicitly implemented. And it's all about return types.

	<span class='added added-interface breaking' data-is-breaking>Javax.Security.Auth.IDestroyable</span>

This should not be reported because all those interface methods are default!

	<h3>Removed Type <span class='breaking' data-is-breaking>Android.Service.Quicksettings.TileState</span></h3></div> 

I explicitly removed this. It had been marked as [Obsolete].

**Comment by jonpryor** [comment]
build

**Comment by atsushieno** [comment]
Marking as do-not-merge until api-merge gets fix.

**Comment by atsushieno** [comment]
After the fix at {...} these changes join the "false-negative reports on parameter name changes" party:

	public bool IsAnnotationPresent (Class <span class='removed removed-inline removed-breaking-inline'>annotationType</span> <span class='added '>annotationClass</span>)
public bool IsAssignableFrom (Class <span class='removed removed-inline removed-breaking-inline'>c</span> <span class='added '>cls</span>)
	public bool IsInstance (Object <span class='removed removed-inline removed-breaking-inline'>object</span> <span class='added '>obj</span>)

In addition, this appeared as a breakage (I guess I missed it as it looked like the duplicate of the same missing method in`GenericDeclaration`):

	<span class='removed removed-method breaking' data-is-breaking>public virtual bool IsAnnotationPresent (Java.Lang.Class annotationClass);</span>

FIXME: this should be brought back.

**Comment by atsushieno** [comment]
>>    <span class='removed removed-method breaking' data-is-breaking>public virtual bool IsAnnotationPresent (Java.Lang.Class annotationClass);</span>

> FIXME: this should be brought back.

This is now fixed.

**Comment by atsushieno** [comment]
https://github.com/mono/mono/pull/5293 blocks this.

**Comment by atsushieno** [comment]
https://github.com/xamarin/xamarin-android-api-compatibility/pull/2 blocks too.

**Comment by atsushieno** [comment]
I am tired of seeing those pointless "data-is-non-breaking" reports. Why are they reported at all?

**Comment by atsushieno** [comment]
If any insignificant lines still matter in this build step, why don't we dump the entire MSBuild log files from our msbuild tests? No you don't want to see them. I don't want to open useless logs every time I have to work on this stuff either, so let's not do this.

**Comment by atsushieno** [comment]
Since the original reports at https://github.com/xamarin/xamarin-android/pull/662#issuecomment-315065444 is too long to read, especially now that we've got tons of "fixes", here is the *updated* list of the reported breaking changes:

    Perceptible = <span class='removed removed-inline removed-breaking-inline'>130</span> <span class='added '>230</span>

Google changed the value!

	<span class='removed removed-method breaking' data-is-breaking>public virtual void OnServiceAdded (ProfileState status, BluetoothGattService service);</span>

It is actually a bugfix: https://bugzilla.xamarin.com/show_bug.cgi?id=55473

	public <span class='removed removed-inline removed-breaking-inline'>AdvertiseTx</span> <span class='added '>int</span> TxPowerLevel { get; }

It is also a bugfix for https://bugzilla.xamarin.com/show_bug.cgi?id=51293

	MaskFlags = <span class='removed removed-inline removed-breaking-inline'>4080</span> <span class='added '>65520</span>

Google changed the constant value here too. Well, it should.

	<h3>Removed Type <span class='breaking' data-is-breaking>Java.Lang.Reflect.Constructor.InterfaceConsts</span></h3>
	<h3>Removed Type <span class='breaking' data-is-breaking>Java.Lang.Reflect.Method.InterfaceConsts</span></h3>

They must be brought be intrusive Google API changes due to the step-by-step migration from Harmony to OpenJDK. There are no members that used those consts and should be simply killed even without changes. We can take bugs IF ANYONE EVER used it. I don't waste my time on "fixing" this.

I found two additional warnings.

    Type Changed: Java.Lang.Reflect.Constructor
    Modified base type: Java.Lang.Reflect.AccessibleObject Java.Lang.Reflect.Executable

    Type Changed: Java.Lang.Reflect.Method
    Modified base type: Java.Lang.Reflect.AccessibleObject Java.Lang.Reflect.Executable

(Why such an overlook happened? I was grepping "data-is-breaking" items but those lines were not marked with that specific attribute! This time they were uncovered because I could read the entire API diff report after all insignificant nonbreaking changes went away.)

Those are OpenJDK changes that we have no control over.

**Comment by jonpryor** [comment]
https://github.com/xamarin/xamarin-android-api-compatibility/pull/5 has been merged. Please update this PR to use the appropriate `xamarin-android-api-compatibility` commit.

That said, the [**macOS+xbuild PR Build** is failing](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/1252/):

```
        Android.Bluetooth/BluetoothGattServerCallback.cs(12,39): error CS0246: The type or namespace name 'ProfileState' could not be found (are you missing a using directive or an assembly reference?)
        Android.Bluetooth/BluetoothGattServerCallback.cs(12,60): error CS0246: The type or namespace name 'BluetoothGattService' could not be found (are you missing a using directive or an assembly reference?)
        Android.Bluetooth/BluetoothGattServerCallback.cs(17,30): error CS0246: The type or namespace name 'ProfileState' could not be found (are you missing a using directive or an assembly reference?)
        Android.Bluetooth/BluetoothGattServerCallback.cs(17,51): error CS0246: The type or namespace name 'BluetoothGattService' could not be found (are you missing a using directive or an assembly reference?)
```

**Pull request merged**
