### PR TITLE
[One .NET] allow M1 macs to find the Android workload

### PR DESCRIPTION
**Pull request by jonathanpeppers**
I got report of M1 Macs failing to build .NET 6 Android projects:

    Microsoft.NET.Sdk.ImportWorkloads.targets(24,5): error NETSDK1147: The following workload packs were not installed: Microsoft.Android.Sdk

Looking at our `WorkloadManifest.json`, we did not define an
`alias-to` for M1 Macs. Manually editing `WorkloadManifest.json`
solved the problem for them.

This gets us closer to M1 working.

There is now a new failure we can address next:

    Xamarin.Android.EmbeddedResource.targets(36,5): error XARLP7000: System.DllNotFoundException: Unable to load shared library 'libzip' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibzip, 1): image not found
        at Xamarin.Tools.Zip.Native.zip_open(IntPtr path, OpenFlags flags, ErrorCode& errorp)
        at Xamarin.Tools.Zip.Native.zip_open(String path, OpenFlags flags, ErrorCode& errorp) in /Users/runner/work/1/s/Native.cs:line 97
        at Xamarin.Tools.Zip.ZipArchive.Open(String path, OpenFlags flags) in /Users/runner/work/1/s/ZipArchive.cs:line 159
        at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options) in /Users/runner/work/1/s/ZipArchive.cs:line 230
        at Microsoft.Android.Build.Tasks.Files.ReadZipFile(String filename, Boolean strictConsistencyChecks) in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 335
        at Xamarin.Android.Tasks.MonoAndroidHelper.ReadZipFile(String filename)
        at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(IDictionary`2 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
        at Xamarin.Android.Tasks.ResolveLibraryProjectImports.RunTask()
        at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17 [/Users/drasticactions/Developer/Projects/net6-mobile-samples/HelloAndroid/HelloAndroid.csproj]

### CODE REVIEW

**Comment by dellis1972** [comment]
So I guess we need to build libzip for `osx-arm64` somehow

**Review by pjcollins — APPROVED** [review]
This seems reasonable. Hopefully we can avoid having to create an `Microsoft.Android.Sdk.osx-arm64` pack by creating universal binaries for the couple of native libraries that we're having issues with?

**Comment by drasticactions** [comment]
> So I guess we need to build libzip for `osx-arm64` somehow

@dellis1972  I did a native build of LibZipSharp and dropped in the resulting dylib to test. It got past that, but then it hit an error trying to load `libmonoposixhelper.dylib`. I think that's part of the Mono build process and I'm not sure how to get past that yet. Those were the only two native dylibs I saw in the workload though.

**Comment by dellis1972** [comment]
Related https://github.com/xamarin/LibZipSharp/pull/84

**Comment by jonathanpeppers** [comment]
Only test failure is `MissingOrgApacheHttpClient`, which we are working on in #5717.

**Pull request merged**
