### PR TITLE
Bump to mono/mono-4.8.0-branch/9e164326

### PR DESCRIPTION
**Pull request by jonpryor**
Mono 4.8 requires SGEN Bridge Version 5.

Supersedes: https://github.com/xamarin/xamarin-android/pull/221

### CODE REVIEW

**Comment by jonpryor** [comment]
Mono 4.8 uses Cecil/master, which is ABI-incompatible with Cecil 0.9.6 (what we're currently using):

https://gist.github.com/jonpryor/8136c2ba811d9c9383d8f4d4bf411be3

```
../../external/mono/mcs/tools/tuner/Mono.Tuner/CecilRocks.cs(481,43): error CS1061: Type `Mono.Cecil.TypeReference' does not contain a definition for `InterfaceType' and no extension method `InterfaceType' of type `Mono.Cecil.TypeReference' could be found. Are you missing an assembly reference?
```

We're going to have to re-work how we build Cecil. We can't use the nuget package.

**Comment by lewurm** [comment]
as a reference, `xamarin-macios` required also changes around `Cecil` when the bumped `mono`: https://github.com/xamarin/xamarin-macios/pull/733

**Comment by kumpera** [comment]
@marek-safar we're blocked on Cecil from bumping mono

**Comment by jonpryor** [comment]
As an added complication, the xamarin-android repo references projects/assemblies from the Java.Interop repo. The Java.Interop repo *also* uses Mono.Cecil, *but has no `mono` reference*. Consequently, "just" updating xamarin-android to use Mono.Cecil projects from `external/mono` *will not work*.

Thus, take 2:

1. Bump Java.Interop to use [the Mono.Cecil 0.10.0-beta1-pre2 NuGet Package](https://www.nuget.org/packages/Mono.Cecil/0.10.0-beta1-v2): https://github.com/xamarin/java.interop/pull/77
2. Update xamarin-android to *likewise* use the Mono.Cecil 0.10.0-beta1-pre2 NuGet package and include the appropriate Java.Interop commit, once merged.

In other news... ABI BREAKS SUCK.

[Film at 11](https://www.youtube.com/watch?v=9AT68eRX-p8).

**Comment by marek-safar** [comment]
You can use different versions of cecil (e.g not to change Java.Interop) but for code you are taking from mono 4.8 you need mono 4.8 cecil dependency. This should be quite simple, as all work was done but you need to fix your project(s) to have correct references.

**Pull request merged**
