### PR TITLE
Revert "[mono-sdks] Use for android toolchain"

### PR DESCRIPTION
**Pull request by luhenry**
This reverts commit fef45412d6b852afe654764bb38a2ad3ab5871c2.

This brings back the responsibility of setting up the Android toolchain back into XA. This follows a discussion I has with @jonpryor, and during which we concluded we didn't want Mono to be responsible for that.

### CODE REVIEW

**Comment by jonathanpeppers** [comment]
@luhenry actually I think something got lost in this revert:
```
  /mnt/jenkins/workspace/xamarin-anroid-linux-pr-builder/xamarin-android/src/monodroid/monodroid.targets(49,5): error MSB3073: The command "/home/builder/android-toolchain/sdk/cmake/3.6.4111459/bin/cmake -GNinja -DMONO_PATH=/mnt/jenkins/workspace/xamarin-anroid-linux-pr-builder/xamarin-android/external/mono -DSGEN_BRIDGE_VERSION=5 -DCMAKE_MAKE_PROGRAM=/home/builder/android-toolchain/sdk/cmake/3.6.4111459/bin/ninja -DANDROID_TOOLCHAIN=clang -DANDROID_NATIVE_API_LEVEL=9 -DCMAKE_TOOLCHAIN_FILE=/home/builder/android-toolchain/ndk/build/cmake/android.toolchain.cmake -DANDROID_NDK=/home/builder/android-toolchain/ndk -DCONFIGURATION=Release -DCMAKE_BUILD_TYPE=Debug -DANDROID_ABI=armeabi-v7a -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/mnt/jenkins/workspace/xamarin-anroid-linux-pr-builder/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/lib/armeabi-v7a /mnt/jenkins/workspace/xamarin-anroid-linux-pr-builder/xamarin-android/src/monodroid/" exited with code 127. [/mnt/jenkins/workspace/xamarin-anroid-linux-pr-builder/xamarin-android/src/monodroid/monodroid.csproj]

    4516 Warning(s)
    1 Error(s)
```

I think @grendello added `cmake` here, and this part isn't working.

**Comment by luhenry** [comment]
@grendello @jonathanpeppers it was just missing the cmake dependency at https://github.com/xamarin/xamarin-android/pull/2087/files#diff-537c65c49ec2131f809eb237923f0a15R79-R88. On the same note, versions are different between `external/mono/sdks/builds/android.mk` and `build-tools/android-toolchain/android-toolchain.projitems` for various packages, so which one is the source of truth and should we modify `build-tools/android-toolchain/android-toolchain.projitems` to match `external/mono/sdks/builds/android.mk`?

**Comment by jonathanpeppers** [comment]
@luhenry I think `external/mono/sdks/builds/android.mk` is the source of truth. The other one was likely only being used on Windows, since the build there can't run `make`.

But we should pick the higher number emulator `4773671` that should be fine. I bet we had a commit "updating" the emulator, but it wasn't _really_ doing it.

**Comment by jonathanpeppers** [comment]
build

**Comment by jonathanpeppers** [comment]
Ok, this build looks good now (I would think the 1 failed unit test is a fluke).

Trying the VSTS builds on fresh VMs.

**Pull request merged**
