### PR TITLE
Add first Android Q preview API build.

### PR DESCRIPTION
**Pull request by atsushieno**

### CODE REVIEW

**Comment by jonpryor** [comment]
I don't know what to make of the unit test results.

For example, from the [**macOS PR Release Pipeline Build**](https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/151/), [`xa-test-results-v9.2.99.74_Darwin-x86_64_pr_331a4b17-Release.zip`](https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/151/Azure/processDownloadRequest/xamarin-android-pr-pipeline-release-151/xamarin-android/xa-test-results-v9.2.99.74_Darwin-x86_64_pr_331a4b17-Release.zip) contains the log for the [`Xamarin.Android.Locale_Tests`](https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/151/testReport/junit/Xamarin.Android/Locale_Tests/Possible_Crash___Release/) execution, and it's...bizarre:

```
  Executing: /Users/builder/android-toolchain/sdk/platform-tools/adb -s emulator-5570  install "/Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/tests/../bin/TestRelease/Xamarin.Android.Locale_Tests-Signed.apk" (TaskId:31)
build-tools/scripts/TestApks.targets(154,5): warning : adb: failed to install /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/tests/../bin/TestRelease/Xamarin.Android.Locale_Tests-Signed.apk: Failure [INSTALL_PARSE_FAILED_NOT_APK: Failed to parse /data/app/vmdl242845261.tmp/base.apk]
```

`INSTALL_PARSE_FAILED_NOT_APK`?!

This same error occurs while attempting to install *every* `.apk` file.

The `msbuild-20190314T104847-Xamarin.Android.Locale-Tests.binlog` file shows no errors, so it certainly appears that `Xamarin.Android.Locale_Tests-Signed.apk` should be valid...

...except maybe perhaps that there's something wrong with Build-tools 29-rc?

```
  AndroidApkSigner: (TaskId:279)
    ApkSignerJar: /Users/builder/android-toolchain/sdk/build-tools/29.0.0-rc1/lib/apksigner.jar (TaskId:279)
    ApkToSign: /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/bin/TestRelease/Xamarin.Android.Locale_Tests-Signed.apk (TaskId:279)
    ManifestFile: obj/Release/android/AndroidManifest.xml (TaskId:279)
    AdditionalArguments:  (TaskId:279)
  /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java -jar /Users/builder/android-toolchain/sdk/build-tools/29.0.0-rc1/lib/apksigner.jar sign --ks "/Users/builder/.local/share/Xamarin/Mono for Android/debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugkey --key-pass pass:android --min-sdk-version 16 --max-sdk-version 22  /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-release/xamarin-android/bin/TestRelease/Xamarin.Android.Locale_Tests-Signed.apk  (TaskId:279)
```

I haven't tried repro'ing locally, but I have to wonder... :-/

**Comment by atsushieno** [comment]
```
Xamarin.Tools.Zip.ZipIOException : File /Users/builder/jenkins/workspace/xamarin-android-pr-pipeline-debug/xamarin-android/bin/TestDebug/CodeGen-MkBundle/Xamarin.Android.MakeBundle-Tests.build/Debug/project/bin/Debug/Xamarin.Android.MakeBundle_Tests-Signed.apk is not a ZIP archive
```

Hmm, indeed. It is possible that reverting back to build-tools 28.0.3 would fix the issue. I would try that and see what happens.

With system mono I have some msbuild problem that fails to resolve some corlib types (v2.0.5.0 and v4.0.0.0 like [this](https://stackoverflow.com/questions/46040113/valuetuplet1-t2-exists-in-both-system-valuetuple-and-mscorlib)) and cannot go further after nunitlite build locally.

**Comment by jonpryor** [comment]
@monojenkins build

**Comment by jonpryor** [comment]
Let's see if anything breaks when we do a full build...

**Pull request merged**
