### PR TITLE
[ci] Copy and publish OSS installer artifacts

### PR DESCRIPTION
**Pull request by pjcollins**
Our OSS builds have been producing .pkg and .vsix installer files,
however we seem to have neglected an attempt to upload these artifacts.
The OSS YAML pipeline has been updated to upload these artifacts for
external consumption as needed.

### CODE REVIEW

**Comment by jonpryor** [comment]
Looks like it broke somehow? https://dev.azure.com/xamarin/public/_build/results?buildId=27834&view=logs&j=d74e0ab2-7427-5d7a-0710-9fca89bfd13a&t=893a9b6b-0eed-5679-fc6b-7127b571e766

```
##[error]Not found workingDirectory: /Users/builder/azdo/_work/2/xamarin-android/xamarin-android
```

**Comment by pjcollins** [comment]
Oops, the wrong working directory was specified.

**Comment by jonpryor** [comment]
```markdown
Our OSS macOS builds have been producing `.pkg` and `.vsix` installer
files and our OSS Linux builds have been producing `.deb` files,
however we seem to have neglected to *upload* these artifacts.


Update the OSS YAML pipeline to upload these artifacts for external
consumption as needed.

From the [Xamarin.Android-OSS Pipelines page][0], click on the desired
commit.  In the **Related** section is a (non-obvious) link with the
label "*N* published".  Click "*N* published" to get to the
**Artifacts** page.  From there you can find installers:

  * Debian Linux `.deb`: **Installers - Linux** >
    **xamarin.android-oss_….deb**

  * macOS `.pkg`: **Installers - macOS and Windows** >
    **Xamarin.Android.Sdk-OSS-….pkg**

  * Windows `.vsix`: **Installers - macOS and Windows** >
    **Xamarin.Android.Sdk-OSS-….vsix**

NuGet packages for ongoing One .NET work are in the
**nupkgs - Linux** and **npkgs - macOS** "folders".

[0]: https://dev.azure.com/xamarin/public/_build?definitionId=48&_a=summary
```

**Comment by pjcollins** [comment]
@awattar What is your use case for these artifacts? I wouldn't recommend using these OSS artifacts in any sort of production workflow. It could be easy enough to separate the installers into unique artifact names if the need is strong enough though.

**Pull request merged**
