### PR TITLE
Bump mono to 5.4.0.0

### PR DESCRIPTION
**Pull request by luhenry**
cc @jonpryor

### CODE REVIEW

**Comment by jonpryor** [comment]
It would seem that the linker code doesn't like you:

```
19:19:03 	/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/external/linker/linker/Mono.Linker.Steps/TypeMapStep.cs(211,31): error CS1061: 'MethodReference' does not contain a definition for 'GetParameterType' and no extension method 'GetParameterType' accepting a first argument of type 'MethodReference' could be found (are you missing a using directive or an assembly reference?)
```

...plus 8 other similar errors.

**Comment by jonpryor** [comment]
This PR also needs to change [`$(MonoRequiredMinimumVersion)` and `$(MonoRequiredDarwinMinimumVersion)`](https://github.com/xamarin/xamarin-android/blob/d12a3bc/Configuration.props#L54-L55), otherwise we won't install the new `MonoFramework-MDK` file you specified (because the bot will already have 5.2 installed, which is the currently specified minimum version).

**Comment by lewurm** [comment]
linux build fails with:

> 15:08:42 	/mnt/jenkins/workspace/xamarin-anroid-linux-pr-builder/xamarin-android/build-tools/scripts/RequiredPrograms.targets: error : Missing dependency detected. For Linux we do not know how to install program `mono`, version >= 5.4.0.


 @jonpryor how would I fix that?

**Comment by jonpryor** [comment]
@lewurm wrote:

> linux build fails with:

Talk with @directhex about getting an updated mono for Linux.

**Comment by jonpryor** [comment]
build

**Comment by jonpryor** [comment]
build

**Comment by directhex** [comment]
(working on it, ought to be up by mid weekend)

**Comment by jonpryor** [comment]
FYI, the previously investigated unit test failures/etc. will continue to fail until PR #662 is merged.

**Comment by lewurm** [comment]
as a reference, #662 should (probably?) fix https://bugzilla.xamarin.com/show_bug.cgi?id=57828

**Comment by lewurm** [comment]
@jonpryor after bumping all the things (tm), this shows up:
```ABI BREAK IN: Mono.Security.dll
<!-- start namespace Mono.Security.Interface --> <div>
<h2>Namespace Mono.Security.Interface</h2>
<!-- start type MonoTlsProviderFactory --> <div>
<h3>Type Changed: Mono.Security.Interface.MonoTlsProviderFactory</h3>
<p>Removed methods:</p>

<pre>
    <span class='removed removed-method breaking' data-is-breaking>[Obsolete ("Use GetProvider() instead.")]
    public static MonoTlsProvider GetDefaultProvider ();</span>

    <span class='removed removed-method breaking' data-is-breaking>[Obsolete ("Use Initialize(string provider) instead.")]
    public static void SetDefaultProvider (string);</span>
</pre>

</div> <!-- end type MonoTlsProviderFactory -->

</div> <!-- end namespace Mono.Security.Interface -->
ABI BREAK IN: mscorlib.dll
<!-- start namespace System.Collections.Generic --> <div>
<h2>Namespace System.Collections.Generic</h2>
<!-- start type Dictionary`2 --> <div>
<h3>Type Changed: System.Collections.Generic.Dictionary`2</h3>
<p>Removed methods:</p>

<pre>
    <span class='removed removed-method breaking' data-is-breaking>public TValue GetValueOrDefault (TKey);</span>
    <span class='removed removed-method breaking' data-is-breaking>public TValue GetValueOrDefault (TKey, TValue);</span>
</pre>

</div> <!-- end type Dictionary`2 -->

</div> <!-- end namespace System.Collections.Generic -->
<!-- start namespace System.Security.Policy --> <div>
<h2>Namespace System.Security.Policy</h2>
<!-- start type PolicyException --> <div>
<h3>Type Changed: System.Security.Policy.PolicyException</h3>
<p>Removed interface:</p>

<pre>
    <span class='removed removed-interface breaking' data-is-breaking>System.Runtime.InteropServices._Exception</span>
</pre>

</div> <!-- end type PolicyException -->

</div> <!-- end namespace System.Security.Policy -->
make[1]: *** [check] Error 1
make: *** [run-api-compatibility-tests] Error 2
+ exit 1
Build step 'Conditional step (single)' changed build result to UNSTABLE
```

idea?

**Comment by jonpryor** [comment]
`ABI BREAK IN: mscorlib.dll` means "the public API in `mscorlib.dll` changed in a manner that we didn't expect."

The process works as follows:

1. https://github.com/xamarin/xamarin-android-api-compatibility contains a set of XML files that contains the `mono-api-info` output for our "reference" assemblies.
2. On every build, we run `mono-api-info` against the currently generated assemblies, then `mono-api-html` against the two sets of `mono-api-info` output (known-good and current).
3. If `>Removed` shows up, Something's Wrong™, and we emit an error.

In your particular output:

```html
<h2>Namespace System.Collections.Generic</h2>
<!-- start type Dictionary`2 --> <div>
<h3>Type Changed: System.Collections.Generic.Dictionary`2</h3>
<p>Removed methods:</p>

<pre>
    <span class='removed removed-method breaking' data-is-breaking>public TValue GetValueOrDefault (TKey);</span>
    <span class='removed removed-method breaking' data-is-breaking>public TValue GetValueOrDefault (TKey, TValue);</span>
</pre>
```

Losing `Dictionary<TKey, TValue>.GetValueOrDefault()` *sounds* bad; it's probably from: https://github.com/dotnet/corefx/issues/17275#issuecomment-291636863

The fix is:

1. Review the reported API breakage. Is this breakage intentional? Is it *acceptable*?

    Historically speaking, breakage in `Mono.*` is acceptable -- thus the `Mono.Security.Interface.MonoTlsProviderFactory` changes are fine -- while `System.*` changes are generally only acceptable if it brings us in-line with what .NET was doing, e.g. if the mono-based BCL had members which .NET "proper" did not.

    In our New World Order™ of using corefx and referencesource, if e.g. we rebased on corefx and corefx *removes those methods*, I'm not entirely sure how we should proceed. :-/

2. For API breakage which isn't acceptable, *fix it*. :-)

3. For API breakage which is acceptable, submit a PR against [xamarin-android-api-compatibility](https://github.com/xamarin/xamarin-android-api-compatibility) which updates the appropriate files. Once the `xamarin-android-api-compatibility` PR is merged, *this* PR (e.g. #631) should be updated to include the `xamarin-android-api-compatibility` bump.

**Comment by marek-safar** [comment]
It may sound harsh but GetValueOrDefault removal is not breaking change. It breaks at binary compatibility level but not sure we made such strong promise.

The API was migrated to extension method so it still compiles just using different code path. See https://github.com/mono/corefx/blob/master/src/System.Collections/src/System/Collections/Generic/CollectionExtensions.cs#L9

**Comment by jonpryor** [comment]
I *suspect* that the [current set of unit test failures](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/1317/testReport/), e.g.

    warning BG850* is NOT expected

is actually due to [Bug #56436](https://bugzilla.xamarin.com/show_bug.cgi?id=56436), as `warning BG8C00` will cause `warning BG8502: Invalidating Java.Util.IList and all nested types because some of its interfaces were invalid.`.

As such, these tests *may* be fixed once PR #732 is merged.

**Comment by lewurm** [comment]
**yay**:
#732 fixed [Bug #57828](https://bugzilla.xamarin.com/show_bug.cgi?id=57828) 🎉 

**nay**:
we have a new failure:
```                                                MESSAGE:
                                                  Expected: null
  But was:  "Well, hello there!"

                                                +++++++++++++++++++
                                                STACK TRACE:
                                                  at Xamarin.Android.LocaleTests.EnvironmentTests.EnvironmentVariablesFromLibraryProjectsAreMerged () [0x0000c] in <0c893f4f155244a9aacf4029c628e013>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <201fd8fdb1f34c919349c733ad7f3910>:0 ```

**Comment by jonpryor** [comment]
@lewurm: The `EnvironmentTests.EnvironmentVariablesFromLibraryProjectsAreMerged()` error should be addressed by PR #742.

**Comment by lewurm** [comment]
build for https://github.com/xamarin/xamarin-android/pull/631/commits/52097a1be958a5951704c5055976e3406a475f02 is green!!! 🙂

**Pull request merged**
