### PR TITLE
[build] Remove doc generation duplication

### PR DESCRIPTION
**Pull request by pjcollins**
Context: https://github.com/xamarin/monodroid/pull/1076

Removes the duplicate docs reference and doc generation
from the inverted build system.

### CODE REVIEW

**Comment by jonpryor** [comment]
Possible squash-and-merge commit message:

Description:

```
Bump to xamarin/monodroid/master@34f5275d (#4351)
```

Body:

```
Changes: https://github.com/xamarin/monodroid/compare/01a4e0a0c436bf1b0b62acf870cc06e67e62034c...34f5275d1db891e25af17d743b425cc318e6e7df

Fixes: https://github.com/xamarin/xamarin-android/issues/4344

  * xamarin/monodroid@34f5275d: [build] Remove android-api-docs submodule, archive supporting code (#1076)

Removes the duplicate docs reference and doc generation from the
inverted build system.
```

**Comment by jonpryor** [comment]
@brendanzagaeski: I believe that [your comment](https://github.com/xamarin/xamarin-android/pull/4351#pullrequestreview-372524021) means that you believe that this PR fixes Issue #4344?

@pjcollins: Please add a `Documentation/release-notes/4351.md` file with a description of the change for the release notes.  See also: https://github.com/xamarin/xamarin-android/blob/master/Documentation/release-notes/README.md#template-for-other-issue-fix-or-small-improvement

**Comment by brendanzagaeski** [comment]
> @brendanzagaeski: I believe that [your comment](https://github.com/xamarin/xamarin-android/pull/4351#pullrequestreview-372524021) means that you believe that this PR fixes Issue #4344?

Ah, no, it turned out #4344 was already fixed on d16-5 and d16-6 because the android-api-docs submodule was bumped as part of branch creation.

And this change by itself doesn't entirely ensure the root problem won't happen again. The android-api-docs submodule in xamarin-android could still fall behind the tip of the upstream repo.

But the work brought in by this PR does remove the redundancy of android-api-docs submodules and API docs build steps between monodroid and xamarin-android. And that will hopefully make it easier to make sure android-api-docs stays up-to-date (only one location to bump) and make it less confusing to diagnose any problems that might come up with the API docs in the future.

I was going to manually close #4344 once this PR is merged since the way that issue is fixed is a bit nuanced, and no single PR is the fix exactly.

> @pjcollins: Please add a `Documentation/release-notes/4351.md` file with a description of the change for the release notes. See also: https://github.com/xamarin/xamarin-android/blob/master/Documentation/release-notes/README.md#template-for-other-issue-fix-or-small-improvement

Since this PR by itself doesn't fix 4344 exactly, it ends up being an even swap of behavior from a user perspective, so there should be no user-facing change introduced by this PR. (That is, d16-5 and d16-6 already have the "good" behavior even though this PR isn't included in them.)

This is an interesting rare edge case for issues that we find are already fixed. I've manually added a few cases like that to release notes and release milestones, and that's what I'll do for 4344 too. Probably the best we could do would be to update the guidelines for issue triaging and closing to include a little description of how to close already-fixed issues (when they aren't clear duplicates of another issue).

**Comment by pjcollins** [comment]
I might as well go ahead and remove the release note mention then if that's preferable?

**Pull request merged**
