### PR TITLE
Bump to xamarin/monodroid/master@8cd2639e

### PR DESCRIPTION
**Pull request by brendanzagaeski**
Changes: https://github.com/xamarin/monodroid/compare/623845d44abe5eb7a76d9a63d48b30a27ac1bac2...8cd2639e7c396f4e5ee8816dccdb2db5fe523023

	$ git diff --shortstat 623845d4..8cd2639e
	 13 files changed, 178 insertions(+), 38 deletions(-)

Bring in changes to the commercial `InstallPackageAssemblies` task to
cache the `AndroidDeploySession` in MSBuild's AppDomain for reuse across
repeated fast deployments.

### CODE REVIEW

**Comment by brendanzagaeski** [comment]
There was one test failure for the `Xamarin.Android.Build.Tests.BuildTest.BuildHasNoWarnings(True,False)` test, caused by the following warnings during the build:

```
Using "ResolveXamarinAndroidTools" task from assembly "/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Build.Debugging.Tasks.dll".
Task "ResolveXamarinAndroidTools" (TaskId:35)
  Task Parameter:AndroidSdkPath=/Users/vsts/Library/Android/sdk (TaskId:35)
  Task Parameter:AndroidNdkPath=/Users/vsts/Library/Android/ndk (TaskId:35)
  Task Parameter:JavaSdkPath=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home (TaskId:35)
  Task Parameter:MonoAndroidToolsPath=/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android (TaskId:35)
  Task Parameter:MonoAndroidBinDirectory=/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Darwin/ (TaskId:35)
  Task Parameter:ReferenceAssemblyPaths=/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/ (TaskId:35)
  DEBUG  ValidateAndroidSdkLocation: `/Users/vsts/Library/Android/sdk`, result=True (TaskId:35)
  DEBUG  ValidateAndroidNdkLocation: `/Users/vsts/Library/Android/ndk`, result=True (TaskId:35)
  DEBUG  ValidateJavaSdkLocation: `/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home`, result=True (TaskId:35)
    Found AndroidSdk at /Users/vsts/Library/Android/sdk (TaskId:35)
    Found AndroidNdk at /Users/vsts/Library/Android/ndk (TaskId:35)
    Found AndroidTools at /Users/vsts/Library/Android/sdk/tools (TaskId:35)
  DEBUG  $(MonoAndroidToolsDirectory) path `/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android` is valid (TaskId:35)
  DEBUG  $(MonoAndroidToolsDirectory) defaultPath `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild/Xamarin/Android` is valid (TaskId:35)
  DEBUG  $(MonoAndroidBinDirectory) path `/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Darwin/` is valid (TaskId:35)
  DEBUG  $(MonoAndroidBinDirectory) defaultPath `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild/Xamarin/Android/Darwin` is valid (TaskId:35)
  DEBUG  mscorlib.dll path `/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0` is valid (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Version.txt` exists=False  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Version` exists=False  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Version.txt` exists=False  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Version` exists=False  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Version.txt` exists=False  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/Version` exists=False  (TaskId:35)
  DEBUG  mscorlib.dll defaultPath `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0` is valid (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild/Version.txt` exists=False  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild/Version` exists=False  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/Version.txt` exists=False  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/Version` exists=True  (TaskId:35)
   Did not find Xamarin.Android at path  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/Version.txt` exists=False  (TaskId:35)
  DEBUG  GetSdkPath `/Library/Frameworks/Xamarin.Android.framework/Versions/Current/Version` exists=True  (TaskId:35)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(109,2): warning XA5300:  Unable to determing Xamarin.Android version [/Users/vsts/agent/2.155.1/work/1/s/bin/TestRelease/temp/BuildHasNoWarningsTrueFalse/UnnamedProject.csproj]
   Did not find Xamarin.Android at path  (TaskId:35)
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(109,2): warning XA5300:  Unable to determing Xamarin.Android version [/Users/vsts/agent/2.155.1/work/1/s/bin/TestRelease/temp/BuildHasNoWarningsTrueFalse/UnnamedProject.csproj]
    Found RuntimePath at  (TaskId:35)
    Found FrameworkPath at  (TaskId:35)
Done executing task "ResolveXamarinAndroidTools". (TaskId:35)
```

This looks superficially similar to the symptom addressed by <https://github.com/xamarin/monodroid/pull/991>, but that fix is already included in this build.

After looking at [`LoadVersionInfo()`](https://github.com/xamarin/androidtools/blob/5c4c8e51d06e9d8f3bfa0ea1faf12aa70fe3a04f/Xamarin.AndroidTools/MonoDroidSdk.cs#L286-L291), [`GetSdkPath()`](https://github.com/xamarin/androidtools/blob/5c4c8e51d06e9d8f3bfa0ea1faf12aa70fe3a04f/Xamarin.AndroidTools/Sdks/MonoDroidSdkBase.cs#L151-L157), and [`FindVersionFile()`](https://github.com/xamarin/androidtools/blob/5c4c8e51d06e9d8f3bfa0ea1faf12aa70fe3a04f/Xamarin.AndroidTools/Sdks/MonoDroidSdkBase.cs#L181-L195), I'm not yet sure what's going wrong. It looks like as long as `GetSdkPath()` finds a `Version` file that exists, which it *does* in this case, then `SdkPath` should be set to a non-null value, and `FindVersionFile()` should log lines marked with `DEBUG FindVersionFile`. Those lines aren't appearing in this case.

In fact, even in a local build using a published Xamarin.Android version where `LoadVersionInfo()` succeeds, I'm seeing suspicious behavior where the method seems to be running twice:

```
  DEBUG  FindVersionFile: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Version, result=True (TaskId:84)
  DEBUG  FindVersionFile: C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Xamarin\Android\Version, result=True (TaskId:84)
   Found Xamarin.Android 10.0.0.40 (TaskId:84)
   Found Xamarin.Android 10.0.0.40 (TaskId:84)
```

**Comment by brendanzagaeski** [comment]
## Test results

### Summary

None of the test failures is likely to be related to the contents of this PR.

### 1  Xamarin.Android.NetTests failure

For the Azure Pipelines build, there was a test failure for `Xamarin.Android.NetTests.AndroidClientHandlerIntegrationTests.HttpClientIntegrationTestBase.GetString_Many / Release`. Azure Pipelines did not show any other recent failures of this test for other PR builds, but that also means the test passed for the previous build of this same PR. The only change since that previous build was to switch the monodroid base commit. As of <https://github.com/xamarin/xamarin-android/commit/d4c8f077faefdfc6174355848a9d8c74ecaa8f56>, the xamarin-android master branch is already using that new monodroid base commit (623845d4), and it is *not* hitting this test failure.

That leaves two possible explanations. The first is that just by chance this test encountered a network connectivity issue on this particular run, which would mean the failure is not related to the contents of the PR. I believe this is the correct explanation. The other possibility would be that the changes to add `AndroidDeploySession` caching in xamarin/monodroid#987 somehow interacted with the 3 new commits between the previous monodroid base commit (ae622c72) and the new base commit (623845d4). Considering that the `AndroidDeploySession` caching does not touch the networking stack, that possibility seems unlikely.

### 1 `run-api-compatibility-tests` failure

The API compatibility tests failed on the Jenkins build due to an API change:

<pre>
Modified fields:

	public const <del>int</del> <ins>ProfileType</ins> HearingAid = 21;
</pre>

This is a known temporary test breakage that is unrelated to the contents of this PR. The [fix for this temporary breakage](https://github.com/xamarin/xamarin-android/commit/8bf664e2596044212612e3d0c449ace00c6f09c0) was committed a little after the most recent build of this PR.

### Xamarin.Android (Test Designer Mac) build incomplete

```
The agent: Azure Pipelines 113 lost communication with the server. Verify the machine is running and has a healthy network connection. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
```

This issue is not related to the contents of this PR.

**Comment by brendanzagaeski** [comment]
@jonathanpeppers and @dellis1972 whenever you get a moment for one more sanity check of this draft bump as a final approval step before https://github.com/xamarin/monodroid/pull/987 gets merged. (And then we can either discard this test PR or update the `.external` file to match the final commit in monodroid master.)

Let me know if I missed anything. Thanks!

**Comment by brendanzagaeski** [comment]
**Changes in the latest force-push:**

Update the `.external` reference to the latest corresponding monodroid commit to check the results.

Also, rebase this PR on xamarin-android/master just to be thorough.

**Comment by dellis1972** [comment]
This looks good, only failing test is
`MonoTests.System.GCTest.TestGetBytesAllocatedForCurrentThread` which is unrelated. 
I think we can merge  xamarin/monodroid#987

**Comment by jonathanpeppers** [comment]
@brendanzagaeski you should be able to bump this to latest xamarin/monodroid/master@8cd2639e7c396f4e5ee8816dccdb2db5fe523023 now.

**Comment by brendanzagaeski** [comment]
**Changes in the latest force-push:**

Update the `.external` reference to point to the merged monodroid commit <https://github.com/xamarin/monodroid/commit/8cd2639e7c396f4e5ee8816dccdb2db5fe523023>.

Add an entry to the release notes draft file for the new work included in the monodroid bump.

Do a first pass at updating the commit message to be closer to the standard format for a monodroid bump.

**Comment by brendanzagaeski** [comment]
**Changes in the latest force-push:**

Rebase on xamarin-android/master to get <https://github.com/xamarin/xamarin-android/commit/7200d66a756e78f2ee4119d03a431f4d0ef60d2a> to fix up the macOS build.

**Pull request merged**
