### PR TITLE
bump linker to get fix for #58740

### PR DESCRIPTION
**Pull request by radekdoulik**
- the commit:

    commit 07b07ef75fa1858253af45af6fe30812a5a1655c
    Author: Marek Safar marek.safar@gmail.com
    Date: Wed Aug 23 00:44:47 2017 +0200

     Don't crash on any wrong type forwader reference

### CODE REVIEW

**Comment by radekdoulik** [comment]
note that macios will have this fixed for d15-4 as well https://github.com/xamarin/xamarin-macios/pull/2530

**Comment by radekdoulik** [comment]
build

**Comment by jonpryor** [comment]
The [**macOS+xbuild PR Build** failed](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/1433/console) because of my new favorite PR #767: the emulator didn't launch properly.

(I think this build actually timed out. I'm surprised *only* an hour elapsed between `<StartAndroidEmulator/>` and the build terminating.)

**Comment by radekdoulik** [comment]
That's because I aborted it by hand yesterday. After restart it timed out again this morning, after 10 hours.

`10 hr building on an executor`
`06:45:32 Build timed out (after 600 minutes). Marking the build as aborted.`

I think we should cherry-pick PR #767 commit to d15-4

**Comment by radekdoulik** [comment]
build

**Pull request merged**
