### PR TITLE
[cycle9] [aot] allow LLVM/AOT configuration for aarch64

### PR DESCRIPTION
**Pull request by lewurm**
backport of https://github.com/xamarin/xamarin-android/pull/338

### CODE REVIEW

**Comment by lewurm** [comment]
build

**Comment by lewurm** [comment]
build

**Comment by lewurm** [comment]
build

**Comment by jonpryor** [comment]
Applied via cherry-pick in a7e7aa843e1095319da6fe6a670291a60411ae40.

**Pull request closed without merging**
