### PR TITLE
[tests] add a task for tests result filtering

### PR DESCRIPTION
**Pull request by radekdoulik**
- it is based on Adb task, filters tests result line from the adb
   command output and writes it to the console

### CODE REVIEW

**Comment by jonpryor** [comment]
As discussed on the call this morning, this should instead be done within the monodroid module.

**Comment by radekdoulik** [comment]
Tried the discussed approach - to use Exec task to execute shell pipeline with adb logcat to sed to get rid of leading whitespace. That doesn't work, because Exec command output is again indented by msbuild :-)

I guess what we can do is to create similar task in monodroid, so that we don't have the inter module dependency.

Comments?

**Comment by jonpryor** [comment]
Creating a task won't help, as all task output is similarly indented.

It sounds like we  may need to do this logic within `make` in the monodroid repo, possibly along with an MSBuild-tasks-side `adb -d logcat > output.txt`.

**Comment by radekdoulik** [comment]
The task was working OK, because it used Console instead of Log class. I have already did it meanwhile in monodroid within the make yesterday :-)

**Pull request closed without merging**
