### PR TITLE
If building on FlatPak, change the system lib directory define

### PR DESCRIPTION
**Pull request by directhex**
Best to make sure Jenkins completes a build of this.

### CODE REVIEW

**Comment by jonpryor** [comment]
It occurs to me that there's a problem with the xamarin-android build system, tangentially related to this PR:

`xamarin-android/src/monodroid` only builds *Android* libraries. It uses `ndk-build` to generate `libmono-android*.so`, and `ndk-build` output can't be expected to run "normally" on Linux, macOS, or Windows.

For starters, what this means is that you shouldn't be changing `Android.mk`. Full stop.

Instead, we need to create a set of `gcc` invocations which emit the desired native library. `build-tools/mono-runtimes` might be handy there.

**Comment by directhex** [comment]
So this isn't used for the Host-Linux stuff?

**Comment by jonpryor** [comment]
> So this isn't used for the Host-Linux stuff?

No. The host build is currently only done in the `monodroid/libmonodroid` build. This is yet another thing that needs migrating.

**Comment by jonpryor** [comment]
Superseded by PR #277.

**Pull request closed without merging**
