### PR TITLE
Add "AndroidManifest resource collection and generate information" tool.

### PR DESCRIPTION
**Pull request by atsushieno**

### CODE REVIEW

**Comment by jonpryor** [comment]
build

**Comment by jonpryor** [comment]
I assume that the intent of this tool is to replace/supplement all of the e.g. `ActivityAttribute` custom attributes used between `Mono.Android.dll` and `Xamarin.Android.Build.Tasks.dll`.

Should the introduction of the tool be alongside the presumed custom attribute behavior? If the tool and the new *use* is in the same PR, it's easier to see how these pieces fit together.

**Comment by atsushieno** [comment]
It is not really for generating code. I thought it's good, but I thought about it again and concluded it's not worthy. It is enough that we can find which elements and attributes are new.

**Comment by jonpryor** [comment]
> It is enough that we can find which elements and attributes are new.

Fair enough.

Could you please write some documentation on how to *use* this tool? Presumably it could be part of `Documentation/HowToAddNewApiLevel.md` (as we'll want to review the attributes on API level bumps).

**Pull request merged**
