### PR TITLE
[tests] Import tests/locale from monodroid/2ed1f0f6

### PR DESCRIPTION
**Pull request by jonpryor**
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=4902
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=15214
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=24742

Add tests around use of satellite assemblies and unit tests (!).

### CODE REVIEW

**Comment by jonpryor** [comment]
This is bad. (Yay Jenkins!)

    UnitTestApks.targets: error : Tool exited with code: 255. Output: Invalid APK file: /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/tests/../bin/TestDebug/Xamarin.Android.Locale_Tests-Signed.apk

**Comment by jonpryor** [comment]
Test failure was caused because `tests/locales/Xamarin.Android.Locale-Tests/Xamarin.Android.Locale-Tests.csproj` wasn't part of `$(TEST_APK_PROJECTS)`. (Or so I hope; otherwise, I'm not sure. ;-)

That should be fixed in 442709b.

**Comment by atsushieno** [comment]
build

**Comment by jonpryor** [comment]
wat.

`SslTest.HttpsShouldWork`:

```
Mono.Security.Protocol.Tls.TlsException : The server stopped the handshake
```

I suspect that will explain all the network-related errors.

**Pull request merged**
