### PR TITLE
Ignore the `nonuapaottests` category of XUnit tests

### PR DESCRIPTION
**Pull request by grendello**
Fixes: https://github.com/xamarin/xamarin-android/issues/1400

### CODE REVIEW

**Comment by pjcollins** [comment]
@grendello should (can?) we do this only when the linker is enabled? Perhaps this is something I can handle only when testing a project configuration that enables the linker? I am not entirely sure that we should be skipping the entire category due to one test failure that occurs only when linking.

**Comment by jonpryor** [comment]
> should (can?) we do this only when the linker is enabled? 

We could wrap it in a `#if RELEASE` block, on the assumption that Release apps will be linked (fair?).

Alternatively we handle this in the "calling" code, e.g. by setting the `$(ExcludeCategories)`?

**Comment by grendello** [comment]
> 
> 
>     should (can?) we do this only when the linker is enabled?
> 
> We could wrap it in a #if RELEASE block, on the assumption that Release apps will be linked (fair?).

Either that or we could narrow it down a bit more. Introduce the `AOT` macro and exclude the category only then. It all depends on how long do we think the situation will remain unchanged with the failing test. O opened the PR mostly to show how/where we can exclude categories :)

> 
> Alternatively we handle this in the "calling" code, e.g. by setting the $(ExcludeCategories)?

That should work too

**Comment by jonpryor** [comment]
build

**Comment by jonpryor** [comment]
Rebuilding with the **full-mono-integration-build** label set so that we build and run unit tests in the Release configuration, which *should* (hopefully) cause the assemblies to be linked. (They aren't linked in Debug).

If the linker is removing the method, shouldn't that happen whenever the linker runes, i.e. Release, not just Release+AOT? Let's find out!

**Comment by jonpryor** [comment]
As I feared/suspected, the `TaskSchedulerTests.GetTaskSchedulersForDebugger_ReturnsDefaultSchedule()` test fails in Release configuration, w/o AOT: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/2971/testReport/Test%20collection%20for%20System.Threading.Tasks.Tests/TaskSchedulerTests/System_Threading_Tasks_Tests_TaskSchedulerTests_GetTaskSchedulersForDebugger_ReturnsDefaultScheduler___Release/

@grendello: instead of using `#if AOT` (and defining AOT in the first place), I think we should instead use `#if !DEBUG`.

**Comment by jonpryor** [comment]
Superseded by PR #1630.

**Pull request closed without merging**
