### PR TITLE
Bump to .NET 6.0.100-preview.1.21103.13

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Changes: https://github.com/dotnet/installer/compare/f4682754...b8a03527

### CODE REVIEW

**Comment by grendello** [comment]
I'm getting the following error with this version:

```
/usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error : Unable to find package Microsoft.NETCore.App.Runtime.android-arm64 with version (= 6.0.0-preview.1.21103.13)
/usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error :   - Found 760 version(s) in dotnet6 [ Nearest version: 6.0.0-preview.2.21075.8 ]
/usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error :   - Found 10 version(s) in nuget.org [ Nearest version: 5.0.2 
/usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error :   - Found 0 version(s) in dotnet-eng
/usr/lib/mono/msbuild/Current/bin/NuGet.targets(128,5): error :   - Found 0 version(s) in xamarin.android util
```

However `preview.2.21075.8` works just fine

**Comment by grendello** [comment]
Ugh, spoke too soon - it does find the nuget package, but doesn't find the corresponding dotnet version:

```
stderr | dotnet_install: Error: Could not find `.NET Core SDK` with version = 6.0.100-preview.2.21075.8
stderr | dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
  Error: Installation of dotnet SDK 6.0.100-preview.2.21075.8 failed.
```

so partial success... :)

**Comment by grendello** [comment]
The version that works from me is `preview.1.21101.4`

**Comment by jonathanpeppers** [comment]
@grendello it seems like it is working for me (and CI):
```
Installed Microsoft.NETCore.App.Runtime.android-arm64 6.0.0-preview.1.21102.12 from https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json with content hash 7wSsLCCk5kAC1lUTrEfpMXkTHc3V54Gl8mSokkDp9TLX+paAzOdDbEn0zl+SAGT/hGkale1E1mEHU0E+iT/TnQ==.
```
This was a really fresh build, can you try again tomorrow morning? To see if it is CDN-related or something.

Also try changing the `NuGet.config`:
```diff
--<add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json" />
++<add key="dotnet6" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/6.0.100-preview.1.21103.13/nuget/v3/index.json" />
```
This is a new feed, but it seems like the other one works, too. I'd rather use the `dotnet6` feed, because nightly builds show up there.

**Comment by jonathanpeppers** [comment]
Ok @grendello, I realized you might be trying to get the header files.

If I install .NET 6.0.100-preview.1.21103.1, then open: `~/android-toolchain/dotnet/sdk/6.0.100-preview.1.21103.13/dotnet.runtimeconfig.json`

You can see the version of the runtime the SDK expects:
```json
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0-preview.1.21102.12"
    }
  }
}
```

So .NET 6.0.100-preview.1.21103.1 depends on the 6.0.0-preview.1.21102.12 runtime... 🙄

**Comment by grendello** [comment]
@jonathanpeppers  the new version still doesn't work for me this morning, it can't find the runtime nugets (`xaprepare` uses `PackageDownload` to get them from its .csproj), maybe they haven't been published yet. I'll keep using the older version for now.

**Comment by jonathanpeppers** [comment]
@grendello use the version that's working for now.

When you get to the point you have a PR, we can figure out the version, thanks.

**Pull request merged**
