### PR TITLE
Bump to mono:2018-06

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by grendello** [comment]
Linux failure: ` /mnt/jenkins/workspace/xamarin-anroid-linux-pr-builder/xamarin-android/build-tools/scripts/RequiredPrograms.targets(22,5): error : Missing dependency detected. For Linux we do not know how to install program `mono`, version >= 5.16.0.`

**Comment by grendello** [comment]
Mac failure: ```22:06:46   /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/build-tools/xa-prep-tasks/xa-prep-tasks.targets(91,5): error : Unable to download URL `https://dist.nuget.org/win-x86-commandline/latest/nuget.exe` to `/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/build-tools/xa-prep-tasks/../../.nuget/NuGet.exe`: An error occurred while sending the request [/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/build-tools/xa-prep-tasks/xa-prep-tasks.csproj]
22:06:46   /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/build-tools/xa-prep-tasks/xa-prep-tasks.targets(91,5): error : An error occurred while sending the request [/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/build-tools/xa-prep-tasks/xa-prep-tasks.csproj]```

**Comment by grendello** [comment]
build

**Comment by luhenry** [comment]
We are focusing on the mono:2018-04 intégration ate this moment since I took over both. We will get back to this one a soon soon as 2018-04 is merged.

**Comment by grendello** [comment]
New mac build error: ```  /bin/sh: fork: Resource temporarily unavailable
  clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
  gmake[5]: *** [lib/Support/CMakeFiles/LLVMSupport.dir/build.make:1191: lib/Support/CMakeFiles/LLVMSupport.dir/SourceMgr.cpp.o] Error 128
  gmake[5]: *** Waiting for unfinished jobs....
``` 
Looks like the bot isn't keeping up or the resource limits for the user building the project are too low?

**Comment by grendello** [comment]
@luhenry if the focus is on `2018-04`, can we get https://github.com/mono/mono/commit/170e9442c976ed6cd4a499093e11a9e12e7368bb in there as well?

**Comment by luhenry** [comment]
We run into `clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable`, is that something you can observe in other builds as well?

**Comment by grendello** [comment]
@luhenry it's been the same error since at least June, which is good and bad - it's consistent enough that we have a chance of tracking it. I haven't seen any other builds fail in this way so far. The bot's resources have been bumped two days ago and that caused the build to fail later, so it seems there's a "fork bomb" hidden somewhere there. We're still trying to find what's causing it.

**Comment by MSylvia** [comment]
build

**Comment by MSylvia** [comment]
build

**Comment by luhenry** [comment]
@MSylvia still some `/bin/sh: fork: Resource temporarily unavailable` 😕

**Comment by MSylvia** [comment]
@luhenry Ya 😞 Have been changing some settings on the machine.
The OS version`10.12.6` is now the same as the master and mono build bots.
Looking into autoconf, automake, etc versions now.

**Comment by MSylvia** [comment]
build

**Comment by MSylvia** [comment]
So we no longer fail with a `/bin/sh: fork: Resource temporarily unavailable` error.
We think there is a bug in gmake 4.1.2 causing a process creation spike that results in the fork error.
Switching to ninja 1.8.2 solved the issue.

**Comment by grendello** [comment]
The current build issue is:

```
/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/external/mono/mono/mini/aot-compiler.c: In function 'mono_compile_assembly':
  /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/external/mono/mono/mini/aot-compiler.c:12853:17: error: implicit declaration of function 'mkdtemp' [-Werror=implicit-function-declaration]
       temp_path = mkdtemp(g_strdup ("mono_aot_XXXXXX"));
```

**Comment by luhenry** [comment]
@grendello I am looking for an alternative to `mkdtemp` on Android.

**Comment by grendello** [comment]
@luhenry `mkdtemp` is present (at lest in the headers) in the NDK, in the `platforms/android-9/arch-x86/usr/include/stdlib.h` file. `aot-compiler.c` doesn't include `stdlib.h` directly - perhaps that's all it'd take to fix this?

**Comment by jonpryor** [comment]
I believe that many of the reported unit test failures are because this branch is missing commit 2e8f96f5ef765a29e5022e9e4bd5c33085467e25 (PR #2125), as the tests are failing because `cross-arm` doesn't exist:

```
error XA3001: ---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: ApplicationName='/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/Darwin/cross-arm', CommandLine='--aot=outfile=/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/src/Mono.Android/Test/obj/Release/aot/armeabi-v7a/libaot-mscorlib.dll.so,asmwriter,mtriple=armv7-linux-gnueabi,tool-prefix=/Users/builder/android-toolchain/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-,ld-flags=,llvm-path=/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/Release/lib/xamarin.android/xbuild/Xamarin/Android/Darwin,temp-path=/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/src/Mono.Android/Test/obj/Release/aot/armeabi-v7a/mscorlib.dll /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/src/Mono.Android/Test/obj/Release/android/assets/shrunk/mscorlib.dll', CurrentDirectory='/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/src/Mono.Android/Test', Native error= Cannot find the specified file [/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/src/Mono.Android/Test/Mono.Android-Tests.csproj] [/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/build-tools/scripts/RunTests.targets]
```

That said, [xamarin-android:master](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/) is *still* not green, and we need to investigate further.

**Comment by luhenry** [comment]
This was tested against `Xamarin-android:f6c3288dd5a7f82c178ef30ad25c11d475f1daf4` which on Jenkins had the same test failure/success (https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1160/testReport/). Let's rerun this PR against a newer `xamarin-android:master` which has more test succeeding (https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/1166/testReport/ has 41,841 tests running).

**Comment by luhenry** [comment]
@jonpryor how can I get more information from the failures at https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3989/testReport/? Especially the `Xamarin.Android.Build.Tests.BuildTest` tests.

**Comment by jonpryor** [comment]
For the [current **macOS PR Build**](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3989/) log, the [** Xamarin.Android.Build.Tests.BuildTest.BuildAotApplication.("armeabi-v7a",True,True) / Release**](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3989/testReport/Xamarin.Android.Build.Tests.BuildTest/BuildAotApplication/__armeabi_v7a__True_True____Release/) failure is:

```
  [aot-compiler stderr] /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/TestRelease/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.s: Assembler messages: (TaskId:198)
  [aot-compiler stderr] /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/TestRelease/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.s:129: Error: missing .fnstart before unwinding directive (TaskId:198)
  [aot-compiler stderr] /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/TestRelease/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/aot/armeabi-v7a/System.dll/temp-llvm.s:147: Error: missing .fnstart before unwinding directive (TaskId:198)
...
  [aot-compiler stderr] AOT of image /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/TestRelease/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/android/assets/shrunk/System.dll failed. (TaskId:198)
...
error XA3001: Could not AOT the assembly: System.dll
```

I don't know why, but AOT appears to be broken.

**Comment by jonpryor** [comment]
@luhenry: to get more information, download the [`xa-test-errors*.zip` link](
https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3989/Azure/processDownloadRequest/xamarin-android-pr-builder-3989/xamarin-android/xa-test-errors-v9.1.99.170_Darwin-x86_64_HEAD_17d7792.zip).  Contained within it are the build directories for the failing test projects, and corresponding build logs.

That is how I got the error message [above](#issuecomment-422076933).

**Comment by jonpryor** [comment]
Looking at the [**macOS PR Build**](
https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091) results, there are:

* [9 unit test failures](
https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091/testReport/)
* API breakage in [`mscorlib.dll`](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091/API_20Compatibility_20Checks/mscorlib.html) and [`System.Numerics.Vectors.dll`](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091/API_20Compatibility_20Checks/System.Numerics.Vectors.html).

The unit test failures need to be reviewed (and ideally fixed); why is `StringBuilder` failing?  Why are the `StringComparer` tests failing?

The [`AndroidClientHandlerTests` failure](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4091/testReport/junit/(root)/AndroidClientHandlerTests/Mono_Android_Tests__Xamarin_Android_NetTests_AndroidClientHandlerTests_Sanity_Tls_1_2_Url_WithMonoClientHandlerFails___Release_Aot/) is *probably* ignorable, as it's *probably* a transient network error; see also 136324c0cc30e325c1cf4edb28fad1682e729b5e.

The API breakage also needs to be reviewed and either fixed/removed, or the https://github.com/xamarin/xamarin-android-api-compatibility repo updated to track these removals.

**Comment by marek-safar** [comment]
@jonpryor StringBuilder tests are new tests and are failing in Release mode only. Any ideas what can be different there?

**Comment by EgorBo** [comment]
@radekdoulik https://github.com/mono/corefx/blob/196e79b1b22cef2a05f1e9457f180326b3aa009a/src/System.Runtime/tests/System/Text/StringBuilderTests.cs

**Comment by jonpryor** [comment]
@radekdoulik: Any idea why the `StringBuilder` tests would be failing only in Release builds?

**Comment by jonpryor** [comment]
@EgorBo: Where's the current `StringBuilder` source?

**Comment by EgorBo** [comment]
@jonpryor somewhere in mono/external/corefx: https://github.com/mono/mono/blob/65737564b04315d79671ef223c0ff10ecfa04d03/mcs/class/corlib/corlib.dll.sources#L1429

**Comment by marek-safar** [comment]
@jonpryor could you please review the status

**Comment by jonpryor** [comment]
There is [API Breakage](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/4175/API_20Compatibility_20Checks/) being reported.  This breakage should be addressed.

**Comment by marek-safar** [comment]
API breakage is not significant.

System.Numerics.Vectors type were replaced with type-forwarders (the tool cannot detect that)

MemoryHandle change is due to previous Span preview which we missed to hide (it should be in previous release only)

CreateAsyncMethodBuilder - is infrastructure code not intended for public usage

**Comment by jonpryor** [comment]
> API breakage is not significant.

I *want* to believe that.

But then I remember:

* https://github.com/xamarin/xamarin-android/pull/1503: mono:2018-04 bump, which detected API breakage around `string.Concat(object, object, object, object)` on or around 2018-Aug-9.
* https://github.com/xamarin/xamarin-android/pull/2051#issuecomment-412651872: An explanation for the `string.Concat()` removal on 2018-Aug-13
* https://github.com/mono/mono/issues/9996: An EntityFramework bug where things break...because `string.Concat(object, object, object, object)` was removed.  Filed on 2018-Aug-9, it wasn't investigated until 2018-Aug-30 and fixed on 2018-Sep-3.

*Especially* after the above `string.Concat()` experience, do we *really* think that the `MemoryHandle(IRetainable, void*, GCHandle)` constructor removal, `IRetainable` type removal, and `CreateAsyncMethodBuilder()` removal are *really* "not significant"?

[This](
https://github.com/dotnet/corefx/issues/22171#issuecomment-327254875) certainly suggests that the `CreateAsyncMethodBuilder()` removal is fine:

> Checked API usage (nuget and API port): no usage at all.

I can't easily find anything similar regarding `IRetainable` or `HasPointer`, just lots of forks of the corefx repo which contain the `IRetainable` type, as well as tvOS documentation:

https://github.com/xamarin/documentation/blob/28fe21da3488aced982082fbf72a40393e027cfd/releases/ios/api_changes/tvos-11-10-1-11-11-0.md

`IRetainable` is even mentioned in the .NET Core 2.0 .. 2.1 diff: https://github.com/dotnet/apireviews/blob/ac765393a7281184ec30948b7a6d86b7ad58af1c/2018/NetCore20-vs-NetCore21-Diff/README.md

*Are* the changes *really* not significant?

**Comment by marek-safar** [comment]
Here is the story behind IRetainable https://github.com/dotnet/corefx/commit/f592e887e2349ed52af6a83070c42adb9d26408c#diff-577bd970484f00965a5e67de411cab76. It was design change before RTW unfortunately at that point we were not using stable branch of CoreFX so we accidentally shipped that API because we missed it when hiding the unstable Span APIs. I'd be very surprised if anyone managed to take a dependency on it in 15.8 which was the first release the API showed up and 15.9 won't have it either.

**Comment by jonpryor** [comment]
@marek-safar, @luhenry: Then the next step is to submit a PR against https://github.com/xamarin/xamarin-android-api-compatibility which updates `reference/mscorlib.xml` and `reference/System.Numerics.Vectors.xml` with the expected API changes.  This can be done from a `xamarin-android` checkout with:

```bash
$ cd external/xamarin-android-api-compatibility
$ make update XA_FRAMEWORK_DIR=$(cd ../../ && pwd)/bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid
```

Once the xamarin-android-api-compatibility PR has been merged, this PR can be updated to include a xamarin-android-api-compatibility bump, which will allow things to work.

**Comment by jonpryor** [comment]
https://github.com/xamarin/xamarin-android-api-compatibility/pull/19 has been merged.

The `external/xamarin-android-api-compatibility` submodule reference can now be bumped and included into this PR.

**Comment by jonpryor** [comment]
...and with luck the Android emulator won't behave badly on the next build...

**Comment by lassana** [comment]
Hi everyone, 
which version of Xamarin.Android includes this?

**Pull request merged**
