### PR TITLE
[Mono.Android] Fix ServerCertificateCustomValidator on API 21-23

### PR DESCRIPTION
**Pull request by simonrozsival**
Follow-up to #8594 to fix https://github.com/dotnet/runtime/issues/95506 on Android API 21-23

### CODE REVIEW

**Comment by simonrozsival** [comment]
The test failures seem unrelated, I can see the same tests failing for other PRs as well.

@grendello is there a way to run tests on API 21 or 23 simulator? Or do we run tests on those simulators only for the nightly builds?

**Comment by grendello** [comment]
@simonrozsival The CI here doesn't have a way to run 21 or 23 emulator tests, but the nightly builds do run them.

**Pull request merged**
