### PR TITLE
Bump to mono/mono/2020-02@ac596375

### PR DESCRIPTION
**Pull request by jonpryor**
Context: https://github.com/dotnet/runtime/pull/35008#issuecomment-657402155
Context: https://github.com/mono/mono/issues/15418
Context: https://github.com/mono/mono/issues/16763
Context: https://github.com/mono/mono/issues/20490
Context: https://github.com/mono/mono/issues/20533
Context: https://github.com/xamarin/xamarin-macios/issues/9949

Changes: https://github.com/mono/mono/compare/be2226b5a1c57df065efc4c1cf008d581e5cec7d...ac596375c762c6b8dbe3c802f0ce626004eab51c

  * mono/mono@ac596375c76: Add support for OP_FCONV_TO_I to mini-arm64.c. (#20548)
  * mono/mono@392fe5b87b2: [2020-02][watchOS] Add simwatch64 support (#20552)
  * mono/mono@a22ed3f094e: Fix potential crash for Encoder.Convert (#20522)
  * mono/mono@970783731fc: Bump to F# 5.0 (#20511)
  * mono/mono@32ab5066f72: Bump msbuild to fix a build issue
  * mono/mono@93a7fe77e8e: Ensure special static slots respect alignment. (#20506)
  * mono/mono@3db5b358413: [debugger] Switch to GC Unsafe in signal handler callbacks (#20495)
  * mono/mono@af315f44c40: [2020-02][corlib] ThreadAbortException protection for ArraySortHelper (#20468)
  * mono/mono@ca11fb0fd81: [2020-02] Bump ikvm-fork to include https://github.com/mono/ikvm-fork/pull/20 (#20452)

### CODE REVIEW

**Comment by jonpryor** [comment]
Related iOS side: https://github.com/xamarin/xamarin-macios/pull/10133

**Comment by pjcollins** [comment]
To address the CredScan issues, we can consider backporting https://github.com/xamarin/xamarin-android/pull/5155.

**Review by grendello — APPROVED** [review]

**Review by jonathanpeppers — APPROVED** [review]

**Review by dellis1972 — APPROVED** [review]

**Comment by jonpryor** [comment]
Superseded by PR #5422.

**Pull request closed without merging**
