### PR TITLE
Bump to xamarin/java.interop/main@1adb7964

### PR DESCRIPTION
**Pull request by jonpryor**
Fixes: https://github.com/xamarin/java.interop/issues/910
Fixes: https://github.com/xamarin/java.interop/issues/1139

Changes: https://github.com/xamarin/Java.Interop/compare/3c83179668cf8b6848626be14ddccc3f742a92d3...1adb7964a2033c83c298c070f2d1ab896d92671b

  * xamarin/Java.Interop@1adb7964: [generator] `generator --lang-features=emit-legacy-interface-invokers` (xamarin/Java.Interop#1145)
  * xamarin/Java.Interop@6bd7ae48: [Xamarin.Android.Tools.Bytecode] Kotlin internal prop visibility (xamarin/Java.Interop#1151)

Updates `class-parse` to better support parsing the visibility of
Kotlin properties.

Updates `generator` to emit optimized interface Invokers.

Add support for a new `$(AndroidEmitLegacyInterfaceInvokers)` MSBuild
property; when `true`, causes `generator` to emit legacy interface
Invokers.  The default value is `false`.

### CODE REVIEW

**Review by jonathanpeppers — APPROVED** [review]

**Comment by jpobst** [comment]
I think we should make `$(AndroidEmitLegacyInterfaceInvokers)` temporary somehow, so we don't end up maintaining it forever.

Perhaps making it `$(_AndroidEmitLegacyInterfaceInvokers)` and documenting that we expect it to be temporary and you should file an issue if you find yourself needing it.  (Or not really documenting it at all, and only pointing people to it if they raise an issue.)

See https://github.com/xamarin/xamarin-android/pull/6436.

Since this one also hasn't been removed, this might bring up a larger point: we should probably maintain a wiki page of planned future deprecations and removals.  We have many instances where we add a new mechanism with the intent to remove the old one once we are sure it works fine, and then we never go back and remove the old one.

**Comment by jonpryor** [comment]
Made `$(AndroidEmitLegacyInterfaceInvokers)` a private `$(_AndroidEmitLegacyInterfaceInvokers)`.

**Review by jpobst — APPROVED** [review]

**Comment by jonpryor** [comment]
@jpobst: I think https://github.com/xamarin/java.interop/commit/6bd7ae48 broke the build; the [**macOS > Tests > APKs .NET > run Xamarin.Android.JcwGen_Tests** job](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8600080&view=logs&j=929e32e6-c174-5bce-e2e0-6697aaa4c6eb&t=0719d0da-bffd-5ace-e137-7c4e9c01652f) is failing to build:

```
…/Xamarin.Android.JcwGen-Tests/KotlinUnsignedTypesTests.cs(20,4): error CS0200: Property or indexer 'UnsignedInstanceMethods.UnsignedInstanceProperty' cannot be assigned to -- it is read only
…/Xamarin.Android.JcwGen-Tests/KotlinUnsignedTypesTests.cs(26,4): error CS0200: Property or indexer 'UnsignedInstanceMethods.UshortInstanceProperty' cannot be assigned to -- it is read only
…/Xamarin.Android.JcwGen-Tests/KotlinUnsignedTypesTests.cs(32,4): error CS0200: Property or indexer 'UnsignedInstanceMethods.UlongInstanceProperty' cannot be assigned to -- it is read only
…/Xamarin.Android.JcwGen-Tests/KotlinUnsignedTypesTests.cs(38,4): error CS0200: Property or indexer 'UnsignedInstanceMethods.UbyteInstanceProperty' cannot be assigned to -- it is read only
…/Xamarin.Android.JcwGen-Tests/KotlinUnsignedTypesTests.cs(68,4): error CS0200: Property or indexer 'UnsignedInterfaceImplementedMethods.UnsignedInterfaceProperty' cannot be assigned to -- it is read only
…/Xamarin.Android.JcwGen-Tests/KotlinUnsignedTypesTests.cs(82,4): error CS0200: Property or indexer 'UnsignedAbstractImplementedMethods.UnsignedAbstractClassProperty' cannot be assigned to -- it is read only
```

**Comment by jonpryor** [comment]
The test failures are in [**UpdateLayoutIdIsIncludedInDesigner(True)**]()

**Pull request merged**
