### PR TITLE
Bump to xamarin/android-api-docs@b4084443

### PR DESCRIPTION
**Pull request by pjcollins**
Changes: https://github.com/xamarin/android-api-docs/compare/6012e04ae54cdc26174dbfe0ca32063193101b32...b4084443c0354661e2257eb698e03d3fe1d86f1b

Includes updated documentation for API 31.

Includes a new policheck exclusion database to address:

    external\android-api-docs\docs\Mono.Android\en\FrameworksIndex\xamarin-android-sdk-12.xml(28444,): error English-9: 79965:

### CODE REVIEW

**Comment by jonpryor** [comment]
Do we have any context on what `error English-9: 79965` refers to?

**Comment by jonpryor** [comment]
Obligatory:

```
% git diff --shortstat 6012e04a...b4084443 
 8098 files changed, 1612158 insertions(+), 328275 deletions(-)
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 1653 and retry the command.
```

Nothing quite like a 1.6 million line diff…

**Comment by jonpryor** [comment]
@pjcollins: `build-tools/automation/policheck-rules-db.mdb`  was added.  Are there any relevant links to documentation for this file format, how to manipulate it, etc.?

**Comment by pjcollins** [comment]
Here is the original policheck failure that is fixed by the database addition:
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=5462911&view=logs&j=d3f8649d-db33-5c22-064d-51efdff82f35&t=d6eedce2-8c18-5f30-d672-a448d57e63e9&l=15

The docs are pretty sparse and many of the relevant sub-links in this section are broken, but I was able to use the following to set up this exclusion db file: 
https://www.1eswiki.com/index.php?title=PoliCheck_Build_Task#Adding_other_PoliCheck_exclusions_from_the_PoliCheck_scan
The ["Adding Exclusions" portion of this doc](https://microsoft.sharepoint.com/sites/globalreadiness/PublicDocuments/Forms/AllItems.aspx?id=%2Fsites%2Fglobalreadiness%2FPublicDocuments%2FPoliCheckSOMUserDocumentation%2FPoliCheckHelp%5F5%2E10%2Epdf&parent=%2Fsites%2Fglobalreadiness%2FPublicDocuments%2FPoliCheckSOMUserDocumentation).

**Comment by jonpryor** [comment]
```markdown
Context: https://www.1eswiki.com/index.php?title=PoliCheck_Build_Task#Adding_other_PoliCheck_exclusions_from_the_PoliCheck_scan
Context: https://microsoft.sharepoint.com/sites/globalreadiness/PublicDocuments/Forms/AllItems.aspx?id=%2Fsites%2Fglobalreadiness%2FPublicDocuments%2FPoliCheckSOMUserDocumentation%2FPoliCheckHelp%5F5%2E10%2Epdf&parent=%2Fsites%2Fglobalreadiness%2FPublicDocuments%2FPoliCheckSOMUserDocumentation

Changes: https://github.com/xamarin/android-api-docs/compare/6012e04ae54cdc26174dbfe0ca32063193101b32...b4084443c0354661e2257eb698e03d3fe1d86f1b

	% git diff --shortstat 6012e04a...b4084443 
	 8098 files changed, 1612158 insertions(+), 328275 deletions(-)
	warning: inexact rename detection was skipped due to too many files.
	warning: you may want to set your diff.renameLimit variable to at least 1653 and retry the command.

The bump to xamarin/android-api-docs@b4084443 introduced a new
PoliCheck failure:

	external\android-api-docs\docs\Mono.Android\en\FrameworksIndex\xamarin-android-sdk-12.xml(28444,):
	error English-9: 79965: Minguo : 

The offending line:

	<Member Id="F:Android.Icu.Util.TaiwanCalendar.Minguo" />

Update PoliCheck to ignore this failure by adding
`build-tools/automation/policheck-rules-db.mdb`, which is a
Microsoft Access DB.  Two tables and rows of consequence are added:


	create table Terms (
	    TermNo int,
	    Term,Flag
	);
	insert into Terms (TermNo, Term, Flag) values (
	    1,
	    "Minguo",
	    0
	);

	create table ExceptionF (
	    FileNo int,
	    File
	);
	insert into ExceptionF (FileNo, File) values (
	    1,
	    "external\android-api-docs\docs\Mono.Android\en\FrameworksIndex\xamarin-android-sdk-12.xml"
	);
```

**Pull request merged**
