### PR TITLE
Update F# targets imports

### PR DESCRIPTION
**Pull request by mhutch**
* Make consistent with xamarin-ios
* Add modern $(VisualStudioVersion)-based import
* Add 4.0 import, remove 3.0 import

### CODE REVIEW

**Comment by mhutch** [comment]
(see also https://github.com/xamarin/xamarin-macios/pull/541)

**Comment by jonpryor** [comment]
@radical: Please review this PR.

Additionally, I have no idea how this PR interacts with our desired F# policy of "provide your own NuGet package": https://bugzilla.xamarin.com/show_bug.cgi?id=41262

> We've decided that the saner course of action is to have developers rely on the F# NuGet packages, as those will be more frequently updated that what is provided with Xamarin.Android.

**Comment by mhutch** [comment]
It doesn't interact with it at all. This is for the build, not the standard library.

Unless you're also suggesting we deprecate this target and require one to be shipped in the aforementioned NuGet.

**Comment by jonpryor** [comment]
> It doesn't interact with it at all. This is for the build, not the standard library.

I have no idea, which is why I asked. :-)

*Is* there any connection between the build system and the referenced `FSharp.Core.dll` file? Xamarin.Android is distributing `FSharp.Core.dll` v3.98.4.0; will the be a problem with the v4.0 *build system*?

**Comment by nosami** [comment]
The referenced FSharp.Core.dll file is a project template issue - it's not connected to this PR.

I've tested this PR along with NuGet'd FSharp.Core - no issues.

**Pull request merged**
