### PR TITLE
[mono-sdks] Use for mxe-Win32, mxe-Win64, llvmwin32, llvmwin64 and android toolchain

### PR DESCRIPTION
**Pull request by luhenry**
https://github.com/mono/mono/issues/6889

### CODE REVIEW

**Comment by grendello** [comment]
```
02:31:52 Done executing task "Exec". (TaskId:587)
02:31:52 Task "Exec" skipped, due to false condition; ( '%(_MonoRuntime.UseMonoSdks)' != 'False' And '%(_MonoRuntime.BuildTests)' == 'True' ) was evaluated as ( '' != 'False' And '' == 'True' ).
02:31:52 Task "Exec" skipped, due to false condition; ( '%(_MonoRuntime.UseMonoSdks)' != 'False' And '%(_MonoRuntime.BuildTests)' == 'True' ) was evaluated as ( '' != 'False' And '' == 'True' ).
02:31:52 Task "Exec" (TaskId:588)
02:31:52   Task Parameter:Command=make -j4 -C android-host-Darwin- -C runtime test (TaskId:588)
02:31:52   Task Parameter:IgnoreStandardErrorWarningFormat=True (TaskId:588)
02:31:52   Task Parameter:WorkingDirectory=/Users/builder/jenkins/workspace/xamarin-android-msbuild-pr-builder/external/mono/sdks/builds (TaskId:588)
02:31:52   make -j4 -C android-host-Darwin- -C runtime test (TaskId:588)
02:31:52   make: *** android-host-Darwin-: No such file or directory.  Stop. (TaskId:588)
```

Looks like we need a check whether `android-host-$(OS)` exists and code to create it if it doesn't

**Comment by grendello** [comment]
```
Building target "CoreCompile" in project "/mnt/jenkins/workspace/xamarin-anroid-linux-pr-builder/xamarin-android/external/Java.Interop/tools/logcat-parse/logcat-parse.csproj" ("/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets"); "Compile" depends on it.
                        Target CoreCompile:
                        Target CoreCompile needs to be built as output file 'obj/Debug/logcat-parse.exe' does not exist.
                        Task "Csc"
                                Using task Csc from Microsoft.Build.Tasks.Csc, Microsoft.Build.Tasks.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
                                Tool /usr/lib/mono/4.5/csc.exe execution started with arguments: /noconfig /debug:full /debug:portable /optimize- /out:obj/Debug/logcat-parse.exe Program.cs Properties/AssemblyInfo.cs Grefs.cs PeerInfo.cs GrefParseOptions.cs Mono.Options-PCL.cs repl.cs obj/Debug/.NETFramework,
Version=v4.5.AssemblyAttribute.cs /target:exe /unsafe+ /define:"DEBUG;TRACE" /main:Xamarin.Android.Tools.LogcatParse.Program /nostdlib /reference:/usr/lib/mono/4.5-api/System.dll /reference:../../packages/Mono.CSharp.4.0.0.143/lib/4.5/Mono.CSharp.dll /reference:../../packages/Mono.Terminal.4.2.2.0/lib/net4/M
ono.Terminal.dll /reference:/usr/lib/mono/4.5-api/System.Core.dll /reference:/usr/lib/mono/4.5-api//mscorlib.dll /warn:4
                                Environment variables being passed to the tool:
                                Microsoft (R) Visual C# Compiler version 2.6.0.62309 (d3f6b8e7)
                                Copyright (C) Microsoft Corporation. All rights reserved.
Build timed out (after 360 minutes). Marking the build as aborted.
Build was aborted
[BFA] Scanning build for known causes...
                                Tool /usr/lib/mono/4.5/csc.exe execution finished.
/usr/lib/mono/xbuild/14.0/bin/Microsoft.CSharp.targets: error : Compiler crashed with code: 143.
                        Task "Csc" execution -- FAILED
                        Done building target "CoreCompile" in project "/mnt/jenkins/workspace/xamarin-anroid-linux-pr-builder/xamarin-android/external/Java.Interop/tools/logcat-parse/logcat-parse.csproj".-- FAILED
```

It looks like roslyn hang again on the Linux bot :(

**Comment by luhenry** [comment]
@grendello about https://github.com/xamarin/xamarin-android/pull/1488#issuecomment-377166916, it's just a mistake on my end at https://github.com/xamarin/xamarin-android/pull/1488/files#diff-a0bf0207533b2c62ad9a97d37d10ec8aL37, by removing `_MonoSdksConfiguration` I break other parts depending on it.

On the roslyn hang on linux, unfortunately I wouldn't say it's related to this change.

**Comment by grendello** [comment]
Yeah, the roslyn hang is unrelated. I was just pointing it out

**Comment by luhenry** [comment]
Depends on https://github.com/mono/mono/pull/7928 which has a fix for MXE

**Comment by jonpryor** [comment]
The [**macOS+msbuild PR Build** build error](https://jenkins.mono-project.com/job/xamarin-android-msbuild-pr-builder/2413/) is *troubling*:

```
Executing: mono "/Users/builder/jenkins/workspace/xamarin-android-msbuild-pr-builder//bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/generator.exe" --public --product-version=7 --api-level=27 -o "obj/Debug/android-27/mcw
" --codegen-target=XAJavaInterop1 --fixup=metadata --preserve-enums --enumflags=enumflags --enumfields=map.csv --enummethods=methodmap.csv --enummetadata=obj/Debug/android-27/mcw/enummetadata --apiversions="/Users/builder/android-toolchain/sdk/platform-tools
/api/api-versions.xml" --annotations="/Users/builder/android-toolchain/sdk/platform-tools/api/annotations.zip" --assembly="Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" --type-map-report=obj/Debug/android-27/mcw/type-mapping.txt --enum
dir=obj/Debug/android-27/mcw obj/Debug/android-27/mcw/api.xml
...
Unhandled Exception:
System.IO.DirectoryNotFoundException: Could not find a part of the path "/Users/builder/android-toolchain/sdk/platform-tools/api/api-versions.xml"
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options)
...
```

Which in turn implies that `$HOME/android-toolchain/sdk/platform-tools/api/api-versions.xml` doesn't exist. *Why doesn't it exist?* It does on my machine. That file is also used by other successful builds, e.g. [Build 948](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android/948), which even contains an inflation message!

```
unzip "/Users/builder/android-archives/platform-tools_r27.0.1-darwin.zip" -d "/var/folders/l8/73t5whsx7dj5v5gh_bn7zxlr0000gn/T/w6ccxo3r.voe/u5tp3vic.mmq"
...
inflating: /var/folders/l8/73t5whsx7dj5v5gh_bn7zxlr0000gn/T/w6ccxo3r.voe/u5tp3vic.mmq/platform-tools/api/api-versions.xml
```

**Comment by luhenry** [comment]
@jonp @grendello good to merge? There is only 1 test failure and it isn't related to the Mono SDKs.

**Pull request merged**
