### PR TITLE
Bump LibZipSharp to 1.0.5 to include pdb files

### PR DESCRIPTION
**Pull request by dellis1972**
We need to start shipping pdb files with our installer. This is so we can get better stack traces if we get errors. LibZipSharp 1.0.2 which we were using did not contain any pdb files. This PR bumps LibZipSharp to 1.0.5 which does include the pdb files.

### CODE REVIEW

**Comment by dellis1972** [comment]
Needs https://github.com/xamarin/monodroid/pull/1032

**Comment by jonpryor** [comment]
Please rebase this atop 7200d66a756e78f2ee4119d03a431f4d0ef60d2a so that `ant` is no longer used, which should allow the **Xamarin.Android (Prepare Bundle)** job to complete.

**Comment by jonpryor** [comment]
Squash-and-merge commit message:

```
Changes: https://github.com/xamarin/LibZipSharp/compare/1.0.2...1.0.5
Changes: https://github.com/xamarin/monodroid/compare/3234426db1bec31d46ecbe8b588a7199511ca3e2...9a1dbc5f56717b88f952c6597a52c14dd5226030

Context: https://github.com/xamarin/xamarin-android/pull/3624

We would like to start shipping `.pdb` files within our installer
This is so we can get better stack traces if we get errors, and also
so that we can use our installer for **SymbolCheck** purposes; see
also PR #3624.

LibZipSharp 1.0.2 didn't contain any `.pdb` files.  LibZipSharp 1.0.5
has been updated to contain `.pdb` files.

Bump to LibZipSharp so that we can rely upon and redistribute `.pdb`
files for LibZipSharp.
```

**Pull request merged**
