### PR TITLE
Api level 27 enumification

### PR DESCRIPTION
**Pull request by atsushieno**

### CODE REVIEW

**Comment by atsushieno** [comment]
This depends on https://github.com/xamarin/xamarin-android/pull/1044

**Comment by jonpryor** [comment]
This PR needs a [xamarin-android-api-compatibility bump](https://github.com/xamarin/xamarin-android-api-compatibility/commit/6a26294329428a1369462bba32e91d5c83164994).

**Comment by jonpryor** [comment]
I do not understand how/why this PR depends on PR #1044. :-(

**Comment by atsushieno** [comment]
Because, these changes were generated based on the changes on 1044. If we apply these changes without that PR, the technology we generated these changes are lost, and we cannot make further changes anymore.

**Comment by atsushieno** [comment]
I'm feeling sorry but I brought somewhat messy situation here.

PR #1044 is practically required but it expects map.csv changes that otherwise causes regression due to the fact that the changes contain API Level 27 changes brought by *this* PR.

This PR with the updated xamarin-android-api-compatibility should cause no regression. So after merging this PR, #1044 will become green. So nominally PR #1044 now depends on this PR while this PR depends on that in practice.

Therefore, could this PR be merged first and then go for 1044?

**Comment by jonpryor** [comment]
> could this PR be merged first and then go for 1044?

Once it's green, Yes.

**Comment by atsushieno** [comment]
Okay, it's green now.

**Comment by atsushieno** [comment]
Let me actually rebase so that "use-merge-commit" makes better sense.

**Pull request merged**
