### PR TITLE
Wrap connection exceptions in HttpRequestException

### PR DESCRIPTION
**Pull request by grendello**
Fixes: https://github.com/xamarin/xamarin-android/issues/7629

Whenever a Java backend connection fails for any reason, we wrap the 
thrown exception in `HttpRequestException` as described in the 
`HttpClient.SendAsync` documentation.

### CODE REVIEW

**Comment by simonrozsival** [comment]
Shouldn't we also fix the other `WebException`s that are thrown from AndroidMessageHandler? (for example https://github.com/xamarin/xamarin-android/blob/main/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs#L428-L436)

**Comment by grendello** [comment]
@simonrozsival I don't want to touch these. We've had a lot of issues filed in the past regarding exception types, I don't want to revisit these unless I absolutely have to... :)

**Comment by grendello** [comment]
@simonrozsival let's leave the legacy Xamarin as it is... :)

**Pull request merged**
