### PR TITLE
Bump to xamarin/java.interop/master@a8f68e56

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Changes: https://github.com/xamarin/java.interop/compare/3894cd76...a8f68e56

* Use `const` instead of `static readonly`
* [generator] Disable [SupportedOSPlatform] until .NET 5/6.
* [generator] Wrap SupportedOSPlatformAttribute in NET
* [build] use $(RollForward)=Major for console apps
* [Java.Interop] Conditionally call ManagedPeer.Init()
* [generator] Add [SupportedOSPlatform] in assemblies using ApiSince
* [global.json] Update Microsoft.Build.NoTargets to 2.0.1.

### CODE REVIEW

**Comment by jonpryor** [comment]
Looks like we do need this: https://github.com/xamarin/java.interop/pull/779

because of the `DotNetBuild` failures, e.g. https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4370096&view=ms.vss-test-web.build-test-results-tab&runId=18107834&resultId=100055&paneView=attachments

```
/Users/runner/work/1/s/bin/TestRelease/temp/DotNetBuildandroid.21-armandroid.21-arm64android.21-x86android.21-x64False/obj/Debug/net6.0-android/UnnamedProject.AssemblyInfo.cs(21,38):
warning CS0436: The type 'SupportedOSPlatformAttribute' in '/Users/runner/work/1/s/bin/TestRelease/temp/DotNetBuildandroid.21-armandroid.21-arm64android.21-x86android.21-x64False/obj/Debug/net6.0-android/generated/src/__NamespaceMapping__.cs'
conflicts with the imported type 'SupportedOSPlatformAttribute' in 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
Using the type defined in '/Users/runner/work/1/s/bin/TestRelease/temp/DotNetBuildandroid.21-armandroid.21-arm64android.21-x86android.21-x64False/obj/Debug/net6.0-android/generated/src/__NamespaceMapping__.cs'.
```

**Review by radekdoulik — COMMENTED** [review]
There's another issue with `SupportedOSPlatformAttribute`.

    /Users/runner/work/1/s/tests/Mono.Android-Tests/Java.Interop-Tests/obj/Release/net6.0-android/Java.Interop-Tests.NET.AssemblyInfo.cs(21,38): error CS0433: The type 'SupportedOSPlatformAttribute' exists in both 'Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' and 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' [/Users/runner/work/1/s/tests/Mono.Android-Tests/Java.Interop-Tests/Java.Interop-Tests.NET.csproj] [/Users/runner/work/1/s/tests/Mono.Android-Tests/Runtime-Microsoft.Android.Sdk/Mono.Android.NET-Tests.csproj]

**Comment by radekdoulik** [comment]
I think the problem here is that the attribute class is also added to `Mono.Android` assembly and we are still building it with `netcoreapp3.1` TFM. 

@jpobst do we need it generated in multiple places? Would it be possible to just add it to legacy `Mono.Android`?

**Comment by jonathanpeppers** [comment]
So... `Mono.Android.csproj` should probably be `net6.0`, right?

But we can't do that because `msbuild` with Mono can't build anything net5.0 or higher...

So that leaves us needing to build this entire repo with `dotnet build`?

**Comment by jpobst** [comment]
I think this is a special case because we use `[InternalsVisibleTo]`:

https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Properties/AssemblyInfo.cs.in#L32

Normally the `Mono.Android.dll` version will not be visible to other assemblies.

What was the fix for the other place we were seeing this? Can it be applied to `Java.Interop-Tests`?

**Comment by jonathanpeppers** [comment]
I added `NET` to `$(DefineContants)` for the `netcoreapp3.1` build. Let's see if that works.

**Comment by jpobst** [comment]
We can also just comment out this code until we are building with `net6.0` if this is blocking people.

**Comment by jonathanpeppers** [comment]
@jpobst yeah, it didn't work, got a bunch of errors like:
```
error CS0234: The type or namespace name 'SupportedOSPlatformAttribute' does not exist in the namespace 'System.Runtime.Versioning' 
```
Could we put it behind a feature flag? It seems like it work work in apps, but not `Mono.Android.csproj`.

**Comment by jpobst** [comment]
We can comment it out for now, until we are compiling .NET 5/6 properly.  It's really only needed for `Mono.Android.dll`.  No user assemblies are going to have `api-since` data.

**Comment by radekdoulik** [comment]
Weird error, trying rebuild.

    /var/folders/9k/brhlbh9d729gxd3m_9j0t23w0000gn/T/tmpddf75c38a8ce438aaf930877db7fd94d.exec.cmd: line 2: 35321 Illegal instruction: 4  /Users/builder/Library/Android/dotnet/dotnet pack -p:Configuration=Release -p:NuGetLicense=/Users/builder/azdo/_work/1/s/xamarin-android/external/monodroid/tools/scripts/License.txt -p:AndroidRID=android.21-arm -p:AndroidABI=armeabi-v7a "/Users/builder/azdo/_work/1/s/xamarin-android/build-tools/create-packs/Microsoft.Android.Runtime.proj"

**Review by radekdoulik — APPROVED** [review]

**Pull request merged**
