### PR TITLE
Bump mono to 5.6.0.0

### PR DESCRIPTION
**Pull request by lambdageek**
We should take #631 first.

### CODE REVIEW

**Comment by lambdageek** [comment]
I see 4 failures:

```
Xamarin.Android.Build.Tests.BuildTest.BuildAotApplication("armeabi-v7a",True,True)
Xamarin.Android.Build.Tests.BuildTest.BuildAotApplicationAndBundle("armeabi-v7a",True,True)
Xamarin.Android.Build.Tests.BuildTest.GeneratorValidateMultiMethodEventName(False,null,"<attr path=\"/api/package/interface[@...","")
Xamarin.Android.Build.Tests.BuildTest.GeneratorValidateMultiMethodEventName(False,null,"\n\t\t\t\t\t<attr path=\"/api/package...","String s")
```

The last two are the same as what #631 is seeing (https://bugzilla.xamarin.com/show_bug.cgi?id=57828), but the first two `"armeabi-v7a"` are new to this branch.

**Comment by jonpryor** [comment]
@lambdageek: The `GeneratorValidateMultiMethodEventName` errors are -- I *hope* -- fixed in PR #732. 

The `BuildAotApplication` errors should be related to mono's AOT compilers.

**Comment by lambdageek** [comment]
Thanks @jonpryor.  

I built XA locally and grabbed a build log from BuildAotApplication and here's what I've got in there:

```
		[aot-compiler stdout] Mono Ahead of Time compiler - compiling assembly /Users/alekseyk/work/platform-android/xamarin-android/bin/TestDebug/temp/BuildAotApplication_armeabi-v7a_True_True/obj/Release/android/assets/shrunk/mscorlib.dll
		[aot-compiler stdout] AOTID 2F1E37E5-7BEB-174F-3D96-7630770DFB42
		[aot-compiler stdout] * Assertion at /Users/alekseyk/work/platform-android/xamarin-android/external/mono/mono/mini/mini-llvm.c:7402, condition `err == 0' not met
		[aot-compiler stdout] 
```

So looks like an LLVM problem

**Comment by lambdageek** [comment]
Better piece of a log file (`BuildAotApplicationAndBundle_armeabi-v7a_True_True`):

```
		[aot-compiler stdout] * Assertion at /Users/alekseyk/work/platform-android/xamarin-android/external/mono/mono/mini/mini-llvm.c:7402, condition `err == 0' not met
		[aot-compiler stdout] 
		[aot-compiler stderr] Block containing LandingPadInst must be jumped to only by the unwind edge of an invoke.
		[aot-compiler stderr]   %17 = landingpad { i8*, i32 } personality void ()* @mono_personality
		[aot-compiler stderr]           catch i32* @type_info_321
: error XA3001: Could not AOT the assembly: mscorlib.dll

```

**Comment by lambdageek** [comment]
We think the AOT failures are due to mono/mono@2c59986b441cbcabc139feea58cb80aa3b09371a. @vargaz is looking into it.

**Comment by borgdylan** [comment]
A similar Aot failure happens not in LLVM mode as well:
```Assertion: should not be reached at /mnt/jenkins/workspace/xamarin-android-linux/xamarin-android/external/mono/mono/mini/mini-arm.c:5888```

**Comment by lambdageek** [comment]
Hi @borgdylan, could you give me a pointer to a jenkins log where you noticed that failure?  Is it happening with this PR or in xamarin-android master or someplace else?  That particular line (5888) seems to be a pretty different part of mono - it would be great to know the particular testcase that triggers the assertion.  If you can, please file a bug at https://bugzilla.xamarin.com with the details. Thanks!

**Comment by borgdylan** [comment]
It happened locally when using XA-master.  I can either file a bug, or keep the conversation going on gitter.

**Comment by borgdylan** [comment]
How would I get the stack trace for the assertion? My build seems to get its mono from a prebuilt CI archive.

**Comment by jonpryor** [comment]
[Looks like the Jenkins shutdown aborted the build](https://jenkins.mono-project.com/view/Xamarin.Android/job/xamarin-android-pr-builder/1752/):

```
FATAL: command execution failed
java.nio.channels.ClosedChannelException
        at org.jenkinsci.remoting.protocol.NetworkLayer.onRecvClosed(NetworkLayer.java:154)
        at org.jenkinsci.remoting.protocol.impl.NIONetworkLayer.ready(NIONetworkLayer.java:142)
        at org.jenkinsci.remoting.protocol.IOHub$OnReady.run(IOHub.java:721)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused: java.io.IOException: Backing channel 'JNLP4-connect connection from 167.220.148.19/167.220.148.19:55649' is disconnected.
...
```

We'll need to re-run this once Jenkins is back up.

**Comment by akoeplinger** [comment]
I talked with @lambdageek and since I'm making good progress on mono-2017-10 it probably makes more sense to spend the effort there :) I cherry-picked the relevant fixes from this branch.

**Pull request closed without merging**
