### PR TITLE
[mono-runtimes] Use pdb2mdb from bundle

### PR DESCRIPTION
**Pull request by alexischr**
Extracted from https://github.com/xamarin/xamarin-android/pull/3039

### CODE REVIEW

**Comment by jonpryor** [comment]
@jonathanpeppers: I believe that this PR *depends upon* PR #3039, and thus #3039 needs to be completed first.

**Comment by alexischr** [comment]
I now moved the inclusion of pdb2mdb.exe in this PR so that they are independent.

**Comment by alexischr** [comment]
@jonathanpeppers @jonpryor this now builds, could you please review?

**Comment by jonpryor** [comment]
Commit message for squash-and-merge:

```
Context: https://github.com/mono/mono/issues/11397
Context: https://github.com/xamarin/xamarin-android/projects/10

Instead of using the "pdb2mdb" sources from mono within
`Xamarin.Android.Build.Tasks.dll`, instead use the `pdb2mdb.exe`
assembly contained within the [mono archive][0].

This reduces the amount of source code used from the mono submodule,
and we wish to eventually remove the mono submodule.

[0]: https://github.com/xamarin/xamarin-android/projects/10
```

**Comment by jonpryor** [comment]
One last thing we need to do here: *add* `pdb2mdb.exe` to `build-tools/installers/create-installers.targets`.  Otherwise the resulting installers will not work, because `Xamarin.Android.Build.Tasks.dll` will have an assembly reference to `pdb2mdb.exe`, which won't exist.

**Comment by alexischr** [comment]
@jonpryor done

**Pull request merged**
