### PR TITLE
Correct `Outputs` of `_GenerateAndroidResourceDir` target

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Review by jonathanpeppers — CHANGES_REQUESTED** [review]
Unfortunately, it looks like this target was correct before...

Because we use:
```xml
<CopyIfChanged SourceFiles="@(_AndroidResolvedResources)"
	DestinationFiles="@(_AndroidResourceDest)"
	CompareFileLengths="False"
>
```
If the target decides to run, it may not copy all files or update their timestamps. Consider a file that is newer with unchanged contents, `<CopyIfChanged/>` wouldn't copy the file or update the timestamp.

Your change here would potentially make this target run every time in this case.

We are potentially not using MSBuild to the correct extent, due  to `<CopyIfChanged/>` existing at all? But this code came over from Xamarin -- we might have a chance to refactor *one day*.

**Comment by jonathanpeppers** [comment]
^^ running the build to find out if any test fails -- seems useful.

**Comment by Youssef1313** [comment]
@jonathanpeppers The target as-is can cause failures due to not being run when it should run.

**Comment by jonathanpeppers** [comment]
> The target as-is can cause failures due to not being run when it should run.

@Youssef1313 that actually sounds like we should adjust the `Inputs` to fix this. Can you share a `.binlog` example of this? Thanks.

**Comment by Youssef1313** [comment]
@jonathanpeppers I lost the binlog I had somehow, but I think to reproduce this you can have a successful build first and get a binlog from that, and then from the binlog find the value of `_AndroidResourceDest` property, and delete that file, then have another build.

I actually have modified `C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Common.targets` locally with the change I made in this PR and have been working with it for few days and haven't seen issues

**Comment by jonathanpeppers** [comment]
Our CI was broken due to: https://github.com/dotnet/install-scripts/issues/387

I'll retry and see what CI results are.

**Comment by jonathanpeppers** [comment]
Maybe @dellis1972 has some thoughts when he's back? The test run looks OK, I just reran a couple flaky steps.

**Comment by jonpryor** [comment]
I too would like @dellis1972' input.  That said… :-)

*Philosophically* -- to my mind/understanding, anyway -- if a target creates a file which is used as `Inputs` elsewhere, then it *should* be listed as `Outputs`.  So this PR is partially correct.

*However*, philosophically, all `Outputs` *should also* be `<Touch/>`ed (or equivalent) before exiting the Target.

The rationale is because of [Incremental Builds](https://github.com/xamarin/xamarin-android/blob/b10a4d52dbb368a8c6f6084160546efc229b2b16/Documentation/guides/MSBuildBestPractices.md#incremental-builds):

> If the timestamps of the `Outputs` are all newer than the `Inputs`, MSBuild will skip the target completely.

If you *don't* `<Touch/>` the outputs, then I think we could have this state of affairs:

 1. Initial build: everything good.
 2. `$(MSBuildProjectFullPath)` is changed (or some other `Inputs` is altered) in such a way that `@(_AndroidResourceDest)` is *not* updated.  (`touch App.csproj`)
 3. Build again.
 4. Build again.

The expectation/desire is that (3) will cause `_GenerateAndroidResourceDir` to be run again -- an `Inputs` changed! -- while (4) *should not* re-run `_GenerateAndroidResourceDir`.

I *believe* that (4) will *always* re-run, *because* the timestamp for `$(MSBuildProjectFullPath)` will always be newer than one/all of the timestamps in `@(_AndroidResourceDest)`.  This would make for a bad incremental build experience.

**Comment by dellis1972** [comment]
I think our current implementation is ok. Unless we want make this a Partial target... which might produce some build speed improvements...

**Comment by dellis1972** [comment]
@Youssef1313 I believe we fixed this via https://github.com/unoplatform/uno/commit/6d912e00b49c182167f9ba2a95e7b6d9b42c20eb in uno. 
So we can probably close this PR now.

**Pull request closed without merging**
