### PR TITLE
Android P API enumification.

### PR DESCRIPTION
**Pull request by atsushieno**
git diff on remaining-int-*.txt shows what remains (and many of them are
covered by comments on enumification-helpers).

(There should be up-to-date documentation on how to work on enumification
so that anyone can take over the work even after I left the project.)

### CODE REVIEW

**Comment by atsushieno** [comment]
Wait, I didn't commit my local Configuration.props change.

**Comment by atsushieno** [comment]
The previous PR (gone now) had important files - map.csv and methodmap.csv (!) Now they are included too.

The changes can be applied either with or without changes in BuildEverything.mk and Mono.Android.projitems. It is up to our branching/cherry-picking plan to deal with the new API. So far they are not included in this PR.

xamarin-android-api-compatibility PR is created and I hope it is easy to review this time.

**Comment by jonpryor** [comment]
https://github.com/xamarin/xamarin-android-api-compatibility/pull/18 has been merged.

Please update this PR to include a xamarin-android-api-compatibility bump.

**Comment by atsushieno** [comment]
build

**Comment by jonpryor** [comment]
Please rebase atop 796b8288943c81099cb9feedf50006587d8c8c45 so that we can (hopefully) get more complete build logs.

**Comment by jonpryor** [comment]
Thank you for rebasing.  In this case, we likely didn't need the build logs; the build is failing because we have [API breakage](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3436/API_20Compatibility_20Checks/).

*Lots* of API breakage.

I believe that this PR needs to [update `$(STABLE_API_LEVELS)` to contain API-28](https://github.com/xamarin/xamarin-android/blob/d80a5c1aa7ef5d1adbcc815dfef70ce8df6502fd/build-tools/scripts/BuildEverything.mk#L32), otherwise it'll be comparing `$(lastword $(STABLE_API_LEVELS))` (i.e. 27) against xamarin-android-api-compatibility, which explains why there is *so much* breakage.

**Comment by atsushieno** [comment]
I guess we are still not sure if we want to mark it stable, but the PR is updated.

**Comment by jonpryor** [comment]
Something seems rather bizarre with the unit test failures, e.g. [Xamarin_Android_Build_Tests_BuildTest_BuildApplicationWithSpacesInPath_True_True_True____Debug](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3448/testReport/junit/Xamarin.Android.Build.Tests.BuildTest/BuildApplicationWithSpacesInPath/Xamarin_Android_Build_Tests_BuildTest_BuildApplicationWithSpacesInPath_True_True_True____Debug/):

```
  /usr/bin/java -jar /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/proguard/lib/proguard.jar -include '/Users/builder/android-toolchain/sdk//tools/proguard/proguard-android.txt' -include 'obj/Release/proguard/proguard_xamarin.cfg' -include 'obj/Release/proguard/proguard_project_references.cfg' -include 'obj/Release/proguard/proguard_project_primary.cfg' -injars "'obj/Release/android/bin/classes/../classes.zip'(!META-INF/MANIFEST.MF):'/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v8.1/mono.android.jar'(!META-INF/MANIFEST.MF):'Hello (World).jar'(!META-INF/MANIFEST.MF):'/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/android-support-multidex.jar'(!META-INF/MANIFEST.MF)" -libraryjars '/Users/builder/android-toolchain/sdk/platforms/android-27/android.jar' -outjars obj/Release/proguard/__proguard_output__.jar -optimizations !code/allocation/variable  (TaskId:186)
  ...
  Note: the configuration refers to the unknown class 'com.google.vending.licensing.ILicensingService' (TaskId:186)
  ...
PROGUARD : warning : mono.android.app.admin.DevicePolicyManager_OnClearApplicationUserDataListenerImplementor: can't find superclass or interface android.app.admin.DevicePolicyManager$OnClearApplicationUserDataListener [/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/TestDebug/temp/BuildReleaseAppWithA InIt(TrueTrueTrue)/UnnamedProject.csproj]
...
  Note: there were 11 references to unknown classes. (TaskId:186)
PROGUARD : warning : there were 38 unresolved references to classes or interfaces. [/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/TestDebug/temp/BuildReleaseAppWithA InIt(TrueTrueTrue)/UnnamedProject.csproj]
           You may need to add missing library jars or update their versions. (TaskId:186)
           If your code works fine without the missing classes, you can suppress (TaskId:186)
           the warnings with '-dontwarn' options. (TaskId:186)
           (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass) (TaskId:186)
  java.io.IOException: Please correct the above warnings first. (TaskId:186)
  	at proguard.Initializer.execute(Unknown Source) (TaskId:186)
  	at proguard.ProGuard.initialize(Unknown Source) (TaskId:186)
  	at proguard.ProGuard.execute(Unknown Source) (TaskId:186)
  	at proguard.ProGuard.main(Unknown Source) (TaskId:186)
        You should check your configuration for typos. (TaskId:186)
        (http://proguard.sourceforge.net/manual/troubleshooting.html#unknownclass) (TaskId:186)
/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/Debug/lib/xamarin.android/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2464,3): error MSB6006: "java" exited with code 1. [/Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/bin/TestDebug/temp/BuildReleaseAppWithA InIt(TrueTrueTrue)/UnnamedProject.csproj]
```

**Comment by jonpryor** [comment]
Reviewing the `java -jar` invocation in my [previous comment](https://github.com/xamarin/xamarin-android/pull/1821#issuecomment-400059710), this part sticks out to me:

```
java -jar ... …/bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v8.1/mono.android.jar
```

Why is it using *`v8.1`* instead of `v9.0`?

Looking earlier in the failing build log, we see:

```
  ResolveSdksTask: (TaskId:7)
    ...
    TargetFrameworkVersion: v6.0 (TaskId:7)
    UseLatestAndroidPlatformSdk: True (TaskId:7)
  Trying build-tools path: /Users/builder/android-toolchain/sdk/build-tools/28.0.0-rc1 (TaskId:7)
  ResolveSdksTask Outputs: (TaskId:7)
    AndroidApiLevel: 27 (TaskId:7)
    AndroidApiLevelName: 27 (TaskId:7)
```

`UseLatestAndroidPlatformSdk`=True, yet the output API level is 27, not 28.

My suspicion is that we need to update `$(AndroidLatestStableFrameworkVersion)`.

**Comment by jonpryor** [comment]
build

**Comment by jonpryor** [comment]
build

**Comment by atsushieno** [comment]
Finally Jenkins did the job.

**Pull request merged**
