### PR TITLE
Add new assemblies to mono-runtimes.targets

### PR DESCRIPTION
**Pull request by akoeplinger**
Those were added as part of the netstandard effort.

### CODE REVIEW

**Comment by atsushieno** [comment]
Aren't those new assemblies just reference assemblies? I believe whatever listed in this *.projitems are implementation assemblies, and our implementation assemblies are different from whatever .NET Core has. Could you elaborate and explain why we need those assemblies listed there?

**Comment by akoeplinger** [comment]
@atsushieno no, these are real implementation assemblies (though they throw NotImplementedException in most cases). We need these so the NuGet packages from MS don't cause build breaks when added to our projects as they specify we provide these assemblies.

/cc @marek-safar

**Comment by marek-safar** [comment]
Correct, these are real code assemblies which implements extended API introduced by nestandard

**Comment by atsushieno** [comment]
Do you mean, those assemblies that you newly added are resolved *directly* to xbuild-frameworks/MonoAndroid/v1.0? I thought it should be resolved to xbuild-frameworks/MonoAndroid/v1.0/Facades just like existing PCLs (there already is e.g. System.Xml.XPath.XPathDocumetn.dll in that directory). Should netstandard assembly resolution be implemented so?

**Comment by marek-safar** [comment]
No they are one layer lower. There are referenced by xxx/Facades

**Comment by akoeplinger** [comment]
> Do you mean, those assemblies that you newly added are resolved directly to xbuild-frameworks/MonoAndroid/v1.0?

Yes.

> (there already is e.g. System.Xml.XPath.XPathDocumetn.dll in that directory).

This adds System.Xml.XPath.XmlDocument.dll which is a different assembly, and as Marek said sits one level lower 😄

**Comment by atsushieno** [comment]
Alright, just read through mcs/class/Facades and understood there are ongoing reorganization. Thanks for the explanation guys.

**Pull request merged**
