### PR TITLE
Bump to mono:2018-08

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by jonpryor** [comment]
The [**macOS PR Build** fails after 10 minutes](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3743/): 

```
  /Users/builder/jenkins/workspace/xamarin-android-pr-builder/xamarin-android/external/mono/mono/metadata/w32file-unix.c:2424:66: error: use of undeclared identifier 'COPYFILE_CLONE'
```

**Comment by EgorBo** [comment]
The failing test needs fresher external/mono/external/corefx to include https://github.com/mono/corefx/blob/master/src/System.Collections/tests/Generic/Comparers/EqualityComparer.Generic.Tests.cs#L65

**Comment by marek-safar** [comment]
@jonpryor is this ready to be merged?

The API change in System.Security.Cryptography.Pkcs.ContentInfo is not breaking change as the type is sealed

**Comment by marek-safar** [comment]
@jonpryor could you please confirm the readiness of this PR from your side?

**Comment by luhenry** [comment]
🎉

**Pull request merged**
