### PR TITLE
Bump to Java.Interop/master/5ff46d03

### PR DESCRIPTION
**Pull request by jonpryor**
`generator` refactoring and cleanups.

Add `Java.Interop.MarshalMemberBuilder.GetMarshalMethodName()`.

`jnimarshalmethod-gen.exe` now updates the "original" assembly,
instead of emitting marshal methods into a separate assembly.

Within marshal methods, use a new `JniRuntime.JniValueManager`
temporary. This allows saving ~18944 bytes on `Mono.Android.dll.`

Use `msbuild` by default.

### CODE REVIEW

**Comment by jonpryor** [comment]
Reading through the [**macOS PR Build** log](https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3055/), the error appears to be coming from `generator`:

```generator.exe obj/Debug/api.xml.class-parse --only-xml-adjuster --xml-adjuster-output=obj/Debug/api.xml ...
  resolving assembly /Volumes/Seagate4TB/work/xamarin-android/bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/mscorlib.dll. (TaskId:1143)
  resolving assembly /Volumes/Seagate4TB/work/xamarin-android/bin/Debug/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v1.0/Java.Interop.dll. (TaskId:1143)
...
  Error while processing type '[Class] com.xamarin.android.Bxc37706Throwable': Type 'java.lang.Throwable' was not found. (TaskId:1143)
  Error while processing type '[Class] com.xamarin.android.Bxc4288': Type 'java.lang.Object' was not found. (TaskId:1143)
...
```

Before that `generator --only-xml-adjuster` invocation, `obj/Debug/api.xml.class-parse` contains a declaration for `Timing`:

```xml
    <class
      abstract="false"
      deprecated="not deprecated"
      jni-extends="Ljava/lang/Object;"
      extends="java.lang.Object"
      extends-generic-aware="java.lang.Object"
      final="false"
      name="Timing"
      jni-signature="Lcom/xamarin/android/Timing;"
      static="false"
      visibility="public">
```

That type doesn't make it into `obj/Debug/api.xml` (`generator --only-xml-adjuster` output). As such, the following `generator` invocation doesn't generate a `Com.Xamarin.Android.Timing` type, resulting in the C# error:

```
Timing.cs(93,55): error CS0115: 'Timing.JniPeerMembers': no suitable method found to override
```

One or more of the `Java.Interop/tools/generator` changes contained within this PR broke things. :-(

**Comment by jonathanpeppers** [comment]
My fix didn't work:
```
Unhandled Exception: (TaskId:1238)
  System.NullReferenceException: Object reference not set to an instance of an object (TaskId:1238)
    at Xamarin.Android.Tools.ApiXmlAdjuster.JavaTypeName.Parse (System.String dottedFullName) [0x0001d] in <11936892d93c401aa2ef9cff368ade49>:0  (TaskId:1238)
    at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiTypeResolverExtensions.Parse (Xamarin.Android.Tools.ApiXmlAdjuster.JavaApi api, System.String name, Xamarin.Android.Tools.ApiXmlAdjuster.JavaTypeParameters[] contextTypeParameters) [0x00001] in <11936892d93c401aa2ef9cff368ade49>:0  (TaskId:1238)
    at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiTypeResolverExtensions.ResolveType (Xamarin.Android.Tools.ApiXmlAdjuster.JavaType type) [0x00060] in <11936892d93c401aa2ef9cff368ade49>:0  (TaskId:1238)
    at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiTypeResolverExtensions.Resolve (Xamarin.Android.Tools.ApiXmlAdjuster.JavaInterface i) [0x00001] in <11936892d93c401aa2ef9cff368ade49>:0  (TaskId:1238)
    at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiTypeResolverExtensions.Resolve (Xamarin.Android.Tools.ApiXmlAdjuster.JavaApi api) [0x000d9] in <11936892d93c401aa2ef9cff368ade49>:0  (TaskId:1238)
    at Xamarin.Android.Tools.ApiXmlAdjuster.Adjuster.Process (System.String inputXmlFile, MonoDroid.Generation.GenBase[] gens, System.String outputXmlFile, System.Int32 reportVerbosity) [0x00052] in <28e58b1255ee4cadb2924a483739b335>:0  (TaskId:1238)
    at Xamarin.Android.Binder.CodeGenerator.Run (Xamarin.Android.Binder.CodeGeneratorOptions options, Java.Interop.Tools.Cecil.DirectoryAssemblyResolver resolver) [0x00368] in <28e58b1255ee4cadb2924a483739b335>:0  (TaskId:1238)
    at Xamarin.Android.Binder.CodeGenerator.Run (Xamarin.Android.Binder.CodeGeneratorOptions options) [0x00029] in <28e58b1255ee4cadb2924a483739b335>:0  (TaskId:1238)
    at Xamarin.Android.Binder.CodeGenerator.Main (System.String[] args) [0x00014] in <28e58b1255ee4cadb2924a483739b335>:0  (TaskId:1238)
```

The commit that broke this is: https://github.com/xamarin/java.interop/commit/84014f4a735f65c3aa666597f05ce6de7d984bb6

Moving the constructor around to partially happen in `OnValidate`  turns out to be a bad idea. Was originally trying to address: https://github.com/xamarin/java.interop/pull/303#discussion_r183396613

I will try another idea tomorrow, and test in `xamarin-android` _before_ sending another PR.

**Comment by jonpryor** [comment]
Good News! It builds!

Bad news: unit test failures: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3070/testReport/

**Comment by jonathanpeppers** [comment]
What? How is this happening!!!
```
public new override unsafe string Message {
```

**Comment by jonathanpeppers** [comment]
I must have broken something else to cause this, but I don't see how this line would ever be right: 

https://github.com/xamarin/java.interop/blob/6f04b002698a3d3614342322f613c1abda4f32e3/tools/generator/Property.cs#L262

These don't compile:
- `new virtual`
- `new override`

**Comment by jonathanpeppers** [comment]
One failure still, which I thought might happen: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3075/testReport/junit/Xamarin.Android.Build.Tests/BindingBuildTest/RemoveEventHandlerResolution___Debug/

Looking into it.

**Pull request merged**
