### PR TITLE
[Xamarin.Android.Build.Tasks] fix for android:name="$" in manifest

### PR DESCRIPTION
**Pull request by jonathanpeppers**
Fixes: https://github.com/xamarin/xamarin-android/issues/1698

In the project reproducing this issue, the Xamarin.Firebase.lid NuGet
produces an `AndroidManifest.xml` with the following line:

    <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />

Unfortunately our manifest merging code is throwing an exception and
producing a warning such as:

    Xamarin.Android.Common.targets(1910,3): warning : Name cannot begin with the '$' character, hexadecimal value 0x24.

We also aren't getting the contents of this `AndroidManifest.xml`
merged, so this is definitely an issue!

The exception is coming from the following code:

    var existing = (name != null) ?
        doc.XPathSelectElement (string.Format ("/manifest/{0}[@android:name='{1}']", top.Name.LocalName, XmlConvert.VerifyNCName (name.Value)), nsResolver) :
        doc.XPathSelectElement (string.Format ("/manifest/{0}", top.Name.LocalName));

Apparently `XmlConvert.VerifyNCName` throws an exception if the input
value contains a `$`.

It appears it has been this way for quite some time, prior to becoming
open source:

https://github.com/xamarin/xamarin-android/blame/bb8183c8c16667b18ba9197e78294b17a0af532c/src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs#L444

I suspect the original goal was to validate the XPath expression
wouldn't throw an exception, but it seems to work fine to use the
value as-is. Let's just not call `XmlConvert.VerifyNCName` at all.

After the fix, I get additional lines in my
`obj/Debug/android/AndroidManifest.xml`:

    <permission android:name="com.companyname.DollarSignProb.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="com.companyname.DollarSignProb.permission.C2D_MESSAGE" />

So it is now properly merging the `AndroidManifest.xml`.

Other changes:
- Updated `ManifestTest.MergeLibraryManifest` test so it also verifies
  this fix
- Added `XA4302` as part of the effort towards:
  https://github.com/xamarin/xamarin-android/issues/1560

### CODE REVIEW

**Comment by kjeremy** [comment]
Yes! This should finally remove the need to manually add the firebase receivers to the manifest.

**Comment by jonpryor** [comment]
Brilliant!

Please add a new test or update an existing test to verify the behavior with:

```xml
<permission android:name="${applicationId}.permission.C2D_MESSAGE"  android:protectionLevel="signature" />
```

**Comment by jonathanpeppers** [comment]
Yeah this has some extra code testing this XML in ManifestTest @jonpryor

**Comment by Gatoreno** [comment]
hi i tried to add those permission but my error persist, can you post a more detailed example of where in the whole manifest should i put those lines?

**Comment by jonathanpeppers** [comment]
@gatoreno this PR will be in a future release of Visual Studio (and Xamarin.Android)

You don’t quite give enough detail as to what your issue is. Could you consider opening an issue? (giving more detail of course)

**Comment by Gatoreno** [comment]
@jonathanpeppers i'm getting the same 

> name cannot begin with the '$' character hexadecimal value 0x24
and i've been reading all post about this issue , i tried to follow ur steps adding persmissions but i still have the same error :S well right now it's a warning but it doesn't allow me to compile. ty

**Comment by jonathanpeppers** [comment]
@Gatoreno Sorry, this fix isn't in a release yet, and there isn't a workaround I know of...

If you are getting a warning that means the `AndroidManifest.xml` from whichever library you are using is not being included in your app. You will need to manually add the required changes to your app's `AndroidManifest.xml`, does that make sense?

**Comment by Gatoreno** [comment]
thank you very much for your time sir @jonathanpeppers i'll keep working on it

**Pull request merged**
