### PR TITLE
[build] Include ThirdPartyNotices in workload packs

### PR DESCRIPTION
**Pull request by pjcollins**
Adds the `THIRD-PARTY-NOTICES.TXT` file to all packs that contain a
license file.

### CODE REVIEW

**Comment by pjcollins** [comment]
@jonpryor Looks like this works fine, do we want to include it in any other packs?
```
Archive:  /Users/peter/Downloads/Microsoft.Android.Sdk.Darwin.34.99.0-ci.pr.gh8455.32.nupkg
  Length      Date    Time    Name
---------  ---------- -----   ----
      518  10-24-2023 13:51   _rels/.rels
      779  10-24-2023 13:51   Microsoft.Android.Sdk.Darwin.nuspec
    22507  10-24-2023 17:36   LICENSE
   ...
   244596  10-24-2023 17:42   ThirdPartyNotices.txt
      150  10-24-2023 17:43   data/net8.0-android34/AndroidApiInfo.xml
     4325  10-24-2023 13:52   [Content_Types].xml
---------                     -------
281167360                     381 files
```

**Comment by jonpryor** [comment]
@pjcollins: should we call it `THIRD-PARTY-NOTICES.TXT`?  That's what other packages appear to do:

```sh
% find ~/.nuget/packages/microsoft.* -iname THIRD-PARTY\*
$HOME/.nuget/packages/microsoft.aspnetcore.app.ref/7.0.9/THIRD-PARTY-NOTICES.TXT
…
$HOME/.nuget/packages/microsoft.netcore.app.host.osx-x64/7.0.9/THIRD-PARTY-NOTICES.TXT
…
# 689 total
```

**Comment by jonpryor** [comment]
@pjcollins [asked](https://github.com/xamarin/xamarin-android/pull/8455#issuecomment-1777758735):

> do we want to include it in any other packs?

I think it should go into any workload pack that redistributes 3rd party code, which might very well be *all* of them?  Certainly `Microsoft.Android.Sdk.Darwin` and `Microsoft.Android.Sdk.Windows`.

**Comment by pjcollins** [comment]
> @pjcollins [asked](https://github.com/xamarin/xamarin-android/pull/8455#issuecomment-1777758735):
> 
> > do we want to include it in any other packs?
> 
> I think it should go into any workload pack that redistributes 3rd party code, which might very well be _all_ of them? Certainly `Microsoft.Android.Sdk.Darwin` and `Microsoft.Android.Sdk.Windows`.

At a glance the Ref/Runtime packs only appear to contain our content, so I think the inclusion in the only the SDK packs should be sufficient.

**Review by grendello — APPROVED** [review]

**Pull request merged**
