### PR TITLE
Add new api R preview 2 with enumeration

### PR DESCRIPTION
**Pull request by gugavaro**
Updating Api R to preview 2
Adding Enumification based on preview 2

Due to a bug on generator, https://github.com/xamarin/java.interop/issues/613 
we can't enumify VibrationEffectEffectType using the "enumificator tool", instead we need to manually add it for now.

### CODE REVIEW

**Comment by jonpryor** [comment]
…in the vain hope that the Windows build error will just disappear if we rebuild...

**Comment by jonpryor** [comment]
The Windows build failure *did* disappear on rebuild.

**Comment by jonpryor** [comment]
Squash-and-merge subject:

```
[Mono.Android] Android API-R Developer Preview 2 Binding (#4468)
```

Body:

```
Context: https://web.archive.org/web/20200307182928/https://developer.android.com/preview/overview

Android 11 [Developer Preview 2 has been released][0].

  * [API diff vs. Developer Preview 1][1]
  * [API diff vs. API-29][2]

Google's documented timeline for Android 11 is unchanged wrt a20be392:

  * Developer Preview 3 in April
  * Beta 1 in May
  * Beta 2 in June
    This contains the final APIs and official SDK.
  * Beta 3 and final release sometime in Q3, 2019.

For a change vs. previous releases, we are testing out some new
workflows and tooling around enumification, and the updated API-R
binding in `Mono.Android.dll` v10.0.99 has been enumified.

Note: due to a [generator bug][3], the
`Android.OS.VibrationEffectEffectType` enum must be manually bound.

[0]: https://android-developers.googleblog.com/2020/03/android-11-developer-preview-2.html
[1]: https://developer.android.com/sdk/api_diff/r-dp2-incr/changes
[2]: https://developer.android.com/sdk/api_diff/r-dp2/changes
[3]: https://github.com/xamarin/java.interop/issues/613
```

**Comment by gugavaro** [comment]
> Squash-and-merge subject:
> 
> ```
> [Mono.Android] Android API-R Developer Preview 2 Binding (#4468)
> ```
> 
> Body:
> 
> ```
> Context: https://web.archive.org/web/20200307182928/https://developer.android.com/preview/overview
> 
> Android 11 [Developer Preview 2 has been released][0].
> 
>   * [API diff vs. Developer Preview 1][1]
>   * [API diff vs. API-29][2]
> 
> Google's documented timeline for Android 11 is unchanged wrt a20be392:
> 
>   * Developer Preview 3 in April
>   * Beta 1 in May
>   * Beta 2 in June
>     This contains the final APIs and official SDK.
>   * Beta 3 and final release sometime in Q3, 2019.
> 
> For a change vs. previous releases, we are testing out some new
> workflows and tooling around enumification, and the updated API-R
> binding in `Mono.Android.dll` v10.0.99 has been enumified.
> 
> Note: due to a [generator bug][3], the
> `Android.OS.VibrationEffectEffectType` enum must be manually bound.
> 
> [0]: https://android-developers.googleblog.com/2020/03/android-11-developer-preview-2.html
> [1]: https://developer.android.com/sdk/api_diff/r-dp2-incr/changes
> [2]: https://developer.android.com/sdk/api_diff/r-dp2/changes
> [3]: https://github.com/xamarin/java.interop/issues/613
> ```

Doc looks great!!!

**Comment by brendanzagaeski** [comment]
*Draft release notes*

Here is the note I'm planning to include for this pull request for the Xamarin.Android 10.3 Previews:

````
### Preview bindings for Android 11 Developer Preview 2

This version includes preview bindings for the [second Developer Preview of
Android 11][android-11-preview-2] from Google.  See the [Android 11 Developer
Preview documentation][android-11-upstream] for additional information about the
behavior and API changes in this new Android version.  To try the bindings for
the new APIs in a Xamarin.Android project, set **Compile using Android version:
(Target Framework)** to **Android 10.0.99 (R)** under the **Application** tab of
the Visual Studio project property pages.  This sets the
`TargetFrameworkVersion` property to `v10.0.99` in the *.csproj* file:

```xml
<TargetFrameworkVersion>v10.0.99</TargetFrameworkVersion>
```

[android-11-preview-2]: https://android-developers.googleblog.com/2020/03/android-11-developer-preview-2.html
````

This note will be merged with the [section for Developer Preview 1](https://docs.microsoft.com/xamarin/android/release-notes/10/10.3#preview-bindings-for-android-11-developer-preview) when the Preview notes are combined into the final Xamarin.Android 10.3 general availability Release notes.

To suggest something different, feel free to reply in this PR or add a `Documentation/release-notes/4468.md` file with the new suggestion. Thanks!

**Pull request merged**
