### PR TITLE
Add Gentoo Linux support to OS detection #7441

### PR DESCRIPTION
**Pull request by cyborgyn**
build-tools\xaprepare update to handle Gentoo Linux OS detection and package handling.

Implementation example is based on ArchLinux implementation.

Solves issue:
[#7441](https://github.com/xamarin/xamarin-android/issues/7441)

### CODE REVIEW

**Review by grendello — APPROVED** [review]

**Comment by cyborgyn** [comment]
Corrected the mistake, sry for overlooking it.

**Review by grendello — APPROVED** [review]

**Pull request merged**
