### PR TITLE
Bump LibZipSharp, Mono.Unix and xamarin-android-tools.

### PR DESCRIPTION
**Pull request by dellis1972**

### CODE REVIEW

**Review by grendello — APPROVED** [review]

**Comment by jonathanpeppers** [comment]
I guess we need to bump monodroid first?
```
(_ResolveXamarinAndroidTools target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.Debugging.targets(109,2): error MSB4062: The "Xamarin.Android.Tasks.ResolveXamarinAndroidTools" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Build.Debugging.Tasks.dll. Could not load file or assembly 'Microsoft.Android.Build.BaseTasks, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 

    1 Warning(s)
    1 Error(s)
```

**Comment by dellis1972** [comment]
I'm including a test monodroid bump to see if this passes without strong naming. Since we need to strong name java.interop etc.

**Comment by jonathanpeppers** [comment]
@dellis1972 I think it's working now.

So we'll have to merge monodroid (it will be broken temporarily), and then come back to this?

**Comment by dellis1972** [comment]
> @dellis1972 I think it's working now.
> 
> So we'll have to merge monodroid (it will be broken temporarily), and then come back to this?

Correct.

**Pull request merged**
