### PR TITLE
Bump to mono:2018-02

### PR DESCRIPTION
**Pull request by baulig**

### CODE REVIEW

**Comment by baulig** [comment]
build

**Comment by luhenry** [comment]
@jonpryor regarding https://jenkins.mono-project.com/job/xamarin-anroid-linux-pr-builder/2240/consoleFull#-1781834693ae1da302-70c8-400e-9aed-bc1cd416a1c7, is that a known issue? Does that impact this integration or is it going to be fixed whenever we merge it?

**Comment by jonpryor** [comment]
```
Missing dependency detected. For Linux we do not know how to install program `mono`, version >= 5.12.0.
```

Means you need to ask @directhex to install a system mono that onto the Linux Azure VM which satisfies the version dependency.

**Comment by jonpryor** [comment]
Proposed squash-and-merge commit message:

```
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=11771
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=15051
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=19436
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=45901
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=56071
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=58413
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=58413
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=58413
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=59184
fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60065
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60225
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60298
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60359
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60568
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60756
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60848
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60862
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60900
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60904
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=60986
Fixes: https://github.com/mono/mono/issues/59400
Fixes: https://github.com/mono/mono/issues/6169
Fixes: https://github.com/mono/mono/issues/6187
Fixes: https://github.com/mono/mono/issues/6192
Fixes: https://github.com/mono/mono/issues/6255
Fixes: https://github.com/mono/mono/issues/6264
Fixes: https://github.com/mono/mono/issues/6266
Fixes: https://github.com/mono/mono/issues/6281
Fixes: https://github.com/mono/mono/issues/6283
Fixes: https://github.com/mono/mono/issues/6320
Fixes: https://github.com/mono/mono/issues/6339
Fixes: https://github.com/mono/mono/issues/6343
Fixes: https://github.com/mono/mono/issues/6349
Fixes: https://github.com/mono/mono/issues/6379
Fixes: https://github.com/mono/mono/issues/6383
Fixes: https://github.com/mono/mono/issues/6401.
Fixes: https://github.com/mono/mono/issues/6411
Fixes: https://github.com/mono/mono/issues/6414
Fixes: https://github.com/mono/mono/issues/6490
Fixes: https://github.com/mono/mono/issues/6721
Fixes: https://github.com/mono/mono/issues/6767
Fixes: https://github.com/mono/mono/issues/6777
Fixes: https://github.com/mono/mono/issues/6848
Fixes: https://github.com/mono/mono/issues/6940
Fixes: https://github.com/mono/mono/issues/6948
Fixes: https://github.com/mono/mono/issues/6998
Fixes: https://github.com/mono/mono/issues/7016
Fixes: https://github.com/mono/mono/issues/7085
Fixes: https://github.com/mono/mono/issues/7086
Fixes: https://github.com/mono/mono/issues/7095
Fixes: https://github.com/mono/mono/issues/7137
Fixes: https://github.com/mono/mono/issues/7184
Fixes: https://github.com/mono/mono/issues/7240
Fixes: https://github.com/mono/mono/issues/7262
Fixes: https://github.com/mono/mono/issues/7289
Fixes: https://github.com/mono/mono/issues/7338
Fixes: https://github.com/mono/mono/issues/7356
Fixes: https://github.com/mono/mono/issues/7364
Fixes: https://github.com/mono/mono/issues/7378
Fixes: https://github.com/mono/mono/issues/7389
Fixes: https://github.com/mono/mono/issues/7460
Fixes: https://github.com/mono/mono/issues/7535
Fixes: https://github.com/mono/mono/issues/7536
Fixes: https://github.com/mono/mono/issues/7610
Fixes: https://github.com/mono/mono/issues/7624
Fixes: https://github.com/mono/mono/issues/7637
Fixes: https://github.com/mono/mono/issues/7655
Fixes: https://github.com/mono/mono/issues/7657
Fixes: https://github.com/mono/mono/issues/7685
Fixes: https://github.com/mono/mono/issues/7786
Fixes: https://github.com/mono/mono/issues/7792
Fixes: https://github.com/mono/mono/issues/7822
Fixes: https://github.com/mono/mono/issues/7860
Fixes: https://github.com/mono/mono/issues/8089
Fixes: https://github.com/mono/mono/issues/8267
Fixes: https://github.com/mono/mono/issues/8409
Fixes: https://github.com/xamarin/maccore/issues/628
Fixes: https://github.com/xamarin/maccore/issues/629
Fixes: https://github.com/xamarin/maccore/issues/673
Fixes: https://github.com/xamarin/maccore/issues/673
Fixes: https://github.com/xamarin/xamarin-android/issues/1561\#issuecomment-381736716
```

**Pull request merged**
