### PR TITLE
[monodroid] `AndroidEnablePreloadAssemblies` causes runtime crash.

### LINKED ISSUE #5838: .NET 6: `$(AndroidEnablePreloadAssemblies)`=False by default
Context: d13d0f972a4eb663251b2a6b5a934c59a6789db1
Context: b90d3ab717cbfd38b2e6a307b4387d2d6cf04af8
Context: PR #5790
Context: PR #5811
Context? 9e6ce03ca2d72f5415a2a1650185ba46113cc3dd

For .NET 6 we want `$(AndroidEnablePreloadAssemblies)`=False by default, so that all assemblies don't need to be loaded as part of process startup.

This was done in PR #5790 / d13d0f972a4eb663251b2a6b5a934c59a6789db1 , after which point we found a problem (missed during PR review, alas):

 1. .NET 6 +
 2. "Debug" build +
 3. Fast Deployment +
 4. App launch

resulted in a crash (!) in [`DebuggingTest.ClassLibraryMainLauncherRuns()`](https://github.com/xamarin/xamarin-android/blob/bf4f4f42af26cdddb46087deed59aae8424f7942/tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs#L74-L124):

```
android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
    at MyLibrary.MainActivity.OnCreate(Bundle bundle)
    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
    at com.xamarin.classlibrarymainlauncherruns.MainActivity.n_onCreate(Native Method)
    at com.xamarin.classlibrarymainlauncherruns.MainActivity.onCreate(MainActivity.java:29)
```

The cause of the crash is that, *because* not all assemblies are loaded as part of process startup, [`ResourceIdManager.UpdateIdValues()`](https://github.com/xamarin/xamarin-android/blob/bf4f4f42af26cdddb46087deed59aae8424f7942/src/Mono.Android/Android.Runtime/ResourceIdManager.cs#L9-L31) isn't able to update all fields in all `Resource` types to have the values from the *app* `Resource.designer.cs` file.  Consequently, the values may be invalid, thus the `NullReferenceException`.

In order to actually default `$(AndroidEnablePreloadAssemblies)`=False for .NET 6, we need to figure out how to make this work.

Perhaps we can enable `$(AndroidLinkResources)`=True (9e6ce03ca2d72f5415a2a1650185ba46113cc3dd) for all .NET 6 builds?  What would the build-time impacts be?

### PR DESCRIPTION
**Pull request by dellis1972**
Context: https://github.com/xamarin/xamarin-android/issues/5838

Setting `$(AndroidEnablePreloadAssemblies)`=False, which disables
assembly preloading (see af02a65a), could result in a crash when:

 1. The launched `Activity` isn't located within the "main App
    assembly", the assembly built as part of the `App.apk` build, and

 2. The launched `Activity` uses Android Resource IDs, and

 3. Those Android Resource IDs differ between the Library project
    build and the Application project build (usually the case).

This setup is exemplified by the
`DebuggingTest.ClassLibraryMainLauncherRuns()` unit test.

Our current Resource architecture assumes/ensures that there is
Only One™ `Resource` type mentioned by an assembly-level
`ResourceDesignerAttribute` custom attribute, with
`ResourceDesignerAttribute.IsApplication`=true:

	[assembly: global::Android.Runtime.ResourceDesignerAttribute("My.Resource", IsApplication=true)]

The `ResourceIdManager.UpdateIdValues()` method looks for this
attribute in all loaded assemblies, and when (if) found, will
invoke the `UpdateIdValues()` static method on the specified type.

The problem is that only the *App assembly* `Resource.UpdateIdValues()`
method does anything, and if the App assembly isn't loaded -- which
may be the case when the `Activity` loaded isn't from the App assembly
and assembly preload is disabled -- then:

 1. `ResourceIdManager.UpdateIdValues()` never finds the
    `ResourceDesignerAttribute`, and

 2. `Resource.UpdateIdValues()` is never invoked, and

 3. Android Resource IDs in non-App assemblies are never updated to
    contain their correct values.

Thus, attempting to use an Android resource may result in unexpected
failures:

	var button = FindViewById<Button> (Resource.Id.myButton);
	// `button` is null, because `Resource.Id.myButton` has the wrong value.

This can result in `NullReferenceException`s:

	android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
	    at MyLibrary.MainActivity.OnCreate(Bundle bundle)
	    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
	    at com.xamarin.classlibrarymainlauncherruns.MainActivity.n_onCreate(Native Method)
	    at com.xamarin.classlibrarymainlauncherruns.MainActivity.onCreate(MainActivity.java:29)

Fix this by *always* loading the App assembly during process startup,
which also happens to be the *first* assembly listed within the
generated `mono.MonoPackageManager_Resources.Assemblies` array, which
is provided to `Runtime.initInternal()`.

### CODE REVIEW

**Review by grendello — APPROVED** [review]

**Comment by jonpryor** [comment]
@dellis1972: as per current understanding, *any* app should crash if/when:

 1. `$(AndroidEnablePreloadAssemblies)`=False, and

 2. The launched `Activity` isn't located within the "main App
    assembly", the assembly built as part of the `App.apk` build, and

 3. The launched `Activity` uses Android Resource IDs, and

 4. Those Android Resource IDs differ between the Library project
    build and the Application project build (usually the case).

for both .NET 6 & Legacy.

Could you please `update/"overload" the [`DebuggingTest.ClassLibraryMainLauncherRuns()`]( https://github.com/xamarin/xamarin-android/blob/bf4f4f42af26cdddb46087deed59aae8424f7942/tests/MSBuildDeviceIntegration/Tests/DebuggingTest.cs#L74-L124) unit test so that `$(AndroidEnablePreloadAssemblies)`=False?

**Comment by jonpryor** [comment]
WIP commit message:

```markdown
Context: https://github.com/xamarin/xamarin-android/issues/5838

Setting `$(AndroidEnablePreloadAssemblies)`=False, which disables
assembly preloading (see af02a65a), could result in a crash when:

 1. The launched `Activity` isn't located within the "main App
    assembly", the assembly built as part of the `App.apk` build, and

 2. The launched `Activity` uses Android Resource IDs, and

 3. Those Android Resource IDs differ between the Library project
    build and the Application project build (usually the case).

This setup is exemplified by the
`DebuggingTest.ClassLibraryMainLauncherRuns()` unit test.

Our current Resource architecture assumes/ensures that there is
Only One™ `Resource` type mentioned by an assembly-level
`ResourceDesignerAttribute` custom attribute, with
`ResourceDesignerAttribute.IsApplication`=true:

	[assembly: global::Android.Runtime.ResourceDesignerAttribute("My.Resource", IsApplication=true)]

The `ResourceIdManager.UpdateIdValues()` method looks for this
attribute in all loaded assemblies, and when (if) found, will
invoke the `UpdateIdValues()` static method on the specified type.

The problem is that only the *App assembly* `Resource.UpdateIdValues()`
method does anything, and if the App assembly isn't loaded -- which
may be the case when the `Activity` loaded isn't from the App assembly
and assembly preload is disabled -- then:

 1. `ResourceIdManager.UpdateIdValues()` never finds the
    `ResourceDesignerAttribute`, and

 2. `Resource.UpdateIdValues()` is never invoked, and

 3. Android Resource IDs in non-App assemblies are never updated to
    contain their correct values.

Thus, attempting to use an Android resource may result in unexpected
failures:

	var button = FindViewById<Button> (Resource.Id.myButton);
	// `button` is null, because `Resource.Id.myButton` has the wrong value.

This can result in `NullReferenceException`s:

	android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
	    at MyLibrary.MainActivity.OnCreate(Bundle bundle)
	    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState)
	    at com.xamarin.classlibrarymainlauncherruns.MainActivity.n_onCreate(Native Method)
	    at com.xamarin.classlibrarymainlauncherruns.MainActivity.onCreate(MainActivity.java:29)

Fix this by *always* loading the App assembly during process startup,
which also happens to be the *first* assembly listed within the
generated `mono.MonoPackageManager_Resources.Assemblies` array, which
is provided to `Runtime.initInternal()`.
```

**Comment by jonpryor** [comment]
@dellis1972: additionally, we should verify behavior with an F# app, as F# apps *don't* include the Resources into the "App" assembly.  How's *that* work?

**Comment by dellis1972** [comment]
@jonpryor it took a while but I managed to put a F# project together which repo's the error on the stable release. Testing this fix with it works, so this seems to work for both C# and F#.

**Pull request merged**
