### PR TITLE
set MONO_ANDROID_PATH environment variable with msbuild path of the V…

### PR DESCRIPTION
**Pull request by tondat**
…S instance `$(VsInstallRoot)\MSBuild\Xamarin\Android`

### CODE REVIEW

**Comment by tondat** [comment]
I found a related bug: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/543597

**Comment by jonpryor** [comment]
@tondat: I don't understand *why* this is necessary. Is there a "call stack" that helps explain what the problem is?

The only place I can easily see where `%MONO_ANDROID_PATH` is used is within `MonoDroidSdk` (`androidtools` repo), and IIRC it's only used if an explicit path isn't provided to `MonoDroidSdk.Refresh()`. VS *does* provide the appropriate path value.

**Comment by kzu** [comment]
Command-line builds from MSBuild 15+ prompts @jonpryor ;)

**Comment by directhex** [comment]
build

**Comment by tondat** [comment]
@jonpryor: this is the error, after run the Install target from a cmd line. 

https://gist.github.com/tondat/e8c5fa46c742af883dca9acf63988c73#file-gistfile1-txt-L148

the issue is that the MonoDroidSdk.RuntimePath is not initialized:
https://github.com/xamarin/androidtools/blob/b46af90754e2dff51f489f22a195d31fedad2283/Xamarin.AndroidTools/PlatformPackage.cs#L48

MonoDroidSdk.RuntimePath execute a GetSdk():
https://github.com/xamarin/androidtools/blob/master/Xamarin.AndroidTools/MonoDroidSdk.cs#L169

and GetSdk execute a Refresh without parameters:
https://github.com/xamarin/androidtools/blob/master/Xamarin.AndroidTools/MonoDroidSdk.cs#L107

making an initialize on an new instance of MonoDroidSdkWindows with a null value of runtimePath:
https://github.com/xamarin/androidtools/blob/master/Xamarin.AndroidTools/MonoDroidSdk.cs#L126

and the initialize execute the findruntime because runtimePath is null:
https://github.com/xamarin/androidtools/blob/master/Xamarin.AndroidTools/Sdks/MonoDroidSdkBase.cs#L71

the fix is set the MONO_ANDROID_PATH envvar in order to return the value here:
https://github.com/xamarin/androidtools/blob/master/Xamarin.AndroidTools/Sdks/MonoDroidSdkWindows.cs#L39

I think that this envvar is null because we are running the Install target out of process of VS.

**Comment by jonpryor** [comment]
> I think that this envvar is null because we are running the Install target out of process of VS.

That would make sense, but why is the `Install` target run out-of-process? This is something I was not previously aware of.

**Comment by tondat** [comment]
It is running in this way from various releases yet.

We have the same issue with command line now, so there are a change on XA that affects this behavior.
I remember that on previous version this line had been used to initialize MonoDriodSdk:

https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Xamarin.Android.Sdk.props#L33-L36

but now these variables are not be used to it. And I am trying to detect the change  but I cannot for the moment to found the exactly line...

**Comment by tondat** [comment]
this is the line (from cycle9 to d15-4):

https://github.com/xamarin/xamarin-android/blob/d15-4/src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs#L144 

and it changed on d15-5:
https://github.com/xamarin/xamarin-android/blob/d15-5/src/Xamarin.Android.Build.Tasks/Tasks/ResolveSdksTask.cs#L144

**Comment by jonpryor** [comment]
The `MonoDroidSdk` type was removed from xamarin-android in 8942eca00a219882f48b5bccf11452f35ddbcaee, though `androidtools` retained its own copy. I'm not sure why this wasn't previously an issue, though; I don't see any code that ever *exported* `$MONO_ANDROID_PATH` as part of the build process.

Rephrased: When was [devdiv 543597](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/543597) introduced?

At the same time, does that matter?

At present, I would prefer a different fix: Instead of exporting `%MONO_ANDROID_PATH%`, we should instead update `monodroid/tools/msbuild` (`Tasks/InstallPackageAssemblies`?) to call the `androidtools`' `MonoDroidSdk.Refresh()` method with appropriate parameters.

@dellis1972? How does this sound?

**Comment by dellis1972** [comment]
@jonpryor I was a bit nervous about exporting `%MONO_ANDROID_PATH%` in this manner. 
The problem with `MonoDroidSdk.Refresh()` is how do we tell it what paths to use? Leaving the params blank will try to use the old paths and not the `$(VSInstallRoot)`.

**Comment by jonpryor** [comment]
I believe (hope, pray?) that the [originating bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/543597) is fixed by:

* https://github.com/xamarin/androidtools/commit/56e42018907ddecf0c5965ab6a94b8714c5c4985
* https://github.com/xamarin/monodroid/pull/731

I am thus closing this PR.

**Pull request closed without merging**
