### PR TITLE
Bump to mono:2019-12

### PR DESCRIPTION
**Pull request by directhex**

### CODE REVIEW

**Comment by directhex** [comment]
Sam should be assigned to this but I don't know his GH username

**Comment by grendello** [comment]
@BrzVlad Keep an eye on this PR https://github.com/xamarin/xamarin-android/pull/3979, it includes fix for the LLVM TPN generation

**Comment by BrzVlad** [comment]
@jonpryor @grendello Looks like this doesn't have any outstanding failures. I would expect after the llvm tpn fix and the other windows fix for it to be green.

**Comment by jonathanpeppers** [comment]
Let's see what happens now?

**Comment by BrzVlad** [comment]
The failures from CI don't seem related (still that Xamarin.Android.Build.Tests and some random disk full on jenkins). I ran tests locally on an arm64 device (`make run-all-tests`) and I didn't notice any mono crashes, just a few build failures that seemed to happen also with a d16-4 that I had locally.

What's the next step from here ? Should we trigger some device tests with this branch ? I don't think the PR jobs do device testing ?

**Comment by jonpryor** [comment]
The iOS equivalent: https://github.com/xamarin/xamarin-macios/pull/7537

**Comment by BrzVlad** [comment]
I didn't notice any mono specific failures over the last weeks. The only recurring failure is the one from `Ubuntu PR Debug Pipeline Build` (job which I think passed once). I wasn't able to reproduce it locally due to unrelated xamarin-android build failures on my ubuntu that blocked me from testing.

@jonpryor @grendello Could you guys take it from here and ping me if you detect any mono issues.

**Comment by jonpryor** [comment]
For the eventual squash-and-merge, the "Subject" should be:

```
Bump to mono/mono/2019-12@b61db514 (#3981)
```

The commit body should be:

```
Changes: https://github.com/mono/api-snapshot/compare/6f14e433d28249f07ccbbee3b28fa737253a4163...5babd5163bbee51001aac17caae43b6782d37ce3

	$ git diff --shortstat 6f14e433...5babd516
	 16 files changed, 164 insertions(+), 444 deletions(-)

Changes: https://github.com/mono/boringssl/compare/4ca62c57796d70d3717f695a726c72a859968594...d7b108ee11053845610bf5155672ff609f84e8db

	$ git diff --shortstat 4ca62c57...d7b108ee
	 1 file changed, 1 insertion(+)

Changes: https://github.com/mono/cecil/compare/cb6c1ca9aaef869841bfc3e2e7407b81b979b875...a6a7f5c0f48c2cbbec699726bbac0816ae097003

	$ git diff --shortstat cb6c1ca9...a6a7f5c0
	 47 files changed, 587 insertions(+), 444 deletions(-)

Changes: https://github.com/mono/corefx/compare/10a41e9f9828b3e299215406eadfde2ee4c9b29f...7926498255800de2da1243f3c12b5b571b4f1006

	$ git diff --shortstat 10a41e9f...792649825
	 44 files changed, 868 insertions(+), 236 deletions(-)

Changes: https://github.com/mono/mono/compare/18920a83f423fb864a2263948737681968f5b2c8...b61db514ab601886be944f1784dc730a418b4d3b

	$ git diff --shortstat 18920a83...b61db514
        1361 files changed, 43214 insertions(+), 90267 deletions(-)

Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1005448
Context: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1005448
Context: https://github.com/ksp-ckan/ckan/issues/2881
Context: https://github.com/mono/mono/issues/10559
Context: https://github.com/mono/mono/issues/12249
Context: https://github.com/mono/mono/issues/12337
Context: https://github.com/mono/mono/issues/12995
Context: https://github.com/mono/mono/issues/13777
Context: https://github.com/mono/mono/issues/15006
Context: https://github.com/mono/mono/issues/15010
Context: https://github.com/mono/mono/issues/15181
Context: https://github.com/mono/mono/issues/15805
Context: https://github.com/mono/mono/issues/15845
Context: https://github.com/mono/mono/issues/16026
Context: https://github.com/mono/mono/issues/16206
Context: https://github.com/mono/mono/issues/16410
Context: https://github.com/mono/mono/issues/16513
Context: https://github.com/mono/mono/issues/16557
Context: https://github.com/mono/mono/issues/16588
Context: https://github.com/mono/mono/issues/16632
Context: https://github.com/mono/mono/issues/16701
Context: https://github.com/mono/mono/issues/17053
Context: https://github.com/mono/mono/issues/17084
Context: https://github.com/mono/mono/issues/17133
Context: https://github.com/mono/mono/issues/17151
Context: https://github.com/mono/mono/issues/17161
Context: https://github.com/mono/mono/issues/17190
Context: https://github.com/mono/mono/issues/17278
Context: https://github.com/mono/mono/issues/17278
Context: https://github.com/mono/mono/issues/17317
Context: https://github.com/mono/mono/issues/17367
Context: https://github.com/mono/mono/issues/17389
Context: https://github.com/mono/mono/issues/17546
Context: https://github.com/mono/mono/issues/17549
Context: https://github.com/mono/mono/issues/17569
Context: https://github.com/mono/mono/issues/17601
Context: https://github.com/mono/mono/issues/17665
Context: https://github.com/mono/mono/issues/17687
Context: https://github.com/mono/mono/issues/17737
Context: https://github.com/mono/mono/issues/17790
Context: https://github.com/mono/mono/issues/17869
Context: https://github.com/mono/mono/issues/17878
Context: https://github.com/mono/mono/issues/17916
Context: https://github.com/mono/mono/issues/17924
Context: https://github.com/mono/mono/issues/17926
Context: https://github.com/mono/mono/issues/17931
Context: https://github.com/mono/mono/issues/18213
Context: https://github.com/mono/mono/issues/18221
Context: https://github.com/mono/mono/issues/27106
```

**Pull request merged**
